### ISSUE TITLE
double-l bug

### ISSUE THREAD

**Issue by sirlaughalot90** [ivan-lednev/obsidian-day-planner#101]
There is a weird bug where the plugin won't render the Gannt chart when there is a word with two Ls in a row in the to-do block. I noticed this rather weird bug when trying to enter a call as one to do item for the day. 

![bug-dayplanner](https://user-images.githubusercontent.com/20352339/126944919-85a97642-e8d6-44c6-a91d-f6071dbde7af.png)

**Comment by ivan-lednev** [comment]
Closing this as stale.
