### ISSUE TITLE
Feature request: name breaks

### ISSUE THREAD

**Issue by 27escape** [ivan-lednev/obsidian-day-planner#102]
Really enjoying using your plugin, many thanks for sharing it. 

I would like the BREAK to allow text after it, so that the breaks can be named, lunch/coffee/etc

This is how it would work in the gantt and markdown

## Day Planner
```mermaid
gantt
    dateFormat  HH-mm
    axisFormat %H:%M
    %% Current Time: 12:45:22
    section Tasks
    START     :07-00, 60mm
    Project     :08-10, 260mm
    Project     :13-00, 120mm
    DevOps drop-in      :15-00, 60mm
    stand up     :16-00, 30mm
    END     :16-30, 0mm
    section Breaks
    lunch     :12-30, 30mm
```

- [x] 07:00 START
- [x] 08:10 Project
- [ ] 12:30 BREAK lunch
- [ ] 13:00 Project
- [ ] 15:00 DevOps drop-in 
- [ ] 16:00 stand up
- [ ] 16:30 END

And a nice picture

![image](https://user-images.githubusercontent.com/332780/126955553-25952d57-bc8a-43c2-aa37-e1ea7a724749.png)

Many thanks

**Comment by ivan-lednev** [comment]
Closing this as stale
