### ISSUE TITLE
Feature request done and active task in gantt

### ISSUE THREAD

**Issue by 27escape** [ivan-lednev/obsidian-day-planner#103]
In the mermaid gantt text it is possible to mark items as done or active and have them colored differently. This is achieved by using done or active before the time with a trailing comma.

Here is the mermaid gantt text and markdown

## Day Planner
```mermaid
gantt
    dateFormat  HH-mm
    axisFormat %H:%M
    %% Current Time: 12:45:22
    section Tasks
    START     :done, 07-00, 60mm
    Project     :done, 08-10, 260mm
    Project     :13-00, 120mm
    DevOps drop-in      :15-00, 60mm
    stand up     :16-00, 30mm
    END     :16-30, 0mm
    section Breaks
    BREAK     :active, 12-30, 30mm
```

- [x] 07:00 START
- [x] 08:10 Project
- [ ] 12:30 BREAK
- [ ] 13:00 Project
- [ ] 15:00 DevOps drop-in 
- [ ] 16:00 stand up
- [ ] 16:30 END

and a nice picture

![image](https://user-images.githubusercontent.com/332780/126955180-07cac43f-5f9c-47a7-80a6-e71ef5c5fe24.png)

Many thanks

**Comment by ivan-lednev** [comment]
Mermaid is no longer supported.
