### ISSUE TITLE
Calendar plugin flashing

### ISSUE THREAD

**Issue by phlind** [ivan-lednev/obsidian-day-planner#105]
When I activate both the calendar plugin and the day planner, the current day of the calendar view in the sidebar is flashing every 1 or 2 seconds, probably due to the updating day planner. Could this be resolved somehow? Thanks!

**Comment by perinm** [comment]
Perhaps you could deactivate Mermaid Gantt option, in Day Planer's Plugin Options, 

can you please see if that solves the problem?

**Comment by perinm** [comment]
I would like to set myself frequency in which mermaid Gantt graph is updated. Every 5s or so is messing up sync system between multiple devices. Should be every 10 minutes or so something like this.

**Comment by kohane27** [comment]
> Perhaps you could deactivate Mermaid Gantt option, in Day Planer's Plugin Options,
> 
> can you please see if that solves the problem?

Hello! Not OP but I'm facing the exact problem. Deactivating Mermaid Gantt does resolve the blinking/flashing issue, but it also means that I can't use Mermaid Gantt, which is not exactly a resolution either. Any other idea?

**Comment by Schobs** [comment]
Also facing same issue. Any resolution?

**Comment by ivan-lednev** [comment]
Should be fixed in 0.7.0.
