### ISSUE TITLE
Sort tasks by time

### ISSUE THREAD

**Issue by AJKock** [ivan-lednev/obsidian-day-planner#106]
Hi
When I create my task template I separate what want to do (Read article, write report) every day from random interuption tasks (buy this, fetch that, email this person, etc.) or meetings. They are all given a time, but when shown on the timeline, they are in the order of the list and not TIME. Would it be possible for the day planner to read the time and slot the items accordingly in my timeline?

**Comment by TheraFu** [comment]
I'd love to have this too!

**Comment by FelixLundt** [comment]
That would be awesome to have, I also usually order tasks like this. It would be great if the Day Planner did the sorting by time for me :)

**Comment by jarradh** [comment]
+1

**Comment by joshwayne** [comment]
A decent workaround is to use the [Sort and Permute lines](https://github.com/Vinzent03/obsidian-sort-and-permute-lines) plugin. Install the plugin, select your tasks, and run the command "Sort & Permute lines: Sort alphabetically"

**Comment by ivan-lednev** [comment]
Available in 0.23.2
