### ISSUE TITLE
Feature request: allow task durations to be specified instead of start times

### ISSUE THREAD

**Issue by balint-bg** [ivan-lednev/obsidian-day-planner#109]
I do love the plugin and use it a ton.
One thing that would make my life a bit easier is if I could specify durations for tasks, rather than concrete start times.
There are several reasons for this:
- unplanned tasks do come in and interrupt the pre-planned flow
- planned tasks sometimes take longer (or, less frequently, shorter) to complete
- occasionally planned tasks get moved to other days or cancelled altogether (e.g. meetings get moved to later in the same day, or even to other days, people cancel stuff etc).
- I sometimes forget to plan for a task, even though I know it's coming and needs to be done, but simply forget to add it to the daily planner
In all these cases, I have to re-adjust the start times for every task that follows the change. This is not only toilsome, manual task but also error prone.

So, perhaps we could have a setting for each note (or even sections within notes): is the note absolute time - based, or duration - based?
If it's absolute time based, then the current behavior remains, no change.
But if it's relative time (duration) - based, then:
- need to specify a start time (the current way for doing this is totally fine, e.g. `- [ ] 9:00 BEGIN` 
- every following entry would need to specify a duration, for example: `- [ ] 1:15 silly meeting` would mean that there's a silly meeting during the day that takes 1 hour 15 minutes.
- tasks would be rendered in the order they are specified in the note
- now, if said silly meeting gets bumped out by 3 hours, I simply move the line to a later part in the note, and all other tasks would re-adjust their start and end times.

Alternatively, in place of a setting, one could also specify the format of the time specification for each task.
E.g. for tasks with set start times the current syntax would prevail: `- [ ] 13:30 silly meeting` , but for relative (duration-based) entries, one would say `- [ ] d0:45`, the `d` prefix denoting that the following time spec is for duration. (45 minutes in this case).

I do realize that there's complexity in lining up a mix of absolute and relative times, and how to handle overlaps for example. I have some ideas for that too but I wanted to put this out there as-is for early feedback. Thanks!!!

**Comment by TheraFu** [comment]
I'd love to have this too!

**Comment by imeed166** [comment]
Me too, duration of tasks instead of start times is much easier, I would use it a lot.

**Comment by lilacblossom** [comment]
Agreed!

**Comment by cynoglav** [comment]
support!

**Comment by ivan-lednev** [comment]
Closing this as stale.

**Comment by talenelat-elin** [comment]
Hi, could this feature request be reopened please? I think this would be a great feature to have and probably not too tedious to implement either. What I envision is if a task's start time is given as "xx" for example, the start time will be set as the end time of the task before it, and the end time can be either a actual time <HH:mm>  or a duration, with the notation for duration being "+<number of minutes>"

For example:

```md
### Day Planner
- 06:00 - 07:00 First Task
- xxxx - +60 Second task
- xxxx - +80 Third task
```
So the timeline will display as 06:00 to 07:00, the first task, 07:00 to 08:00 the second task, and 08:00 to 09:20 the third task.

The advantage is if the first task takes longer than plan, we can just edit the end time for the 1st task and have the changes cascade down. I'm aware we can do this from the timeline with the "Resize Block and push neighboring blocks option" but this offers more control and additionally is far easier to edit on mobile.

**Comment by kazerniel** [comment]
I would find this very helpful too! Looking for a replacement to [SuperMemo's Plan](https://help.supermemo.org/wiki/Plan), which offers duration-based day planning (with dynamic proportional rescheduling if things don't go to plan). Would love if this was possible inside Obsidian.

**Comment by CyberScooby** [comment]
People are so busy now-a-days, with many shifting priorxtxes pulling them in different directions. We need a planner that can easily shift along with our lives.

Please add this feature. It is a lot of work to manually shift my schedude overy time something changes, which happens a lot. 

It would be awesome to be able to make one change and have the rest of the schedule automatically adjust.
