### ISSUE TITLE
notification doesn't appear when it's the last task

### ISSUE THREAD

**Issue by imeed166** [ivan-lednev/obsidian-day-planner#110]
I would like the notification to appear when the task is started, even if there is only one task (no task after this one), can you add this feature please ? thank you

**Comment by Vitor12xx** [comment]
> So that's why .. I work around it by setting a task like this to the end of the task list
> 
> ![image](https://user-images.githubusercontent.com/33634312/210870252-39bda0ea-32f6-4c98-8b9a-a1a7ba81a7e1.png)

Shit. Just found out that this is the intended way of using the END keyword. To mark the end of the tasks list and notifications..

**Comment by ivan-lednev** [comment]
Closing this as stale.
