### ISSUE TITLE
Daily mode

### ISSUE THREAD

**Issue by venatiodecorus** [ivan-lednev/obsidian-day-planner#114]
I would love to be able to just set a mode where the day planner pane is automatically linked to my daily note so I don't have to manually link it every day. I end up having to do it on desktop and mobile. I would just want it to only show content for today's daily note and not generate empty files in the Day Planner folder.

**Comment by fyrfli** [comment]
Came here to search for a solution to this myself.

**Comment by blackpeasy** [comment]
+1

**Comment by guocailee** [comment]
Solution: 
1. Linked to Daily Note.
2. Daily Note  file name use `\D\a\y P\l\ann\er-YYYYMMDD`  formatter and save to `Date Planner` folder.

**Comment by blackpeasy** [comment]
> Solution:
> 
> 1. Linked to Daily Note.
> 2. Daily Note  file name use `\D\a\y P\l\ann\er-YYYYMMDD`  formatter and save to `Date Planner` folder.

Thanks for the tip. However, I guess the request still persists. An essential part of Daily Notes is organizing them alphabetically by date. Having to name them like this messes up the system.

**Comment by jposey27** [comment]
Was this ever resolved? I bound the insert Day Planner command to a hotkey but it would be much more convenient if there was a way to add Day Planner to the Daily Note template so that it was inserted every day automatically, without having to follow a baroque naming scheme.
