### ISSUE TITLE
Feature request: I would like to add annual, quarterly, monthly, and weekly plans.

### ISSUE THREAD

**Issue by TheCodeverse** [ivan-lednev/obsidian-day-planner#115]
Hi James Lynch , Thank you for the plugin! I wish it had more and better features, such as the ability to use this plugin to create my annual plan, then break the annual plan into quarterly plans, then into monthly, weekly and daily plans.
Finally, it is also possible to check the execution results of the plan.
Also, I hope this plugin can use templates.

**Comment by ivan-lednev** [comment]
Closing this as stale.
