### ISSUE TITLE
Using command option

### ISSUE THREAD

**Issue by Mcezarf** [ivan-lednev/obsidian-day-planner#116]
I'm trying to use Command Mode and I can not. The daily notes option is on and creates a note daily. Daily notes use a template that is in the template folder and works well. But, I try to use this same model in the Plugin Day Planner and I can not. On a note created from the day, I try to use the "Show Today's Day Planner" command and give a "CANNOT READ PROPERTY 'REPLACE' UNDEFINED '. How to get out of this? I would like someone's help, please.

**Comment by tcqiuyu** [comment]
I have the same problem. Did you resolve it yet?

**Comment by Mcezarf** [comment]
Not yet.

Enviada do iPhone de Mario Cezar

**Comment by tcqiuyu** [comment]
Actually I build main.js from the source instead of the release and it seems ok now. You can try.

**Comment by Mcezarf** [comment]
Hi Qiu

Where you get the main.js? 

Best Regards

Mario

**Comment by tcqiuyu** [comment]
Sorry didn't look at github for a while. You just clone the repo and use npm to build it: `npm run build`

**Comment by ivan-lednev** [comment]
Command option has been removed in 0.7.0
