### ISSUE TITLE
Can Timeline Items Be Modified? 

### ISSUE THREAD

**Issue by jgarr16** [ivan-lednev/obsidian-day-planner#117]
I need to differentiate my Planner items from other Obsidian entries. In addition to the Obsidian Daily Planner, I use the Obsidian  TODO plugin which utilizes the same task identifier (e.g., -[ ]). Using both plugins results in a constantly full TODO Inbox. I'm looking for a way to eliminate separate entries for these two plugins, and I'm wondering if it's possible to change the tags that Obsidian Daily Planner uses to identify my timeline items?

Instead of using "-[ ]" to identify my timeline items, is it possible to make a change that will trigger on something different, like "--[ ]" and "--[x]"?

**Comment by ivan-lednev** [comment]
Closing this as stale.
