### ISSUE TITLE
Modified pop up

### ISSUE THREAD

**Issue by Lanalangz** [ivan-lednev/obsidian-day-planner#118]
Thanks for a great plug in. 
Every time I change my daily note, a pop-up comes up saying that the note has been modified externally and the changes are being merged. On mobile this makes editing my daily note rather bothersome. Is there a way to stop that.
I synchronize via Dropbox, is that why it does that?
Best regards

**Comment by NanoRocket** [comment]
I experience the same pop up using iCloud, which makes the plugin difficult to use! It is a great plugin though!

**Comment by Lanalangz** [comment]
A little tip. I found that if I don't link the note to today's planner the pop up doesn't appear. So if I have to make a lot of changes to the note I unlink it first and relink it afterwards

**Comment by gpatkinson** [comment]
Same problem. Would be great to find a better fix, if anyone has any ideas.

**Comment by balint-bg** [comment]
I'm not 100% sure but there's a chance this is coming from the new `Live Preview` function of the editor. You can verify this by disabling this feature. Go to settings -> options -> editor -> "Use legacy editor" -> enable -> restart Obsidian.

I will experiment with this later too (can't right now) but I think the new `Live Preview` when used in combination with some other plugins (e.g. our beloved Day Planner) might do this.

**Comment by JamesHWade** [comment]
I still get the alert if I turn off the Live Preview. Any other suggestions for a fix?

**Comment by danielRep** [comment]
I'm also experiencing the same issue.

**Comment by wenyaoliu** [comment]
The unlink method of @Lanalangz  works for me. But I prefer it not popping up even it's linked.

**Comment by BahneGork** [comment]
crazy question, where can i see the link to the daily note?  
its not only the popup that is bothersome, but the fact that it is effectively uses backspace in what im writing.

**Comment by MitchellAcoustics** [comment]
I had this same issue on all my systems (Windows, Linux, Android). From [this response ](https://github.com/lynchjames/obsidian-day-planner/issues/161#issuecomment-1184577811) it appears it is due to the Mermaid Gantt option. Disabling it removed the popup for me.

**Comment by ivan-lednev** [comment]
Closing this as stale.
