### ISSUE TITLE
Feature Request: Configure time format

### ISSUE THREAD

**Issue by djbowers** [ivan-lednev/obsidian-day-planner#121]
Currently the Day Planner plugin requires you to use the time format `HH:mm` which is utilizes a 24 hour clock. I prefer to plan my day using a 12 hour clock, and it would be nice to be able to configure Day Planner to allow for that customization. 

The Natural Language Dates plugin has this as a customization option for reference.

**Comment by lilacblossom** [comment]
Yes please! i also asked for this in the forums, and they linked me to this post. ^^

**Comment by DarthPleurotus** [comment]
Agreed. While I prefer 24 hour time, I would like to have the ability to us HHmm format instead of HH:mm. I'm sure other people have their own specific preferences as well

**Comment by alok8bb** [comment]
Adding AM/PM option would be better.

**Comment by acatalepsycurse** [comment]
12h format would be amazing :]

**Comment by bjagasia** [comment]
+1 This would be a great addition!

**Comment by sayedbakeer3** [comment]
did it happen?

**Comment by ivan-lednev** [comment]
Day Planner now understands any time format.

**Comment by drnola** [comment]
I don't know if this is the correct place to post this query but I don't know how to set Dayplanner to a 12h format. I tried through  the Natural Language Dates plugin but had no success.
