### ISSUE TITLE
Notifications not working!.

### ISSUE THREAD

**Issue by franquinteroegea** [ivan-lednev/obsidian-day-planner#123]
My obsidian just stop sending notifications to windows. It doesnt appear in the settings also.
![image](https://user-images.githubusercontent.com/43573817/134347736-263ee7bf-4fd8-4a91-90c3-a21dd8e0c2d4.png). I dont know what to do

**Comment by Vitor12xx** [comment]
See this #110

**Comment by ivan-lednev** [comment]
Closing this as stale.
