### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by sfield541** [ivan-lednev/obsidian-day-planner#125]
Timeline view does not work in mobile app. I'm unable to add day planner note to current daily note even after linking day planner in mobile app.

**Comment by pjkaufman** [comment]
@sfield541 , the issue is that the plugin looks to be using the electron API for notification and this is not available on mobile versions. The manifest should really be updated to say it is not a mobile plugin or use JS to create notifications if that is even possible.

**Comment by pjkaufman** [comment]
@sfield541 , I just figured out how to see the day planner info in the mobile app. You have to have the day planner enabled, then run the command `Day Planner: Show the Day Planner Timeline`. This will not display the day planner timeline on the same screen. You then need to click the three dots in the upper right hand corner. Once there, you should see a day planner option in the drop down which you can use for the timeline. I have not tested this thoroughly, so I may have a slightly modified version of the plugin locally.

**Comment by ivan-lednev** [comment]
Closing this as stale.
