### ISSUE TITLE
Dayplanner doesnt work if Planner notes are in a subdirectory

### ISSUE THREAD

**Issue by MichalWiczynskithetrainlinecom** [ivan-lednev/obsidian-day-planner#126]
Dayplanner works fine only if the Planner notes are in the root directory.
As soon as I change the planner notes location, the dayplanner no longer displays the Dayplanner Timeline

**Comment by asifm** [comment]
@cashew90 I see last commit was on June 19. Doesn't look dead to me.

**Comment by cashew90** [comment]
Last release is from Dec. 2020, though. Also no bugs are being fixed and no new functionality. Unfortunately, I have not the required knowledge to develop the plugin on my own...

**Comment by asifm** [comment]
You're right. Well, all we can do is wait graciously and take with gratitude anything that comes our way. Or, I guess, we can learn to write our own plugins :-) 

Seriously, though, I have a lot of respect for people who spend their valuable time to make stuff that benefits others. So, thank you @lynchjames !

**Comment by ivan-lednev** [comment]
Closing this as stale.
