### ISSUE TITLE
The "END" task is never checked at the end

### ISSUE THREAD

**Issue by ONLYA** [ivan-lednev/obsidian-day-planner#127]
Every day, when the time passes the END time, the status is shown as "ALL DONE!" but the check box is never checked. What I have to do is to wait for the next day and manually tick the check box of the "END" task.

Is it a common issue or only specific for me because of some configuration mistakes?

**Comment by symph0nic** [comment]
I have the same issue. Using Command Mode, in my daily note. Have to manually 'check' it the following day.

**Comment by ivan-lednev** [comment]
Closing this as stale.
