### ISSUE TITLE
Calendar Task Start and End Times

### ISSUE THREAD

**Issue by pjkaufman** [ivan-lednev/obsidian-day-planner#129]
I would like to know if there is enough desire for the addition of task start and end times. Right now you can specify when a task starts, but not when it ends. I personally would prefer to specify the start time and end time for each task. I know you can specify break for when you have a break, but then it fills out that time as if something is going on during that time period instead of leaving it blank.

I was thinking the format would be kind of like the following:
```
- [ ] 12:00 - 19:00 Meeting
```

This could be a different mode for the app or even an optional part of the syntax where if it is not specified the end is assumed to be the start of the next event.

I did see something similar in the issues list where someone else had requested adding duration to the tasks (https://github.com/lynchjames/obsidian-day-planner/issues/109), but that is not quite the same thing, so I decided to open another issue and see what happens.

I would also like to specify overlapping and all day tasks, but those are of lesser concern to me. 

I would even be glad to help out in the creation of this feature even though I would be new to typescript.

**Comment by 229c9cf0** [comment]
+1, but the format should probably accept all of `-`, `--`, and `–` (an en dash).

The hyphen-minus because it's simple / right on the keyboard, the en dash because that's the typographically correct standard for ranges, and the double hyphen-minus because pandoc (via TeX) turns that into an en dash and it's still easy to type.

**Comment by FelixLundt** [comment]
+1 from me as well!

**Comment by AKasera** [comment]
+1 for me as well. It would enable me to have overlapping events. Or would it? Regardless, it would still be a welcomed treat to have.

**Comment by pjkaufman** [comment]
I can see about adding something where those three types are accounted for. I am not sure if @lynchjames  is maintaining this project anymore, so the logic my just reside in my fork of the repo since I have no way to merge without a maintainer's help.

**Comment by pjkaufman** [comment]
I am not sure it would actually allow for overlapping events as the way the
methodology for this plugin works is that you only take on one task at a
time. However it would allow start and stop times.

I will see about adding -- and the em dash this weekend and make my PR no
longer be a draft. I am not sure if @lynchjames us working on this plugin
anymore, but I guess I won't know until I make the PR no longer a draft.

**Comment by ivan-lednev** [comment]
This feature is available in the new version.
