### ISSUE TITLE
Prevent day planner for create a new note every day, even if I don't create one

### ISSUE THREAD

**Issue by MavropaliasG** [ivan-lednev/obsidian-day-planner#131]
Hi, thank you for this fantastic plugin.

Day planner creates a new note every day on its own. This can quickly make things convoluted, and as a result I can't find past planner notes easily.

What I would suggest is only create a new note when I create it, similar to the Daily notes plugin.

**Comment by MavropaliasG** [comment]
I guess this happens in File mode only, and not command mode? However, would it be better if File mode created the day planner only when clicked on the sidebar?

**Comment by ivan-lednev** [comment]
This is available in the new version.

**Comment by d34th4ck3r** [comment]
@ivan-lednev I don't see this toggle in the settings. How can we achieve this?
