### ISSUE TITLE
Defining Day Planner extent with rule ("---") not working

### ISSUE THREAD

**Issue by DarthPleurotus** [ivan-lednev/obsidian-day-planner#139]
Hi! I am enamored with this plugin so far. Seems like a powerful tool. However, when I try to add a day planner section to a note (in Command Mode), the Day Planner is not limited to the section I defined using "## Day Planner" and "---". For example, say my note looks like this:

```
## Day Planner

- [ ] 14:30 do stuff

---

## Other Section

- [ ] 12:00 do other stuff
```

In this example, both uncompleted tasks will show up in my Day Planner timeline. Thoughts/suggestions?

**Comment by precurcor** [comment]
i have the same thing. it would be great if tasks early in the day could be typed after a task that is meant to happen later in the day

**Comment by ivan-lednev** [comment]
Closing this as stale.
