### ISSUE TITLE
Fedora 35 notifications not working

### ISSUE THREAD

**Issue by MinallW** [ivan-lednev/obsidian-day-planner#140]
I'm using the latest Gnome available for Fedora 35 and Xorg. Perhaps the notification system changed since I'm using pipewire?, how should I debug this?

**Comment by serpro69** [comment]
I also don't get notifications in Ubuntu 20.04 (gnome-shell version 3.36.9).
Doesn't seem like this plugin is maintained much though, so little luck of this being fixed anytime soon.

**Comment by ivan-lednev** [comment]
Closing this as stale.
