### ISSUE TITLE
Is this plugin still being maintained / developed?

### ISSUE THREAD

**Issue by GitMurf** [ivan-lednev/obsidian-day-planner#141]
Curious if @lynchjames is still planning on maintaining / developing this amazing plugin? I may create my own fork if not. Thanks!

**Comment by aisle9** [comment]
I don't think this is being maintained anymore. Any plans on forking it?

**Comment by maugsburger** [comment]
I started using the fork https://github.com/jdbeightol/obsidian-simple-day-planner and can recommend it.

**Comment by ivan-lednev** [comment]
Yes, this plugin is maintained again.
