### ISSUE TITLE
enable dayplanner for daily notes using fontmatter

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [ivan-lednev/obsidian-day-planner#142]
instead of having to maintainer  map, i'd like to denote a dayplanner date in a note using font-matter

**Comment by jebeaudoin** [comment]
This would be a great addition! You could -- for instance -- indicate it in the front matter of your daily note, and include a standard schedule in your daily note template.

**Comment by ivan-lednev** [comment]
Closing this as stale.
