### ISSUE TITLE
Day Planner Removing Characters while Typing

### ISSUE THREAD

**Issue by KyleKing** [ivan-lednev/obsidian-day-planner#143]
Related to #107, but I wanted a new ticket to bump this issue since it is a critical bug

With the new Obsidian Live Preview mode, I'm noticing this issue more frequently. Obsidian is merging changes from the Day Planner causing whitespace between words to be removed as I'm typing

I still have Day Planner active, but I can no longer link the note to prevent Day Planner from modifying it

**Comment by KyleKing** [comment]
The problem is here: https://github.com/lynchjames/obsidian-day-planner/blob/c8d4d33af294bde4586a943463e8042c0f6a3a2d/src/planner-md.ts#L92-L99

Could either be a timing issue with auto-save, an issue with Obsidian's merge logic, or that the trailing spaces are being clipped in the plugin. I'm not sure which, but I don't think the plugin should be modifying the file unless it needs to?

**Comment by fnuttens** [comment]
I have the same issue, thankfully the plugin is still usable with the legacy editor.

**Comment by RobColes** [comment]
Same issue here too, Windows, clean vault with only day planner loaded.

**Comment by himmAllRight** [comment]
Also experiencing this issue and it's causing a bunch of issues for me

**Comment by rxy0424** [comment]
I am experiencing the same issue, have to switch to legacy editor to avoid it. Is there any other solution?

**Comment by RobColes** [comment]
I am finding as a workaround that if I enter the details without a time, it leaves the text alone while I am typing, and then I go back and add the time to the beginning of the line when I'm done with the rest of it.

I have not done extensive testing on this but it is helping me while we wait for a proper fix.

**Comment by grouchal** [comment]
> I think this could be an issue with the regex stripping whitespace:
> 
@KyleKing can you not create a merge request for this?

This bug is so annoying....

**Comment by KyleKing** [comment]
I don't think opening a PR would be worthwhile without input from @lynchjames first on what types of changes they would be open to

**Comment by RobColes** [comment]
Typing the time, then a full stop/period, then back-arrowing and typing the text before the full stop is also working for me.

**Comment by RobColes** [comment]
If the code fix works, it is possible to implement it locally. I have done this with another plug-in. Obviously this will be wiped if the plug-in is updated, but hopefully this would fix the issue anyway. And in the meantime...

Did you have a fix @KyleKing or have you just isolated the area of the issue?

**Comment by KyleKing** [comment]
> Did you have a fix @KyleKing or have you just isolated the area of the issue?

I only tried to isolate the issue and hadn't tried patching it locally yet

**Comment by beansrowning** [comment]
I think this is demonstrably abandonware at this point and needs to be forked.

**Comment by RobColes** [comment]
I'm not using the plug in any more, so haven't looked further, sorry.

**Comment by beansrowning** [comment]
I don't write type/javascript, so I can't be of much help. If someone was keen to work on the project, I'd be happy to sponsor.

**Comment by ivan-lednev** [comment]
This should be fixed in the new version.
