### ISSUE TITLE
Indented tasks don't show up on Planner/status bar

### ISSUE THREAD

**Issue by Gewerd-Strauss** [ivan-lednev/obsidian-day-planner#145]
Hello,

suppose I have the following structure in my daily note:
```
- [ ] 09:20 BE25: Prepare [Presentation Poster](https://www.google.com)
	- [ ] prepare writeup on Summary 
	- [ ] 11:15 Meeting @ [Anja's place](https://www.google.com) ![[embedded image 1]]
- [ ] 13:15 Resume Work
```

This will result in the following day planner:

![image](https://user-images.githubusercontent.com/80548781/150316457-c36f601d-394d-4d5f-bffe-92d5b0b47d1d.png)

It seems like indents in front of set time tasks are forbidden and not parsed correctly. Howver, this limits the usefulness of the plugin, because it forces us to use a flat structure when setting times. This is often okay, but if you have subtasks that you want to visually distinguish on both the planner _and_ markdown-file, this currently isn't possible.

Is there any means of resolving this? 

Thank you,  
Sincerely,  
~Gw

**Comment by ivan-lednev** [comment]
This is available in 0.7.0.
