### ISSUE TITLE
Numbered lists are not working

### ISSUE THREAD

**Issue by balint-bg** [ivan-lednev/obsidian-day-planner#146]
The numbered lists functionality is expected to automatically increase the list numbers on each subsequent list item.
Further it's expected to use a different numbering scheme on indented, sub-items. Currently list items get all the same numbers, and indented items don't get a different scheme.

See attached screenshot from the "help" vault.

Using Obsidian on Ubuntu 18.04, V0.13.23

![image](https://user-images.githubusercontent.com/75276107/151828920-08ad482c-1eaa-4a5c-a4dc-ab70f48be6da.png)

**Comment by ivan-lednev** [comment]
Hello, @balint-bg, please update the plugin and re-check.
