### ISSUE TITLE
[Feature Request] - Reading out a Daily Plan out of ALL notes in a Vault

### ISSUE THREAD

**Issue by L00tz1ffer** [ivan-lednev/obsidian-day-planner#148]
### Scan ALL notes for todays Appointments
It would be a nice feature, if this plugin would query the actual Date in a specific predefined format like 
```YYYY-MM-DD``` or ```DD.MM.YYYY``` 

>Example Syntaxes (Maybe all should be implemented)
>``` - [ ] Appointment (@[[2022-08-01]] 8:00)```
>```- [ ] Appointment (@[2022-08-01] 8:00)```
>```- [ ] Appointment (@2022-08-01 8:00)```
> ```- [ ] Appointment (@[2022-08-01](2022-02-09) 23:07)```

>In case of having this structure
>```- [ ] Appointment (@[2022-08-01](2022-02-09) 23:07) (@@2022-02-09 23:08)```
>it would be useful to implement a detection for this scheme, because in this case as i understand how it works the second timestamp is the event, while the first one is a reminder

(**-> like the [Reminder](https://github.com/uphy/obsidian-reminder) Plugin** does) 

### Sidebar Graph for All Appointments
and show this nice sidebar graph for the actual Day by listing every appointment for it. 

### Disable useless file creation
If this feature would be established, it would be nice to have an option to disable 

thank you anyways for this so far great attempt <3

**Comment by ivan-lednev** [comment]
Closing this as a duplicate.
