### ISSUE TITLE
Issues with file mode using Obsidian Sync between mobile and desktop

### ISSUE THREAD

**Issue by Snaity** [ivan-lednev/obsidian-day-planner#149]
The Day Planner will automatically create the next day as expected when Obsidian is opened (ex. on desktop) and edits can be made. 

However, there are sometimes issues where the day planner will delete and recreate itself in a loop when the vault is opened at the same time on mobile (something to do with the Obsidian Sync, cause it registers that in the sync log). 

This is only fixed by closing both programs and reopening, in which the day planner starts with a fresh daily file (so any previous edits have been deleted).

This is using Windows 10/11 (I use two desktops), Samsung Galaxy version 9 and Obsidian 1.0.1.

**Comment by ivan-lednev** [comment]
Closing this as stale.
