### ISSUE TITLE
[Feature] Availability to specify the filename format of the autocreated Files

### ISSUE THREAD

**Issue by L00tz1ffer** [ivan-lednev/obsidian-day-planner#151]
## Availability to choose custom time Format
Since your plugin creates Daily notes automatically, could you make up an Option to choose the filename format
>In its actual version the format of the note ist 
>```DayPlanner-20220101```
nice to have would be instead in the optopns menu an option to setup a custom format
wrether fully customizable or the ability to choose different options from
>i would be very happy if there would be the format
>```2022-01-01```

## is the pfefix needed?
since the notes were always created in the folder "DayPlanners" there is no need for the prefix and there would be a compatibility with some other existing plugins like Obsidian Reminders, which creates appointments in that syntax 
>```(@[[2022-01-01]] 12:59)```
which obsidian interprets creating a link in the root dir of the vault with this name - instead if a dayplanner could interecept this for future events - this could be a nice feature

## My guess
Best would be a feature to choose the Format 
like an interpreter which accepts ```YYYY-MM-DD``` in the options menu.

## Another Idea
or even better if this plugin had a switch to turn on or of like 
```enable scanning vault to move events into specific daily notes``` 
which would then if turned on recrusively scan the vault and create from those events listed in it and create those dates as files and in them place those events in the required format
>from extracted note ```index.md```
>with text ```testappointment (@[[2022-01-01]] 12:59)``` 
>create note ```\DayPlanners\2022-01-01.md```
>with entry ```12:59 testappointment```

hope you get it

i have no clue on js, so im not a real help in this but this would be some features i woukd be really glad if you could implement <3

Much love and thanx!!

**Comment by cocoonkid** [comment]
I agree. I would like to be able to chose the name of files and folders.

In my case I don't plan ahead but would like to log what happened every night.

folder: logbook
filename: log20220101

That would be so cool.   Please :)

**Comment by bifidotftw** [comment]
I would also love to see that feature.

An easy work around is to manually create the folder and note and run the Day Planner in command mode.

**Comment by levifig** [comment]
One possible solution is to use your current "Daily Notes" setup, outline/plan those future days in their respective (upcoming) day's note, but only link them to Day Planner (in "Command Mode", using "Link today's Day Planner for today to the current note") when that "future" day arrive… 😅

I'm about to try this for my workflow. Will report back… ;)

**Comment by ivan-lednev** [comment]
The plugin is now integrated with Daily Notes
