### ISSUE TITLE
[Feature Request]: Process Transclusion

### ISSUE THREAD

**Issue by DashConroy** [ivan-lednev/obsidian-day-planner#154]
## Make `Day Planner` process transclusions such that

**Note:** `Morning Routine`:

> - [ ] 09:00 Drink water
> - [ ] 09:05 Meditate
> - [ ] 09:20 Exercise

**Note:** `Night Routine`:

> - [ ] 21:00 Get ready for bed
> - [ ] 21:20 Brush teeth
> - [ ] 21:25 Get in bed

**Note:** `Day Planner`:
> ## Day Planner
> - [ ] 09:00 START
>
> ![[Morning Routine]]
> ![[Night Routine]]
> - [ ] 21:30 END

## Would show up on the timeline correctly, as if it were

**Note:** `Day Planner`:
> ## Day Planner
> - [ ] 09:00 START
> - [ ] 09:00 Drink water
> - [ ] 09:05 Meditate
> - [ ] 09:20 Exercise
> - [ ] 21:00 Get ready for bed
> - [ ] 21:20 Brush teeth
> - [ ] 21:25 Get in bed
> - [ ] 21:30 END

**Comment by ivan-lednev** [comment]
The plugin relies on Obsidian's API for rendering markdown, so this issue should be raised on forum.obsidian.md.
