### ISSUE TITLE
[Feature Request] - Button to uncheck all tasks in Day Planner in a specific day

### ISSUE THREAD

**Issue by giorgio-villani** [ivan-lednev/obsidian-day-planner#156]
Excellent plugin! I use it every day.

Issue:
I copy day planner from previous day into the current day and thought it would be useful if there was a button to automatically uncheck all completed tasks on a specific day.

**Comment by edhilgendorf** [comment]
hi, not sure i understand the issue but you can use templates for this.

**Comment by ivan-lednev** [comment]
Closing this as stale.
