### ISSUE TITLE
BREAK sections should not be colored in the timeline

### ISSUE THREAD

**Issue by thorlucas** [ivan-lednev/obsidian-day-planner#160]
Breaks should not appear as ordinary tasks. This is related to #159.

From the README:

<img width="469" alt="Screen Shot 2022-04-20 at 8 10 18 AM" src="https://user-images.githubusercontent.com/25698466/164263156-7e6f1c99-e0b0-4c9d-8815-a53a55fc0504.png">

Compare this to Apple calendar:

<img width="1443" alt="Screen Shot 2022-04-20 at 8 12 35 AM" src="https://user-images.githubusercontent.com/25698466/164263677-c426b31b-afe2-4192-8a39-8ce086dedc20.png">

I may submit a PR for this and #159 soon.

**Comment by ivan-lednev** [comment]
Closing this as stale.
