### ISSUE TITLE
Bug - Mermaid gantt chart 

### ISSUE THREAD

**Issue by Djuris** [ivan-lednev/obsidian-day-planner#162]
I tried to create a more extensive template based on the template provided here.

But once I added a few additional checkboxes I get the following error:
![grafik](https://user-images.githubusercontent.com/105242549/167487596-42608fcb-ccb9-4a88-a791-f466fa864131.png)

System: Windows 10
Obsidian: Latest
Plugin 0.5.8
Error
```

```mermaid
gantt
    dateFormat  HH-mm
    axisFormat %H:%M
    %% Current Time: 21:54:38
    section Tasks
         :07-00, 180mm
    Reading     :12-00, 30mm
    Reading     :13-30, 60mm
    Review notes and update daily note [[20201103]]     :15-30, 30mm
         :16-00, 30mm
    Walk     :16-30, 0mm
    Reading     :16-30, 50mm
    Prep for tomorrow's meetings     :17-20, 340mm
    te     :23-00, 60mm
    END     :24-00, 0mm
    section Breaks
    BREAK     :10-00, 120mm
    BREAK     :12-30, 60mm
    BREAK     :14-30, 60mm
```
```

**Comment by gilmrjc** [comment]
All tasks need a descriptive text. Task at 7:00 and 16:30 have no name and that makes mermaid crash.

**Comment by ivan-lednev** [comment]
Mermaid is no longer supported.
