### ISSUE TITLE
Feature request to Adjust time Blocks 

### ISSUE THREAD

**Issue by Aneeqasif** [ivan-lednev/obsidian-day-planner#165]
the plugin works really great approach is simple and every thing is fine. But a major issue that me and my friends face while time boxing using this plugin is if lets say i have laid down all tasks from morning to eve consecutively and then if i need to adjust a task and give it more time lets say add another 20 minutes i have to adjust times of other 20 different tasks accordingly and this really makes working with this uncomfortable . it would be a great adjustment if we implement some idea to encounter this issue in our plugin. some thing like draging a task in day planner time line up and down to give it more time and all other adjust automatically etc 
some thing like in  [aika](https://www.aikahq.com/)

**Comment by ivan-lednev** [comment]
Hello, check out the latest release:
https://github.com/ivan-lednev/obsidian-day-planner/releases/tag/0.10.0
