### ISSUE TITLE
[Bug] New template cannot be inserted, even when original file is deleted

### ISSUE THREAD

**Issue by mike-feldmeier** [ivan-lednev/obsidian-day-planner#166]
This is on a fresh install of Day Planner.  While figuring out how to arrange a generic routine...

A note is created, and through command-mode, and Day Planner template is inserted.  No, this isn't the way I want this.  Delete the file.  Add a new note in the templates directory, use command-mode to insert a Day Planner template.

I get no template, just a popup claiming that a Day Planner template has already been inserted in <deleted filename>.

**Comment by jelphd** [comment]
Ditto! Day Planner does not use my template to create my Day Planner note. I used this plug-in a while ago, and everything worked fine.  I removed it from my Obsidian vault months ago. Today I re-installed it and ran into the same problem.

**Comment by ivan-lednev** [comment]
Closing this as stale.
