### ISSUE TITLE
Will we have week-planner or month-planner?

### ISSUE THREAD

**Issue by RiddMa** [ivan-lednev/obsidian-day-planner#169]
Will we have week-planner or month-planner? The mermaid Gantt idea is awesome for long-term task management!

**Comment by jankap** [comment]
I second that! Was searching for an alternative, but why not adding this to this plugin? I'd like to create a roadmap for my research.

**Comment by ivan-lednev** [comment]
A Google Calendar-like planner has been added to 0.7.0. Mermaid is no longer supported: this form of planning deserves its own plugin.
