### ISSUE TITLE
option to add daily note a preset templeate for file mode

### ISSUE THREAD

**Issue by Aneeqasif** [ivan-lednev/obsidian-day-planner#170]
it would be really nice if we have a option to have a option to set a template for daily note that our plugin creates on file mode

**Comment by JadoJodo** [comment]
In addition to the above, the ability to set the folder structure for the file would be great. I like to keep my day planner organized as a date (within subfolders of `~/Year/Month`) so the ability to specify where it's created would be great.

**Comment by ivan-lednev** [comment]
This is available in 0.7.0.
