### ISSUE TITLE
create a custom tag to prevent meermaid gant updates from bleeding into the output file

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [ivan-lednev/obsidian-day-planner#173]
every change of the day planer log triggers a change of the mermaid diagram content

in order to prevent that from affecting the file content, i propose having a own markdown block type that internally renders to the mermaid diagram, but leaves the content untouched

**Comment by lukemt** [comment]
Fantastic idea! I was also thingink it would be great if the gantt diagram would be in a seperate file, so it would be similar to the timeline. and i could open the daily file in edit mode while looking at the diagramm. maybe a transclusion like ![[file]] that includes contents from other files would also be an idea.

**Comment by ivan-lednev** [comment]
Closing this as stale.
