### ISSUE TITLE
No Planner Data

### ISSUE THREAD

**Issue by ssravjee** [ivan-lednev/obsidian-day-planner#174]
See sample markdown file below **Day Planner-20220801.md**

# Day Planner
- [ ] 09:30 Setup for work
- [ ] 09:45 Review notes from yesterday
- [ ] 10:30 Create new notes
- [ ] 11:30 BREAK
- [ ] 15:30 read

See the screen print, I was expecting the __Day Planner Time Line__
![image](https://user-images.githubusercontent.com/6989615/182651020-b5e2d346-362d-49ad-a031-edfa5eb0b3ab.png)

See Day Planner Notes (Under **Day Planner** folder)

![image](https://user-images.githubusercontent.com/6989615/182651451-c5afa377-6590-4ea2-a957-4519e86ede33.png)

See **Version** 
![image](https://user-images.githubusercontent.com/6989615/182651257-bec7a14e-3c79-4aac-becc-e79cb9c1f7a2.png)

**Comment by lukemt** [comment]
#76

**Comment by P4nzerkunst** [comment]
Hi. Same issue here. "no planner data" message and I still didn't find what's the issue.

**Comment by wlscarthage** [comment]
some issue

**Comment by aryn-iris** [comment]
same issue

**Comment by zhao414** [comment]
Did you try to unlink the day planer with the day planer note and link to it again.
Mine issue is solved after doing this.

**Comment by avigilante** [comment]
Yes, and it works most of the times (sometimes I just need to do it a
couple of times).
My expected behavior was for it  to  correctly identify today’s daily note
and link to that by default.

**Comment by ivan-lednev** [comment]
Closing this as stale.
