### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by ssravjee** [ivan-lednev/obsidian-day-planner#175]
How to disable notifications on the **Day planner**, as I'm using it on a smart phone and it keeps distracting from what I plan to do. E.g. when I'm taking notes and changing and the notifications keep popping up it's quite disturbing is there any way to block the more doable the notifications if not can it be added to the feature request 

thank you!

**Comment by ssravjee** [comment]
> How to disable notifications on the **Day planner**, as I'm using it on a smart phone and it keeps distracting from what I plan to do. E.g. when I'm taking notes and changing and the notifications keep popping up it's quite disturbing is there any way to block the more doable the notifications if not can it be added to the feature request 
> 
> thank you!

The way to stop notifications is to disable **mermaid gantt** in the plug-in options!


Once you are happy with your Notes in it, if you wish you can toggle it back. 

It's a pretty nice workaround till it makes it to the feature list one day. 
Happy days!

**Comment by cyberpz** [comment]
So the Gant chart cannot stay on the notes if you keep editing them. Must stay on a separate file.

Thank you all for replies.
Solved to me the notification annoyance.

**Comment by ivan-lednev** [comment]
Closing this as stale.
