### ISSUE TITLE
Can we have a menu to change the format so we can track bullet points instead of tasks for interstitial journaling?

### ISSUE THREAD

**Issue by ssethparriss** [ivan-lednev/obsidian-day-planner#177]
Currently it's like this:

- [ ] HH:mm Task text

I request we have a menu so we can change it to what we want so I can make it like this:

- **hh:mm a:** Task text

If I could combine this with the option to change the folder that day planner applies to I think my ADHD could go away

**Comment by HanaNoAme** [comment]
This is exactly what I've been looking for. It would be a perfect addition to this plugin

**Comment by ivan-lednev** [comment]
This is already available in 0.7.0.
