### ISSUE TITLE
BUG: Light mode does not invert text color to white when 

### ISSUE THREAD

**Issue by Gewerd-Strauss** [ivan-lednev/obsidian-day-planner#180]
Hello,

When using light mode, the text color of the task's text does not change to be readible, or rather it gets changed to a potentially unreadable color.
The images display the same task, only that the second time I am actively hovering over the task's "block" within the dayplanner-pane.

![grafik](https://user-images.githubusercontent.com/80548781/193411962-8fb8a435-a847-41e7-a7af-1e9c7b8d1b19.png)
![grafik](https://user-images.githubusercontent.com/80548781/193411965-5c3770b5-8962-4317-bae4-b1afafdd5373.png)

I hope this can be resolved.

Sincerely,
~Gw

**Comment by ivan-lednev** [comment]
Please update the plugin and re-check.
