### ISSUE TITLE
BUG: Constant reload to the bottom of the page when using v0.5.8 with the new release of Obsidian 

### ISSUE THREAD

**Issue by TheRobBrennan** [ivan-lednev/obsidian-day-planner#183]
Obsidian just updated to include support for tabs and tab groups. Immediately after upgrading to the latest Obsidian, the Day Planner plug-in continued to save and repeatedly refresh - forcing me to the bottom of the page instead of where I wanted to be (toward the top).

For now, I've disabled this plug-in. Is this a known issue? Or should I uninstall this all together?

To repro - Update to the latest Obsidian version - `Version 1.0.0 (Installer 0.14.15)` and move around in a Day Planner note using the plug-in version `v0.5.8`

**Comment by crystalwby** [comment]
I have the same problem.

**Comment by Steven-Shixq** [comment]
I have the same problem. Turning off the "complete past planner items" may help locate current tasks. Hope to fix this in future releases.

**Comment by LucienReyes** [comment]
Same problem

**Comment by ivan-lednev** [comment]
Closing this as stale.
