### ISSUE TITLE
When obsidian updates to 1.0.0 version, the display is abnormal.

### ISSUE THREAD

**Issue by the-mountain-rcj** [ivan-lednev/obsidian-day-planner#184]
![image](https://user-images.githubusercontent.com/56163642/196312038-741850ad-1485-4426-8e05-a35f93073ea3.png)

![image](https://user-images.githubusercontent.com/56163642/196311998-d1b6c988-00d2-4b98-a06c-9a31d70b977d.png)

**Comment by rwchan13** [comment]
I am seeing similar issues.

**Comment by gilmrjc** [comment]
The problem is here https://github.com/lynchjames/obsidian-day-planner/blob/main/src/mermaid.ts#L51

The `'mm'` should be `'m'`, just one `m`. Sadly this plugin has not been updated since Jun, 2021. I hope the maintainer sees this messages and releases a fix.

**Comment by ivan-lednev** [comment]
Mermaid support has been removed.
