### ISSUE TITLE
Checkbox UI issue

### ISSUE THREAD

**Issue by bmadone** [ivan-lednev/obsidian-day-planner#186]
Hi, I found that checkbox doesn't look good 

![CleanShot 2022-10-31 at 21 08 22@2x](https://user-images.githubusercontent.com/23120972/199090075-09cf534e-4775-4922-a3b2-85df84c275a5.png)

**Comment by ivan-lednev** [comment]
The checkbox has been removed in 0.7.0. Please update and re-check.
