### ISSUE TITLE
Align UI problem

### ISSUE THREAD

**Issue by bmadone** [ivan-lednev/obsidian-day-planner#187]
<img width="397" alt="CleanShot 2022-10-31 at 21 10 17@2x" src="https://user-images.githubusercontent.com/23120972/199090353-65612a2c-70c6-4cfa-8199-8e2ec8bf8934.png">

Bottom panel items doesn't on the same line, looks like a bug

**Comment by ivan-lednev** [comment]
Fixed in 0.7.0.
