### ISSUE TITLE
Enhancement: Order tasks by time

### ISSUE THREAD

**Issue by curtismitchell** [ivan-lednev/obsidian-day-planner#189]
It would be great if the timeline displayed the tasks in chronological order. Currently, they are displayed in the order they appear in the list. For example:

```
08:30 Do this item second
08:00 Do this item first
```

The two tasks, above, will appear on the timeline in the order they are written instead of in order by time.

**Comment by ivan-lednev** [comment]
Closing this as a duplicate.
