### ISSUE TITLE
Template to current note / other issues found

### ISSUE THREAD

**Issue by SBmarOG** [ivan-lednev/obsidian-day-planner#190]
It seems not possible to add the template to the current note.

**This option (see screenshot):**
https://i.imgur.com/HhSvFKD.png
seems not working.

I also tried to change your `main.js` file like this:

```Javascript
const DAY_PLANNER_DEFAULT_CONTENT = `# Day Planner

This are to ToDo's of the current day.

### Morning plans

- [ ] 
- [ ] 12:00 BREAK

### Doings for today

- [ ] 13:00 Next

### Afternoon Review

- [ ] 16:00 Next
- [ ] 18:00 END
`;
```

**The markdown rules are:**

1. Start a document with a H1 element
2. A blank new line between each element
3. End the document with a "new line"

Thise rule should be followed though.
Normally a H1 should be followed by H3 see this article here:
https://ux.stackexchange.com/a/49115
but if there will be no H2 at all in this file it's "okay" to use H3.

---

### Checkbox graphic issues

There is a visual issue with the check box symbols:
https://i.imgur.com/KpQV6Zz.png

On the left side you see the **black symbol** boxes in the **Editor Life-Preview** side.\
And you see them too on the **Reading-View** on the right side, above the **white symbols**.\
Another **black symbol** you can find on the "**On / Off**" switch button, on the left side.

---

### Feature requests

**Here are some cool features who are needed:**

1. Add a function to create a new daily planner note for the next day.\
  And if already created for the next day, for the day after that day and so on.\
  So that you can add multiple days in a row to "plan your week".

2. Add a folder path option so that you can change the path directly on the settings instead of editing the `data.json` file which some users can't do (knowledge).

3. Add a custom path to a template file which will be used. Other plugins do that method too.\
  So if you do not enter a template path, it will take your template from main.js file, but if there is a file set it will use this template instead.

4. Add a custom file name field into the options. For example I would use it like this: `17.11.2022 (Do.) - KW 44 (Q4)` while (Do.) means "Donnerstag" which is german for "Thursday". The format is like this:\
  `DD.MM.YYYY (dd.) - \K\W w (\QQ)`\
  You can have a look at the "daily notes" Obsidian standard plugin.

5. You can't disable the "status bar" indicator **at all** which shouldn't be. It's nice to have a graphical circle / bar down there but sometimes you don't want it **at all**, this should be possible to disable.

6. There's a plugin called:\
  `obsidian://show-plugin?id=obsidian-checklist-plugin`\
  wich basically shows a list of all "ToDo's" on the right panel side.\
  It would be nice if your plugin could show a list like this of the todays "Day Planner" note.\
  &nbsp;
  **See screenshot:**\
  https://i.imgur.com/cYaJQLO.png

7. If you click on the graph, the MD-file should be opened.\
  It would be nice if it jumps directly to the checkbox of the task in the graph.

If I found more things while testing your plugin, I'll continue giving you feedback.
Thanks for your work!

**Comment by jasecoop** [comment]
Bump. Also experiencing this problem.

**Comment by jasecoop** [comment]
I am new to this plugin, but it would seem the command: _Add a Day Planner template for today to the current note_ will only work when you're in Command Mode.

I was in File mode before. See the plugin settings to change.

**Comment by cdmcdermott** [comment]
Does this plugin work with Obsidian 1.0.3 - have installed and set it to command Mode.
I have followed instructions to link to current note and add Day Planner Template into the note, added tasks, but I just get the message 'No Planner Data'.
Tried to use it with the auto generated daily notes in 'Day Planners' folder but again I get the same 'No Planner Data' message

**Comment by kaosine** [comment]
Yeah, same issue can't add to current note and can't show the timeline. It looks like from what I've seen it doesn't support the current versions of Obsidian. I wonder if @lynchjames is still around to work on this, or if someone else would take up the reigns? Since he's not touched this in almost a year and a half, from the looks of it?

Really stinks too because this seems like the perfect plugin to add next to the newly launched canvas feature....I'm just no help, since I don't understand JS enough to do anything...

**Comment by kaosine** [comment]
Ok so as an update to this since I think I figured it out: It works, it's just the command palette doesn't for whatever reason. I almost wonder if any of the other forks fix it since I assume it's just an incompatibility error w/1.x of Obsidian(since that's a thing apparently, and I guess is probably an electron/node breaking change?). Not sure how easy of a fix that is but yea....

**Comment by ivan-lednev** [comment]
Please update the plugin and re-check
