### ISSUE TITLE
Strange Behavior 

### ISSUE THREAD

**Issue by m0ll3art** [ivan-lednev/obsidian-day-planner#191]
strange behavior when trying to plan my day. When creating a checklist with times that will be automatically tracked during the day then strange behavior is observed when typing. On the contrary, if the checklist's entry does not contain a time then normal behavior when typing is observed. 

To get a feeling of what is happening please see the provided short video 

https://user-images.githubusercontent.com/11415120/202467302-baee5257-3ff7-469a-94a5-55fe0311f4e9.mp4

Is this an already known "behavior"? Prior to Obsidian v1.0, this behavior was not observed. 
Thanks for your work

**Comment by LuX1nAt0r** [comment]
I'm having the exact same issue, did you find a solution for it?

**Comment by m0ll3art** [comment]
no still having the issue with latest Obsidian version, so related to this plugin I assume

**Comment by kenjords** [comment]
Having the same issue, mine even removed all of my headings and compacted my tasks.

**Comment by kdsub1** [comment]
Same issue. Be great to get a fix

**Comment by clayton14** [comment]
I am having the same issue. 
For some reason when I check the check boxes (with time stamps) It causes the page to jump around. 
The best way I can describe the behavior is like when you click on a anchor link, but it is being clicked several times.

**Comment by ivan-lednev** [comment]
Please update the plugin and re-check.
