### ISSUE TITLE
An issue about the format of the automatically generated Mermaid Gantt

### ISSUE THREAD

**Issue by PianCat** [ivan-lednev/obsidian-day-planner#192]
The Mermaid Gantt chart generation does not work as expected, and in the case of the sample code of readme.md, it should have looked like the one shown below.

![Snipaste_2022-12-03_12-52-27](https://user-images.githubusercontent.com/50688679/205424264-33a71146-d3a7-43a1-8cd0-f5be358b1a9b.png)

But in fact, the style shown in the automatically generated Mermaid Gantt chart code block is shown in the figure below.

![Snipaste_2022-12-03_12-51-24](https://user-images.githubusercontent.com/50688679/205424223-33e30b9f-03e9-4c7f-8612-28676fd1377e.png)

The difference between the two code blocks is shown in the figure below. The Gantt chart does not display properly as expected when the minutes are marked in "mm", but it does display as expected when the minutes are marked manually in "m".

![Snipaste_2022-12-03_12-53-00](https://user-images.githubusercontent.com/50688679/205424284-81650876-abb2-4c86-958a-b038e141bdd7.png)

**Comment by wuqui** [comment]
I have the same problem. Thanks for providing this little fix. I hope this can be fixed in the plugin soon!

**Comment by Norisama** [comment]
I have also experience this issue, would you please specify which main.js are you editing?

**Comment by Norisama** [comment]
> 

It works!!!

**Comment by Conmy** [comment]
I'm willing to provide this fix as a Pull Request if it's wanted (with all credit to @PianCat )

**Comment by ivan-lednev** [comment]
Mermaid is no longer supported.
