### ISSUE TITLE
Scrolling to the bottom of the day planner

### ISSUE THREAD

**Issue by Osirus2019** [ivan-lednev/obsidian-day-planner#194]
Hello, I have calender, day planner, periodic notes plugins, my issue with day planner is 

1. when view at the middle of the note, it will scroll by itself to the bottom always, re-enable or reinstall doesnt work.
2. The mermaid ghant chart for the task it doesnt have bar only words which hard to see when it start and end. I have added the sample css from this git for the mermaid chatt to it still same. Pls help.

**Comment by strahmhoffman** [comment]
I'm having the same issue. The scrollbar start scrolling itself down to the bottom when I reach the Day Planner section of a note.

**Comment by strahmhoffman** [comment]
Removing the mermaid ghant chart seems to solve the problem. But I still haven't figure out the root cause of the issue.

**Comment by adeldaoud** [comment]
I have the same issue. Very annoying

**Comment by Github-six** [comment]
我看到它向下滚动页面时时间间隔是相同的，所以我去这个插件的main.js中搜索setTimeout，只搜索到一个，所以我注释掉了它所在方法的引用，虽然我不知道那个方法有什么用，但当前确实解决了这个问题。
scrollToPosition(position - 150);搜索这行代码，应该在7068行，前面加//即可。
如果没生效，可能是ob缓存，需要先将文件移出文件夹，重启ob和这个插件，它会显示不能加载插件，这时候将main.js移动进去，就可以了

**Comment by Github-six** [comment]
我看到它向下滚动页面时时间间隔是相同的，所以我去这个插件的main.js中搜索setTimeout，只搜索到一个，所以我注释掉了它所在方法的引用，虽然我不知道那个方法有什么用，但当前确实解决了这个问题。
scrollToPosition(position - 150);搜索这行代码，应该在7068行，前面加//即可。
如果没生效，可能是ob缓存，需要先将文件移出文件夹，重启ob和这个插件，它会显示不能加载插件，这时候将main.js移动进去，就可以了

**Comment by Github-six** [comment]
> Hello, I have calender, day planner, periodic notes plugins, my issue with day planner is
> 
> 1. when view at the middle of the note, it will scroll by itself to the bottom always, re-enable or reinstall doesnt work.
> 2. The mermaid ghant chart for the task it doesnt have bar only words which hard to see when it start and end. I have added the sample css from this git for the mermaid chatt to it still same. Pls help.

You can try me idea.       Chinese English...HaHaHaHaHaHa

**Comment by Github-six** [comment]
![fixBug](https://user-images.githubusercontent.com/58926187/224504118-87ff66e0-728e-497f-9fb2-0f21dd8db46f.png)

删除这三行应该就可以了，就是不知道有没有其他bug

> Hello, I have calender, day planner, periodic notes plugins, my issue with day planner is
> 
> 1. when view at the middle of the note, it will scroll by itself to the bottom always, re-enable or reinstall doesnt work.
> 2. The mermaid ghant chart for the task it doesnt have bar only words which hard to see when it start and end. I have added the sample css from this git for the mermaid chatt to it still same. Pls help.

![fixBug](https://user-images.githubusercontent.com/58926187/224504118-87ff66e0-728e-497f-9fb2-0f21dd8db46f.png)

删除这三行应该就可以了，就是不知道有没有其他bug

**Comment by Github-six** [comment]
> Hello, I have calender, day planner, periodic notes plugins, my issue with day planner is
> 
> 1. when view at the middle of the note, it will scroll by itself to the bottom always, re-enable or reinstall doesnt work.
> 2. The mermaid ghant chart for the task it doesnt have bar only words which hard to see when it start and end. I have added the sample css from this git for the mermaid chatt to it still same. Pls help.

![fixBug](https://user-images.githubusercontent.com/58926187/224504118-87ff66e0-728e-497f-9fb2-0f21dd8db46f.png)

删除这三行应该就可以了，就是不知道有没有其他bug

**Comment by ivan-lednev** [comment]
Please update and re-check
