### ISSUE TITLE
FR: Auto-link today's note on first startup of the day

### ISSUE THREAD

**Issue by Gewerd-Strauss** [ivan-lednev/obsidian-day-planner#195]
Hello,

Would it be possible to auto-link today's note if it exists? The path still gets defined by the native "Daily Notes"-plugin as seen in the image below. From there, the dayplanner could check if today's note already exists, and then auto-select it as the note to render if it does.
If the note does not exist, the plugin should do nothing and issue a notice that no daily note could be found in the daily-notes directory. 

Is this possible?

**Comment by ivan-lednev** [comment]
The plugin is integrated with the daily notes plugin now. If there is other functionality you'd like to see implemented, please create another issue.
