### ISSUE TITLE
Failed to load plugin  obsidian-day-planner

### ISSUE THREAD

**Issue by one0oneChen** [ivan-lednev/obsidian-day-planner#196]
as the title, I can't load it in Obsidian V1.1.9, my installer version is V1.19 also.

**Comment by davislf2** [comment]
I got the same problem on Obsidian V1.1.9 (installer 1.1.9), and my OS is macOS Monterey v12.3.

**Comment by teaqu** [comment]
Working OK for me on 1.1.9. Perhaps it's conflicting with another plug-in?

**Comment by ivan-lednev** [comment]
Please update the plugin and re-check.
