### ISSUE TITLE
Allow adding sub bullet points to each time item and display on planner

### ISSUE THREAD

**Issue by Gewerd-Strauss** [ivan-lednev/obsidian-day-planner#199]
Hello,

would it be possible to accomodate something along the lines of this:

    - [ ] 12:00 BE29 Assignment
    	- [ ] Finish Introduction
    	- [ ] Prep M&M
    	- [ ] finish LR
    - [ ] 13:00 Break
    	- [ ] eat something
    - [ ] 14:15 Break End
    - [ ] 14:20 BE29 Assignment
    	- [ ] finish LR, fix gaps
    	- [ ] start manuscript prep
    - [ ] 18:40 stop working
    	- [ ] make food
    - [ ] 20:10 Meeting Person X.
    	- [ ] Topic 1
    	- [ ] Topic 2
    	- [ ] Topic 3
    - [ ] 22:00 go sleep
    
to be used, where subitems indented further than a timeslot (so 1st level indentation and beyond) are considered "details" for the previous task, and then are printed in the Dayplanner Graphic? 

Currently, you would have to but it all on a single line. That is not only overwhelmingly difficult to work with because it makes modification _much_ harder, but additionally there is no method of forcing a linebreak in what the planner displays. So you either make a rather ugly overview on the  planner which is unwieldy to work with itself (and doesn't really actually allow breaking apart tasks to begin with), or you give up and resort to a short task description and everytime go back to your dailynote to see the non-rendered subtasks. 

And neither is really a good solution imo. 

Would this in principle be implementable? 

Thank you.  
Sincerely,  
~Gw

**Comment by ivan-lednev** [comment]
Hello, @Gewerd-Strauss, please update to 0.8.0 and re-check.

**Comment by Gewerd-Strauss** [comment]
Oh this is great; especially with the week-view. Thank you.

I noticed two things, one of them I am not sure whether or not it is a bug or not: 
![grafik](https://github.com/ivan-lednev/obsidian-day-planner/assets/80548781/35b9325b-9707-480c-b321-44f6a44aecf0)

Is it possible to tick task markers while on the week-view/timeline-view and check them off? 

---

The other; would it be possible to disable the timeline-view auto-opening a note when switching to a different date? Or better, would it be possible to prevent the opening of daily notes _other than today's_ from triggering the timeline to change to that date?
