### ISSUE TITLE
Task manager

### ISSUE THREAD

**Issue by dxcore35** [ivan-lednev/obsidian-day-planner#2]
If you can replicate this task list management > transferring unfinished task to selected day and hour: 
https://youtu.be/fm15cmYU0IM?t=123

This will be increase usefulness of your plugin... I think that there is no a single person who can finished all task how he planed it....

**Comment by lynchjames** [comment]
A few questions:

How would you see this working? Using a command/keyboard shortcut to insert a new task in the list or remove it? 

Would the user enter the time and text in a modal or would it be populated some other way?

**Comment by dxcore35** [comment]
If you consider this please replicate whole task management from this tool

https://youtu.be/F5NtTtFEArE?t=52
