### ISSUE TITLE
Trying to link Day planner with current note named Untitled or fired from a Templater template gives error about path not being updated in loop and doesn't link to final file

### ISSUE THREAD

**Issue by frtru** [ivan-lednev/obsidian-day-planner#200]
X-post from issue I posted in Templater, because the issue doesn't seem related to their side and more on other plugins and the Obsidian API.

https://github.com/SilentVoid13/Templater/issues/1032

In short, firing the "Day Planner: Link today's Day Planner to the current note" command from a new file created from a Templater template doesn't link properly or links too early to the intermediate "Untitled" file being moved. Which gives endless errors like those in console. The same can be observed by doing this manually with a file named "Untitled" at root "/".

![image](https://user-images.githubusercontent.com/11325196/218322809-ca263bda-11d7-461c-b7c4-b17f971f4085.png)

**Comment by ivan-lednev** [comment]
From 0.7.0, the plugin works only with daily notes. If you'd like to enhance this in some way, please create a separate issue.
