### ISSUE TITLE
Mermaid chart does not like a task starting with the word “Call”

### ISSUE THREAD

**Issue by Morgwee** [ivan-lednev/obsidian-day-planner#201]
Platform : iPad Pro M2
OS: iOS 16.3
Obsidian Version: 1.4.1 (83)

Hi folks, have found that the Mermaid chart does not render correctly when a task begins with the word “Call”. I was wracking my brain on this and when I removed the word Call from the front and moved to another position in the task things worked ok.

Mermaid ERROR
<img width="1258" alt="Mermaid Error png" src="https://user-images.githubusercontent.com/48145541/218349807-299d46b6-dafa-4273-bb0f-f3fbb42dcceb.png">

Mermaid OK
<img width="1210" alt="Mermaid OK png" src="https://user-images.githubusercontent.com/48145541/218349921-4a77b6cf-9957-4919-aa8f-dfc00f3c0dd2.png">

**Comment by ivan-lednev** [comment]
Mermaid support has been removed.
