### ISSUE TITLE
[Feature Request] - Daily template files

### ISSUE THREAD

**Issue by benninkcorien** [ivan-lednev/obsidian-day-planner#204]
Great plugin, thank you!

I'd love to be able to have a Settings option for  all 7 days of the week, and choose which template I want to use for that day.

| Day Planner Settings | |
|---|---|
|Monday| select-template-file|
|Tuesday| select-template-file|
|Wednesday| select-template-file|
|Thursday| select-template-file|
|Friday| select-template-file|
|Saturday| select-template-file|
|Sunday| select-template-file|

**Comment by ivan-lednev** [comment]
Please check out other plugins dedicated specifically to templating. Here is a great one: https://github.com/SilentVoid13/Templater

I consider templating to be outside of the plugin scope.
