### ISSUE TITLE
[bug] Unexpected Comportament in Note

### ISSUE THREAD

**Issue by see7e** [ivan-lednev/obsidian-day-planner#209]
I'm using the same template of your `README` file, and when I link the currently note in the app, it takes control of the scroll movement, you can see that even when I openned the command menu it was still moving.

![Day Planner-20230606 - DRIVE - Obsidian v1](https://github.com/lynchjames/obsidian-day-planner/assets/15942792/e20118f8-28b8-41cb-a4fe-4d3845ac6a82)

When I disabled the Mermaid Gantt it worked "just fine".

**Comment by victor-heliomar** [comment]
Same happened to me. I had to disable Mermaid Gantt and also disable Auto check options, since is not a great experience to use it so

**Comment by see7e** [comment]
> Same happened to me. I had to disable Mermaid Gantt and also disable Auto check options, since is not a great experience to use it so

Yeah it revert to normality when I disabeled Mermaid Gantt here too

**Comment by ivan-lednev** [comment]
Should be fixed in 0.7.0.
