### ISSUE TITLE
UX Sizing

### ISSUE THREAD

**Issue by Owlf-Dev** [ivan-lednev/obsidian-day-planner#210]
It would be great if more screen real estate could be afforded to listing the tasks. Current issues are:

- font size is not adjustable within styles.css and the default is larger than the sidebar font size. It takes up too much space on the left sidebar. It would be great if this could be adjustable.
- the progress line that tracks down on the left has too much padding on the left side leaving the tasks to push too far over on the right. If the progress line was further left, you could conserve more space for listing the tasks.

**Comment by ivan-lednev** [comment]
Hello, @Owlf-Dev,

Please update the plugin and re-check.
