### ISSUE TITLE
Timeline not showing

### ISSUE THREAD

**Issue by hanhanfei** [ivan-lednev/obsidian-day-planner#212]
The timeline icon doesn't appear in the right sidebar, and the timeline not showing, can anyone help?

Version: 0.5.8

<img width="764" alt="2023-06-16 102227" src="https://github.com/lynchjames/obsidian-day-planner/assets/44226443/31f5656c-b952-409b-a54f-e59cd1db58f5">

**Comment by stanleykylee** [comment]
had the same question, it's a command to open it. https://github.com/lynchjames/obsidian-day-planner#timeline-view

**Comment by elFlashor** [comment]
Hello, I have the same issue, even after using the command to open it, just nothing happens.
My Obsidian version is 1.3.5

**Comment by ivan-lednev** [comment]
Please update the plugin and re-check. Note that now you have to specify day planner heading in the settings, and the plan is going to live in your daily note.
