### ISSUE TITLE
Status bar items missing

### ISSUE THREAD

**Issue by kmaustral** [ivan-lednev/obsidian-day-planner#219]
I've been able to get this resurrected Day Planner working now, thanks. It's a little extra work to add in the end time, but it seems worth it.

I have selected options for Circular Progress and Now and Next, but I only get Now in the status bar. It much harder to see what the current item is than it was in previous version of the app.  This seems so regardless of theme. 

Is there any workaround to restoring these options?

Thanks.

**Comment by kmaustral** [comment]
Also, I have the extension installed on two computers with exactly the same options. In one I get the title of the event and in the other I get "minutes left".

**Comment by flapjack89** [comment]
I have the extention installed and in my status bar all I see is 'all done' I don't have the next task or the status bar visible at all

**Comment by ivan-lednev** [comment]
Hello, @kmaustral, please update and re-check. Make sure the Dataview plugin is installed.

**Comment by kmaustral** [comment]
Thanks Ivan. It's great to see the upcoming event now.

This is how it should be?

[image: image.png]

**Comment by ivan-lednev** [comment]
More fixes to the status bar in 0.16.0. Please re-open the issue if this doesn't work as expected.

**Comment by kmaustral** [comment]
🙏 It works well now.
