### ISSUE TITLE
Add modal for quick task edits

### ISSUE THREAD

**Issue by endlessblink** [ivan-lednev/obsidian-day-planner#221]
These features would be invaluable for working with the daily planner plugin and the tasks plugin:
- Creating and editing tasks, using the time planner plugin and having them recognized by the tasks plugin and vice versa. 
- Being able to edit the Tasks modal directly inside of the daily planner.

Thank you!

**Comment by pcause** [comment]
What would be great is to pull in tasks from the tasks plugin that start the description with HH:MM-HH-MM.  If you sort these items alphabetically you get a day planner.  Doing this would allow tasks and day planner to work well together.  Then is you made the fetched tasks links to their original location, you've got great integrations.  Items could still be added under the day planner heading and you'd just sort them all together.

**Comment by ivan-lednev** [comment]
Collecting tasks across the vault is handled in 0.11.0. Narrowing this one down to the edit modal.

**Comment by ivan-lednev** [comment]
Hey there! Check out 0.18.0: now hovering over a task with Control pressed will trigger a preview pop-up. This works great with the awesome [Hover Editor plugin](https://github.com/nothingislost/obsidian-hover-editor). This plugin is far superior to any modal I would implement 😅

**Comment by ivan-lednev** [comment]
Closing this as stale.
