### ISSUE TITLE
Day Planner causing hitching while typing in note with planner

### ISSUE THREAD

**Issue by iamrecursion** [ivan-lednev/obsidian-day-planner#226]
When the plugin is enabled and I am actively typing, every so often (on the order of seconds) the typing hitches momentarily. This only happens, as best I can tell, in the note where the current planner exists.

Disabling the plugin causes this hitching to stop.

**Comment by FeralFlora** [comment]
Yeah, I also thought there were some performance hits since the Week planner update (0.7.0 in the fork), maybe due to this?
> "Timeline now tracks your active note"

**Comment by iamrecursion** [comment]
Possibly, but it seemed to me more like an intermittent polling to see whether the planner in the note had changed. Definitely an annoying thing; I can't use or benefit from the new features at the moment due to it!

**Comment by FeralFlora** [comment]
@ivan-lednev Maybe this is of interest? https://discord.com/channels/686053708261228577/1082420499163918408/1147334873271521300

@Fevol (developer of the Commentator plugin) says they can load the Obsidian database faster than Dataview using https://github.com/localForage/localForage-getItems

**Comment by lukemt** [comment]
I'm trying to reproduce this, but I can't. I do have a similar behaviour in my main vault (usually barely noticable though). But it does not correlate with day planner as it does not make a difference whether I have day planner enabled or not.

Do you have some ideas on how I can reproduce this?

**Comment by ivan-lednev** [comment]
Hey, @lukemt, 

My best guess: at this moment we re-parse notes for the whole week after Obsidian updates the cache for any note. This is a simple and straightforward approach, but it'll lead to slowdowns if you have a lot of tasks in your week. I'm going to fix this soon.

**Comment by lukemt** [comment]
Hi @ivan-lednev,

Thanks for the explanation! I know dataview and others calculate and save a hash for every file and check whether it changed (it was discussed in some github issue that I had read but can't find anymore). But this might not be necessary for this one here. Just for your information/inspiration if needed at all 😉

**Comment by iamrecursion** [comment]
You might want to do the re-parsing in a worker rather than in the UI loop!

**Comment by ivan-lednev** [comment]
> You might want to do the re-parsing in a worker rather than in the UI loop!

😄 I imagine, this would be an overkill. For now I'll just try to re-parse only what's changed, once I add some tests and tidy up.

**Comment by iamrecursion** [comment]
I hope that is enough! 

I know the notes I have my planners in can get quite large, so that was the reason behind my thought!

**Comment by lukemt** [comment]
Yeah I would hope that's enough. Usually it's not calculations like this (at least when they are halfway efficient) that slow down the ui, but rather rerenderings and layout shifts and that kind of stuff

**Comment by ivan-lednev** [comment]
> Yeah I would hope that's enough. Usually it's not calculations like this (at least when they are halfway efficient) that slow down the ui, but rather rerenderings and layout shifts and that kind of stuff

Who said they're efficient? 😄

**Comment by lukemt** [comment]
Fair point 😅

**Comment by iamrecursion** [comment]
@ivan-lednev Are you still planning on fixing this one?

**Comment by ivan-lednev** [comment]
Of course. Keep in mind: this is a one-man operation 😓

**Comment by iamrecursion** [comment]
The reason I ask is that I have a bit of time and might be able to look into it myself. I don't want to clash with you if you're already on it, though!

**Comment by ivan-lednev** [comment]
Sure, I can assign it to you, if you want. Do you need any ideas on where to start?

**Comment by iamrecursion** [comment]
I think your comment above is a decent starting point! Throw it my way and I hope to take a look this weekend.

**Comment by ivan-lednev** [comment]
I'm going to handle this myself in scope of the upcoming dataview integration.

**Comment by iamrecursion** [comment]
Okay, sounds like a plan!

**Comment by ivan-lednev** [comment]
Hello, @iamrecursion, please update and re-check. Make sure the Dataview plugin is installed. 

Two things to note:
- Dataview itself gets slow once you have a large enough vault. This is where the Dataview filter gets handy: you can narrow down  the search operation to certain tags or folders, the narrower the search, the faster it is.
- I added a debouncer that should prevent the plugin from talking to Dataview until you stop typing. So this alone removes this annoying lag when typing continuously.

Let me know if it helps!

**Comment by iamrecursion** [comment]
This has helped significantly! My vault is large, but even with the default filter Dataview is performing well and not causing any lag. This is fantastic, thank you!
