### ISSUE TITLE
Enhancing the Day Planner Plugin A Request for More Visual Appeal.

### ISSUE THREAD

**Issue by FEI352** [ivan-lednev/obsidian-day-planner#232]
I'm really glad that you took over the day planner plugin, and I'm so grateful to you even though I don't know what language to express it in. However, I haven't started using it yet because I feel that the new version of the plugin is too plain. I'm still using the old version. Do you have any plans to provide a timeline with gradient colors similar to the old version, or the ability to customize colors for different time periods?

Also, I'm not sure why, but my computer doesn't show notifications like the old version used to.

**Comment by ivan-lednev** [comment]
Hello, @FEI352, 

there is a pull-request in progress, adding gradients. You can observe the progress on the issue here: https://github.com/ivan-lednev/obsidian-day-planner/pull/227

Also, what exactly do you have in mind here?
> or the ability to customize colors for different time periods?

**Comment by JosephBrooksbank** [comment]
new PR for the gradient timeline: #237

**Comment by ivan-lednev** [comment]
Hello, @FEI352, please update the plugin and re-check.
