### ISSUE TITLE
Addding more views 

### ISSUE THREAD

**Issue by endlessblink** [ivan-lednev/obsidian-day-planner#233]
It would be great to have a day view, legend view and monthly view on top of the weekly view.

**Comment by ivan-lednev** [comment]
Hey, @endlessblink, what do you mean by "legend view"? Also, can you send me some screenshots from other tools of what a monthly view should look like?

**Comment by endlessblink** [comment]
Sorry, I meant list / agenda view. It looks like this - 

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/37155282/757bd59e-7d4a-4bf2-8e30-1e9df8043300)

Monthly view would look like this - 

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/37155282/bf02aeac-8a7e-4453-bfba-ba23da61d2bb)

**Comment by ivan-lednev** [comment]
This should be more focused. We already have one for monthly view: #336. I'm not sure there is any value in creating an agenda view, since users can already do this with some powerful Dataview/obsidian-tasks queries.

**Comment by Barmaid1076** [comment]
> Sorry, I meant list / agenda view. It looks like this -抱歉，我的意思是列表/议程视图。它看起来像这样——
> 
> ![image](https://private-user-images.githubusercontent.com/37155282/265678501-757bd59e-7d4a-4bf2-8e30-1e9df8043300.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzEzMzUsIm5iZiI6MTczNTUzMTAzNSwicGF0aCI6Ii8zNzE1NTI4Mi8yNjU2Nzg1MDEtNzU3YmQ1OWUtN2Q0YS00YmYyLThlMzAtMWU5ZGY4MDQzMzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDAzNTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMzI1YzdjZTgyNjJiZTdlM2MxYmM0ZDA5YzNmYjUwYTAzMWUwMWJhMzU2ODJhNzU5NjI2OWE4YzJlZTU5ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tpqNzYOyREAhPOR3XzudVbw1JA0_ChEvMlmgJxyvVKU)
> 
> Monthly view would look like this -每月视图看起来像这样 -
> 
> ![image](https://private-user-images.githubusercontent.com/37155282/265678613-bf02aeac-8a7e-4453-bfba-ba23da61d2bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzEzMzUsIm5iZiI6MTczNTUzMTAzNSwicGF0aCI6Ii8zNzE1NTI4Mi8yNjU2Nzg2MTMtYmYwMmFlYWMtOGE3ZS00NDUzLWJmYmEtYmEyM2RhNjFkMmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDAzNTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZjI1YmZmNzk0NDIyYjhhM2EyYzVhM2RhOTZkY2E2MDA2MjJkNjgxZTFkZmE4ODVmZGYzNDlmZmRjYTRkZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l0_PCkvY7xAe1EpRqaz5GaGjwW1PmUn2dHm9dm5vOXc)

hey what software is that
