### ISSUE TITLE
[feature request] option to hide child tasks from Day Planner views

### ISSUE THREAD

**Issue by magma-chili** [ivan-lednev/obsidian-day-planner#234]
Hi,

Thank you for the sweet [0.8.1 release](https://github.com/ivan-lednev/obsidian-day-planner/releases/tag/0.8.1). I love how the checkbox status is rendered in the view. Would it be possible to optionally hide the child tasks from the views with a toggle? I find it makes the interface a bit noisy.

**Comment by kwojcik-blockether** [comment]
Hey, I wanted to say this would be really great to have it!

**Comment by ivan-lednev** [comment]
Available since 0.17.0:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/cf5dd3c8-a8f3-4ebf-8ee2-9d260249992c)
