### ISSUE TITLE
Day Planner only check on daily notes.

### ISSUE THREAD

**Issue by makkuro-kuroe** [ivan-lednev/obsidian-day-planner#235]
Hi there! 

I have one vault to manage my personal and work/projects life. Currently I'm separating a daily note for both of them...

on versions before v0.70 I had a command to display the planner on a custom note. 
I would like to have this behaviour or some enhancement to select a custom note to check for the schedule. Or better, if I could add some metadata to different notes, so the planner automatically watch all those notes. That would be the best!!

Thanks!

I saw a linked issue 
- #200

**Comment by ivan-lednev** [comment]
Hi, @makkuro-kuroe, so you have some periodic notes that are not daily notes? Or is there a bunch of files that don't have their names changed?

**Comment by makkuro-kuroe** [comment]
I have periodic notes for my personal use, but also maintaining a different "daily" note for my work/project.

I cannot use only one daily note because privacy issues on the company I work, so i cannot sync that data... 

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/53063314/a6aabdf3-88ca-406c-a104-c122f2fddb5a)

**Comment by ghbolivar** [comment]
The attach planner to current note was extremely useful. 
I have several templates that have scripts like this:
`
<%*  app.commands.executeCommandById('obsidian-day-planner:app:link-day-planner-to-note') %>
`

**Comment by jvivian** [comment]
> The attach planner to current note was extremely useful. I have several templates that have scripts like this: `<%* app.commands.executeCommandById('obsidian-day-planner:app:link-day-planner-to-note') %>`

To clarify, Is there currently no way to create a template that automatically associates the "Day planner insert planner heading at cursor" with it?

**Comment by lukemt** [comment]
How about making it work (at least the day planner timeline) on any note that has a day planner section?
I mean by default without calling any command?

How would this work for you guys?

Why? Simplicity!

**Comment by JosephBrooksbank** [comment]
@lukemt which note would show up in the timeline view when you left that note? whichever note was last viewed that had a day planner header in it? there is also the ability to go 'forward' and 'back' through the daily notes using navigation arrows above the timeline. What would those do?

**Comment by lukemt** [comment]
@JosephBrooksbank Yes the last viewed note.

I think the navigation would need to be disabled.

Another question would be if the now-line should be visible when we don't know if it's today's note.

Finally, what about notifications?

Maybe a combination of what I suggested and a command would be ideal plus possibly a button in the timeline header to make the current note the day note

**Comment by ivan-lednev** [comment]
Hello, @makkuro-kuroe, please update and re-check. Make sure the Dataview plugin is installed. Now scheduled tasks are gathered all across the vault.
