### ISSUE TITLE
[feature request] Open sidebar

### ISSUE THREAD

**Issue by kmaustral** [ivan-lednev/obsidian-day-planner#236]
Currently, the command Show Day Planner Timeline populates the sidebar, but the sidebar remains closed. To get focus, you have to open the sidebar and click the appropriate tab. Most other sidebar commands automatically take focus. It would be good to remove these extra steps so that the command could become a reflex.

**Comment by ivan-lednev** [comment]
Hello, @kmaustral, please update the plugin and re-check.

**Comment by kmaustral** [comment]
Works great now. Sorry I overlooked leaving a message with the 3 coffees. I appreciate your work.

**Comment by JosephBrooksbank** [comment]
this issue should be closed
