### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [ivan-lednev/obsidian-day-planner#239]

**Comment by lukemt** [comment]
Hi @LuisB79 !

Why not directly put it into tomorrows note? Or write a section into today's note and copy it over to tomorrow’s note. Or you could embed tomorrow’s day planner section into today's note

**Comment by FeralFlora** [comment]
> could it be possble to make something on my daily note that said Tomorrow from 10:00 to 11:00 do something? Or something akin for weekly planning?, repetitive tasks

Yeah, either just edit tomorrow's daily note in advance like @lukemt said, or you can use the week planner feature (command palette -> Show the week planner). When you add a task to a future date, it will create that day's daily note / day planner an insert the task.

If you insist on putting tomorrow's tasks into today's note, you can use the Rollover daily todos to transfer these unchecked tasks to the next day when tomorrow's daily note is created.

**Comment by ivan-lednev** [comment]
As it's now possible to add tasks to any daily note, there is no need to do so from today's note, so closing this one as 'won't fix'.
