### ISSUE TITLE
[BUG] Changing zoom level is broken (time blocks don't scale until I switch note)

### ISSUE THREAD

**Issue by FeralFlora** [ivan-lednev/obsidian-day-planner#243]
Only the timeline gets rescaled when changing zoom level. The tasks stay at the same zoom level, until you switch to another note (from any note to another).

See this demo:
![Obsidian_JP4kc2MXZm](https://github.com/ivan-lednev/obsidian-day-planner/assets/33608083/c4b7586d-1381-479c-87d6-b5ed6ce7a04a)

When my cursor goes off screen, I am switching to a different tab. Doesn't matter which the original tab is.

**Comment by FeralFlora** [comment]
@ivan-lednev I think you meant to reply here. Well, broken in the sense that it doesn't work as intended anymore. As the demo shows, the tasks don't follow the scaling of the timeline, and the time goes out of sync when changing the zoom level.

**Comment by JosephBrooksbank** [comment]
It looks like this may have been caused by my colorful timeline changes, since it works in 0.81. I can look into this

**Comment by FeralFlora** [comment]
The fix worked!
