### ISSUE TITLE
Can't automatically create the day planner file for today.

### ISSUE THREAD

**Issue by neuromaancer** [ivan-lednev/obsidian-day-planner#245]
After the update to the latest version, my obsidian can't create the file automatically. And the status bar always shows: no plan for day, even I manually create the day plan file.

More info:

1. obsidian version: 1.4.8
2. OS: macOS
3. related plugins: calendar?

**Comment by JanPastorek** [comment]
the same here

**Comment by ivan-lednev** [comment]
Hello, @neuromaancer, please update and re-check.

**Comment by neuromaancer** [comment]
> Hello, @neuromaancer, please update and re-check.

Unfortunately, it is the same.

**Comment by JosephBrooksbank** [comment]
when you say "day plan file", do you mean your daily note, or the 'day planner' file that this plugin used to generate? With the release of 0.7.0 the behavior of this plugin changed. The timeline is now generated from a specific _header_ in your daily note, rather than a separate file

**Comment by neuromaancer** [comment]
> when you say "day plan file", do you mean your daily note, or the 'day planner' file that this plugin used to generate? With the release of 0.7.0 the behavior of this plugin changed. The timeline is now generated from a specific _header_ in your daily note, rather than a separate file

I mentioned the "day planner" file that used to be generated automatically. I got it! I just checked the new README.md. So basically now I need to add the `# Day planner` header to my template of daily note, if I understand well. Very interesting interaction between 2 plugins  🎉
