### ISSUE TITLE
Stop the plugin from opening new tabs when editing a time slot

### ISSUE THREAD

**Issue by endlessblink** [ivan-lednev/obsidian-day-planner#246]
Right now, if I want to edit a time slot by clicking on it and being transferred to the daily note, the plugins open a new note each time
instead of just using the current open tab. This causes a lot of open tabs being open instead of just one.

Here is an example for the issue - 
https://capture.dropbox.com/9NejiHOb5JJPyFvP

**Comment by LennartCode** [comment]
Big +1 from me :D

**Comment by ivan-lednev** [comment]
Hey there! Check out 0.18.0!

**Comment by LennartCode** [comment]
Thank you very much for the effort! Works flawlessly :)
