### ISSUE TITLE
Option to not create new Daily Note when scrolling past empty days

### ISSUE THREAD

**Issue by flomax** [ivan-lednev/obsidian-day-planner#247]
Great work on the plug-in Ivan.. I greatly appreciate your efforts and will be donating :)
At the moment when scrolling forward / backwards using the timeline view arrows, it will create a new Daily Note if one does not exist for that particular  date.

Is it possible to _not_ create this note when scrolling ? 

My workflow doesn't require I have a Daily Note for every single day, and I would like to avoid the clutter it causes. A toggle to not "create note on empty days" would be great. 

Hopefully I haven't missed this feature if it already exists. Cheers.

**Comment by flomax** [comment]
Same issue as [316](https://github.com/ivan-lednev/obsidian-day-planner/issues/316)

**Comment by ivan-lednev** [comment]
Closing as a duplicate of #316.
