### ISSUE TITLE
Customize Time format in Day planner

### ISSUE THREAD

**Issue by laraSalconiDenis** [ivan-lednev/obsidian-day-planner#248]
It would be nice to get the ability to change the way the task time are display.
For now I can see that it is: 
```
- HH:MM - HH:MM <Description>
```

I would like this plugin to support my current setup:
```
- #<ProjectTag>
  - HH:MM-HH:MM <Description>
  - HH'h'MM-HH'h'MM <Description>
  - H'h' <Description>
  - M'm' <Description>
  - H'h'M'm' <Description>
```

Not sure if it too custom and complicated to support this look (time frame & relative time).

**Comment by onesura** [comment]
I hope this would be possible too. This is only the thing that is holding me back from using it and the old one.

**Comment by ivan-lednev** [comment]
@alexandreSalconiDenis, hello. Can you provide real examples of these formats? I don't totally get what this syntax means.

By the way, task times can be written in multiple ways. The format you mentioned is just the one used by the plugin when you create or update tasks through drag-and-drop.

**Comment by laraSalconiDenis** [comment]
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/38858375/870c77af-b2da-409c-ab85-25789ac8ccd0)
here is an example of what could look my diary for me normaly   
The dashboard at the end help me understand what I did in the specific day and the time are place in a sub list under the specific title. (for me it's: `🕔 Time tracking `)

**Comment by laraSalconiDenis** [comment]
> @alexandreSalconiDenis, hello. Can you provide real examples of these formats? I don't totally get what this syntax means.
> 
> By the way, task times can be written in multiple ways. The format you mentioned is just the one used by the plugin when you create or update tasks through drag-and-drop.

I've saw on the source that some are already supported, I think probably the main thing could be to search time inside all the list (even the sub-list) under the specific title. But also for me I dont put space between time and dash.

**Comment by onesura** [comment]
I know that this is an off-topic, but it is possible to force timeline to display 12-hour format instead of 24-hour format?

**Comment by ivan-lednev** [comment]
Hello, @onesura, please create a separate ticket for that, and attach screenshots of where exactly you'd like to have configurable time format.

**Comment by ivan-lednev** [comment]
@alexandreSalconiDenis, the problem in your example is that you're mixing time (e.g. 10:30 am) and duration (e.g. 1h10m). I haven't thought about it yet, but implementing this and figuring out how to display it in the day planner might be really complicated.

What can be easily implemented is 2 things:
1) Parsing more time formats, like `15H00`
2) Configuring, what format the plugin uses when it updates your daily plan (through drag-and-drop)

**Comment by FeralFlora** [comment]
> I think probably the main thing could be to search time inside all the list (even the sub-list) under the specific title. But also for me I dont put space between time and dash.

This sounds like https://github.com/ivan-liadniou-epam/obsidian-day-planner-fork/issues/11 (in the fork, before it was merged into the main repo).
Edit: Well, not exactly the same, because that issue is about top level time blocks with sub-blocks, while your idea is about simple bullets (no time) with sub-lists that are time blocks.

**Comment by laraSalconiDenis** [comment]
I've split the issue into a new one for the list issue (https://github.com/ivan-lednev/obsidian-day-planner/issues/251)  
 @FeralFlora I will check that to be sure I've not duplicate an issue.   
@ivan-lednev I aggree with the proposition but would it be possible to use a format like: https://momentjs.com/ ?

**Comment by ivan-lednev** [comment]
@alexandreSalconiDenis, you've linked to a format library, not a specific format. Did you have some specific moment in mind or something else?

**Comment by laraSalconiDenis** [comment]
:thinking: I dont know much in javascript and obsidian in general. but instead of a drop down with hard suggestion, could we put a string where the we can specify the format like: `HH:mm-HH:mm` ?
I've linked momentjs because it's the tool I use to parse the list on my side, to sure If it could help to show how I did it?

**Comment by ivan-lednev** [comment]
@alexandreSalconiDenis, okay, I got what you meant.

**Comment by talenelat-elin** [comment]
> I've saw on the source that some are already supported, I think probably the main thing could be to search time inside all the list (even the sub-list) under the specific title. But also for me I dont put space between time and dash.

@alexandreSalconiDenis Could you point out where in the source is this, I'd like to modify it myself if possible

**Comment by ivan-lednev** [comment]
Hello, @alexandreSalconiDenis, please update and re-check. Make sure the Dataview plugin is installed. You can now specify time format that the plugin uses when editing tasks through drag-and-drop.

**Comment by laraSalconiDenis** [comment]
@ivan-lednev Dataview is installed because I need it for my own script(the dashboard at the bottom of the picture).

@ivan-lednev yes you can change the time format that will be use once you displace a task but the display seems to use a different rule

to test:
1. add a time like `14:30-15:30 another test`
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/38858375/4fd692d0-7512-495e-a2a0-71ceb5d8f32f)
2. go to the setting and enter a different format: for fun I've used _Default timestamp format_: `HHpmm`
3. displace the task in the diplay view
  - You will see the task inside the markdown change with the new format
  - You will see the task in the display shrinking and showing incorect text
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/38858375/ee6efaf1-9149-4638-aaf6-0edf1317ab99)

**Comment by laraSalconiDenis** [comment]
@ivan-lednev I'm unsure if I found the cause
- https://github.com/ivan-lednev/obsidian-day-planner/blob/main/src/regexp.ts#L12  
I dont know where is the value from the config but I suppose it need to be use there.

**Comment by ivan-lednev** [comment]
`p` is simply not a valid separator. And I'm not sure it should be.
