### ISSUE TITLE
[Feature Request] Configurable Time Format on the Day Planner Timeline 

### ISSUE THREAD

**Issue by onesura** [ivan-lednev/obsidian-day-planner#250]
Although the plugin understands any time format, it doesn't really display that format on the Day Planner Timeline, at least for me. For example, I have these tasks set in a 12-hour format instead of a 24-hour format:

# Day planner
- [ ] 1:00 PM - 2:00 PM Study
- [ ] 2:00 PM - 2:30 PM Break 

However, the timeline still displays these tasks using the 24-hour format instead of the 12-hour format that I had set. It would be amazing if Day Planner Plugin options would allow its users to toggle between displaying tasks between 12 and 24-hour formats. After all, there are various users from several countries that mainly utilize the 12-hour format. This, however, is but merely an inconvenience, so simply take this as a suggestion. Thank you so much!

Attached below is an example:

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/86343717/48004c4f-77ac-4ebf-98af-1c7814ef5b80)

**Comment by ivan-lednev** [comment]
Hello, @onesura, please update and re-check. Make sure the Dataview plugin is installed.
