### ISSUE TITLE
Parser doest find entry under sub-list

### ISSUE THREAD

**Issue by laraSalconiDenis** [ivan-lednev/obsidian-day-planner#251]
I'm unable to display manual entry with this layout:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/38858375/b7454923-0d26-46e7-a526-9817ccd3914c)

but If i do it like that it work:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/38858375/696d748e-5587-49a3-8276-d667ff92a4d4)

I think the parser shold try to look at all element in the list, event sub list and only procese when the time format match.

**Comment by FeralFlora** [comment]
@alexandreSalconiDenis You could probably make your workflow work without any change to this plugin, if you use headings for each project rather than tags. Then, you could use a query similar to this to distinguish the time spent on different projects: https://app.raindrop.io/my/0/dataview/item/583907688/web

That is, if the tags aren't important to you in some other way.

**Comment by laraSalconiDenis** [comment]
@FeralFlora It is because I can use them to track global information but I've tried with only 2level list and it doesnt work could you show me an example of your proposition please?

ps: I cant see your link since I need to create an acount

**Comment by lukemt** [comment]
@FeralFlora Just tried the link because I already have a raindrop account but it does not work here either.

@alexandreSalconiDenis  Can you explain a little more how your time tracking system works and which plugins/code you use?

**Comment by FeralFlora** [comment]
@alexandreSalconiDenis @lukemt Sorry for sharing the wrong link. Here's the non-raindrop link: https://s-blu.github.io/obsidian_dataview_example_vault/20%20Dataview%20Queries/Show%20all%20list%20items%20under%20a%20specific%20heading/

It's from the Dataview demo vault.

> could you show me an example of your proposition please?

Maybe if you share your current query, I could take a shot at adapting it. Otherwise, see the correct link above.

**Comment by lukemt** [comment]
@FeralFlora This is a pretty valuable resource! Thanks for sharing. I was looking for exactly this a few days ago and ended up with using dataviewjs which works but it still bothered me that I couldn't get it to work any other way

**Comment by FeralFlora** [comment]
> @FeralFlora This is a pretty valuable resource! Thanks for sharing.

You're welcome! It helped me a lot too.

**Comment by laraSalconiDenis** [comment]
> @FeralFlora Just tried the link because I already have a raindrop account but it does not work here either.
> 
> @alexandreSalconiDenis Can you explain a little more how your time tracking system works and which plugins/code you use?

@lukemt I use [DataView](https://github.com/blacksmithgu/obsidian-dataview) and heres my template with the main script I made at the end: https://gist.github.com/alexandreSalconiDenis/73a97e392e703a6de988e95206cfea90

# Context
I work on different client during the day an I need to track the total time I end up doing for each one.  

# Solution
To Help with that I decided to use dataview with a 2 level list to separate the time.  
On the first level I enter a tag to identify the client and if needed a specific work i.e: `#ClientA/UpdateObsidianPlugin`.  
On the second level I enter a time window (`8h00-9h00`) , or an amount of time (`1h40m`), follow by a short context of what I did. I've also made some modification to support different layout since I never write time the same way :facepalm: .

# Mechanic
At the bottom I use dataview to cycle inside the current diary page and extract each time for each entry(1st level) and sum the time (2th level). The result is then display for each client.

I was targeting to make a script to help other dev inside the company and probably use it at large scale to make a dashboard from time enter in dairy.

**Comment by laraSalconiDenis** [comment]
ps: I don’t expect to fit the current plugin 100% but I think the plugin should at least find the time I enter manually and display on the calendar.  
The creation from the calendar and moving task is probably harder to handle.

**Comment by yoghurtdewdew** [comment]
I have the same problem!
I also love using a lot of tags in parents nodes.
I wanna children nodes to be rendered as time block, too. Hope there will be more options in calendar view!

<img width="1448" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/63794438/a64e2e56-5712-4730-a362-f0dae19f95fe">
<img width="1362" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/63794438/4feb4c02-f21e-4d86-aef0-c7ff8dfc84ff">

**Comment by laraSalconiDenis** [comment]
I've found a work around not sur if the parsing logic is the best for the moment but here is the workaround for now: https://github.com/cimeq/obsidian-day-planner/tree/cimeq/dev 

with that I can see all sub list inside the weekplan but dont edit them because it's undefined beaviour.

A rework of the parsing mechanic might be needed to fully support my request I think.

**Comment by ivan-lednev** [comment]
Hello, @alexandreSalconiDenis, please update and re-check. Make sure the Dataview plugin is installed.

**Comment by laraSalconiDenis** [comment]
hi @ivan-lednev , I've just tested the new version 0.11.2 and it's fully compatible with my needs:

The only thing I had to change is my time format `10h30` to `10:30` not a big deal to use this awsome plugin :cowboy_hat_face: :+1: 

Also the:  amount of time (1h40m) is not supported but doesnt cause issue so I think it need to be an issue on it's own.
I'm closing this one thanks again.
