### ISSUE TITLE
Date Format in Timeline Header not changing

### ISSUE THREAD

**Issue by ElphaTech** [ivan-lednev/obsidian-day-planner#252]
When I change the `Date Format in Timeline Header` setting, nothing happens.
I changed it to `dddd, D [of] MMMM YYYY` it just keeps the normal one, even after restarting.
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/68719406/42c6ffa0-a92c-4239-8ebf-781c233e0571)
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/68719406/48cb11ee-e40f-4ba4-a15e-b197e78623bf)

**Comment by ivan-lednev** [comment]
Hello, @ElphaTech, please update and re-check. Make sure the Dataview plugin is installed.

**Comment by ElphaTech** [comment]
Yep, just updated it and it is fixed now. Thank you!
