### ISSUE TITLE
Look for a specific file instead of a heading?

### ISSUE THREAD

**Issue by j1dywfrxvq** [ivan-lednev/obsidian-day-planner#253]
I've got a folder under Journal named Schedule, within which I store schedules for each day. e.g `S9923`.
I'd like for the day-planner to detect the file, but there's no such option.
I have templater installed, so there's no need to worry about the numbers after S in the file.

**Comment by lukemt** [comment]
Do I understand you correctly that you do not want to put a `# Day planner` heading into the file or is it about the file detection?

**Comment by j1dywfrxvq** [comment]
> Do I understand you correctly that you do not want to put a `# Day planner` heading into the file or is it about the file detection?

Yes, I don't need a heading and I also would like for the daily planner to be in separate file.

**Comment by lukemt** [comment]
I see, thanks. Would you mind needing to have a heading though? I like your username btw.

**Comment by j1dywfrxvq** [comment]
I mean, as long as I get to have the daily planner in a separate file from daily notes, I don't mind having a heading there.

**Comment by ivan-lednev** [comment]
Closing this as a duplicate of #242
