### ISSUE TITLE
Daily plan not opening up after latest update

### ISSUE THREAD

**Issue by arnoldandinocspe** [ivan-lednev/obsidian-day-planner#259]
My last daily plan was from yesterday morning, today it is not being created. I updated the plug in yesterday in the afternoon. I tried uninstalling and reinstalling the plug in.

**Comment by ivan-lednev** [comment]
Hello, @arnoldandinocspe,

What exactly is not created? Your daily file or the timeline view? I just tried deleting my daily note and opening it through the planner, and it works.

**Comment by arnoldandinocspe** [comment]
My daily file. I can manually create it of course, just wanted to give you the heads up that the automation broke. For me at least.

**Comment by ivan-lednev** [comment]
Can you describe exactly, step by step, what buttons are you clicking, what happens, etc.?

**Comment by arnoldandinocspe** [comment]
Hello @ivan-liadniou-epam 

Usually when I open up Obsidian in the morning, Daily Plan starts up and a new note with today's date is created. As of today, this stopped happening. That is all.

**Comment by ivan-lednev** [comment]
I could not reproduce the issue with the steps you've described. Keeping this open in case someone else adds some more precise steps to reproduce.

**Comment by arnoldandinocspe** [comment]
There is not really a step to reproduce. It is just not working for me, and perhaps it is just me. Before whenever you opened up Obsidian, A note was created for your Daily Plan with the current date. Now that does not happen for me. I do believe I can share a screenshot of a message That I notice might be relevant. There is a caution mark on that message and when I mouse over it the message says "failed on initialization" 

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/66221754/2ae653aa-2589-4241-9a0c-ca30f52626bc)

**Comment by ivan-lednev** [comment]
Can you open developer tools (f12 for Chrome) and check for errors in the console? If there are, please share a screenshot here.

**Comment by arnoldandinocspe** [comment]
Sorry, I do not follow. Obsidian is a windows application on my laptop, Not sure why would I check a browser dev tool. I think we are fine though, it probably is something local to my installation that went awry. As mentioned, I can simply manually create a Note, so it is not a big deal.

**Comment by ivan-lednev** [comment]
@arnoldandinocspe, okay, just to clarify, Obsidian is an Electron app, which is a platform based on Chrome, so the developer tools are the same:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/0aa19278-dbae-41d5-969e-8c49085efd84)
