### ISSUE TITLE
Suggestion: Change icons only when note is active

### ISSUE THREAD

**Issue by benjaminezequiel** [ivan-lednev/obsidian-day-planner#262]
Hi! I wanted to give a little UX suggestion.

I personally find annoying the current behavior in which an item's icon indicator changes while you press CTRL. For me it's really distracting while you are trying to type and using macros with CTRL or even simple copy/paste, the icon changing shifts your attention from the note to the planner, which I think it's a negative experience. 

My current solution was to add a CSS snippet to my vault so that no icon displays ever, since I prefer not having those actions available rather than the current behavior.

**Comment by ivan-lednev** [comment]
Hello, @benjaminezequiel, please update and re-check.
