### ISSUE TITLE
Syntax Error in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Raboro** [ivan-lednev/obsidian-day-planner#263]
In the CONTRIBUTING.md file in **Pull Request Process** the first item is not starting with 1.:

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/88288557/621a2661-99c8-4e38-b564-090d1887e729)

Should be 1. -> 2. -> 3. not 2. -> 3. -> 4.

I can fix this with a PR

**Comment by ivan-lednev** [comment]
Fixed.
