### ISSUE TITLE
checkboxes not showing in timeline

### ISSUE THREAD

**Issue by Rhydderch** [ivan-lednev/obsidian-day-planner#269]
Hello,

You really did a fantastic job with updating this plugin! Thank you.

I reinstalled it and noticed the checkboxes aren't showing up correctly on the timeline. It might conflict with another plugin because it shows up the same on all themes (except "primary" theme, for some weird reason).
<img width="1134" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/3197629/090c7f4b-420d-4721-8952-3f8784ebb345">

**Comment by ivan-lednev** [comment]
Hello, @Rhydderch,

Try disabling all the plugins and enabling them one by one to see which one causes the issue.

**Comment by 1071189147** [comment]
> 您好， ，
> 
> 尝试禁用所有插件并逐个启用它们，以查看哪个插件导致问题。
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/28439235/5a2da7db-00bc-4d85-b721-a55380dcb154)

I am currently using the latest version. And I have created a new vault to ensure that there are no other third-party plugins, but the checkbox is still not displayed and the task will not be automatically completed. What should I do?

**Comment by ivan-lednev** [comment]
@1071189147,
in your case, there are no checkboxes because there are none in your file. Write your tasks this way:
```md
- [ ] 08:20 - 08:50 Task
```

Task autocompletion is not currently implemented.

**Comment by 1071189147** [comment]
> @1071189147, in your case, there are no checkboxes because there are none in your file. Write your tasks this way:
> 
> ```
> - [ ] 08:20 - 08:50 Task
> ```
> 
> Task autocompletion is not currently implemented.

Thanks，I thought a check box would be automatically generated. I changed the `listTokens:" - " `in line 19667 of main.js to`" listTokens: "- []",` which also had the same effect,  Is there a hidden danger in doing so?

**Comment by ivan-lednev** [comment]
Once you re-install or update the plugin, this change is going to break.

**Comment by Rhydderch** [comment]
@ivan-lednev i deactivated all plugins one by one and could not find the culprit.
I inspected the element and it seems the error is coming from this CSS line. If I uncheck it, the checkbox shows up correctly:
<img width="983" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/3197629/ba4de156-7d42-43ee-949e-f0a76cf63d3d">
Any idea of how to fix the issue permanently? (worst case, I'd add my own CSS file

**Comment by ivan-lednev** [comment]
@Rhydderch, the plugin doesn't mess with `--font-ui-small`. You may have a CSS snippet enabled that redefines this variable, or your theme messes it up.

**Comment by Rhydderch** [comment]
Thanks to your comment I looked up the variable. The problem was the minimal theme settings plugin. I hadn't spotted it because just deactivating the plugin doesn't update the CSS variable. I had to restart obsidian.
I can now start enjoying your wonderful plugin :)

**Comment by Rhydderch** [comment]
Note: just putting a value inside the small font size parameter also solves the problem. The problem occurred when the default was set which resulted in an empty value for that parameter which conflicted with the plugin
