### ISSUE TITLE
Planner Heading and Planner Heading Level not working

### ISSUE THREAD

**Issue by josephdong1000** [ivan-lednev/obsidian-day-planner#271]
First off, I only recently updated from 0.5.8 to 0.10.1 and I just want to say I absolutely love the new interactive calendar! Hats off to the team for making this possible. Having an interactive calendar was something that I've always wanted in Obsidian but the other plugins just didn't fit my workflow and/or didn't have this feature. Thank you!

I've noticed the fields `Planner Heading` and `Planner heading level` in the plugin settings don't change the behavior of the plugin. Currently those fields are set in my vault to "Events" and "4", respectively, but I can only get Day Planner to read events if I title the header "Day planner" in my daily note template. Also, `Inserting a Planner Header` will insert the default H1 sized `# Day planner` instead of the expected `#### Events` per my settings.

This is a minor issue since I can easily work around it, but it appears like unintended behavior and might be easy to fix. Cheers!

**Comment by kevinstadler** [comment]
@josephdong1000 I originally had the same issue, turns out that both features (header name and level) can actually be changed, but changes only come into effect after you restart Obsidian!

**Comment by ivan-lednev** [comment]
Starting from 0.11.0, updating settings works immediately.
