### ISSUE TITLE
DayPlanner outline within a callout

### ISSUE THREAD

**Issue by ThomasMathoi** [ivan-lednev/obsidian-day-planner#273]
At the moment the outline of the daily plan is only possible underneath a specific heading in a note. It would be wonderful if that would also be possible in a specific collapsable callout. Especially if you have visually structured your daily note with multiple callouts.

**Comment by ivan-lednev** [comment]
Hello, @ThomasMathoi, please update and re-check.

**Comment by ThomasMathoi** [comment]
Oh, WOW! I will update as soon as it is available - at the moment I can't get the update :-(
