### ISSUE TITLE
feature request: different background color for past tasks or completed task

### ISSUE THREAD

**Issue by Rhydderch** [ivan-lednev/obsidian-day-planner#275]
Hi,

I'm loving the plugin and how it helps me time-block.
Would it be possible to add an option to have a slightly darker background or faded out look to block in the calendar once they are "in the past" or have been completed?

<img width="1072" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/3197629/ba2cb227-8ba8-446b-a78e-1cb4050cb20a">

This would replicate what google calendar allows:
<img width="275" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/3197629/18331604-24e8-4c5e-b542-64532494acc3">

**Comment by ivan-lednev** [comment]
This has been fixed. Please re-check.

**Comment by Rhydderch** [comment]
Thanks. It works well!
