### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by mlevison** [ivan-lednev/obsidian-day-planner#277]
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'isSame')
    at DayPlanner.handleActiveLeafChanged (plugin:obsidian-day-planner:22345:29)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:2027623)
    at t.activeLeafEvents (app.js:1:2013519)
    at l (app.js:1:254406)
    at c (app.js:1:254522)

I'm guessing this problem is happening when a new daily note is loaded. Looking at the code:

 const dayUserSwitchedTo = (0, import_obsidian_daily_notes_interface6.getDateFromFile)(view.file, "day");
      if (dayUserSwitchedTo.isSame(get_store_value(visibleDayInTimeline), "day")) {
        return;
      }
      if (!dayUserSwitchedTo) {
        if (isToday(get_store_value(visibleDayInTimeline))) {
          visibleDayInTimeline.set(window.moment());
        }
        return;
      }

Is there any chance that dayUserSwitchedTo is null?

**Comment by ivan-lednev** [comment]
Hello, @mlevison, please update and re-check. Make sure the Dataview plugin is installed.

**Comment by mlevison** [comment]
D
[2023-10-13.md](https://github.com/ivan-lednev/obsidian-day-planner/files/12896391/2023-10-13.md)
ataview is installed and was when the exception happened, I updated the plugin 0.11.0 and now my weekplanner displays an empty week, except there were plans Wed -> Fri.

However the exception is gone. Today's daily note is attached, no world takeover plans included.

**Comment by ivan-lednev** [comment]
Oh, I added a warning to the timeline view: only tasks `- [ ] 10:00 task` are now recognized. And I see in your file, that you're using bullet lists :) 

This is done to enable Dataview integration and improve performance.

**Comment by mlevison** [comment]
Cool, then i guess this one is closed.
