### ISSUE TITLE
Query dataview only for relevant pages

### ISSUE THREAD

**Issue by lukemt** [ivan-lednev/obsidian-day-planner#280]
Hi @ivan-lednev ,

You probably thought about this too, I just wanted to hear your thoughts. 

Performance wise it would make a lot of sense to only query dataview for the files that are relevant for the current view.

Then querying list items also would not hurt performance.

**Comment by ivan-lednev** [comment]
Hey, @lukemt, the problem is that you don't know which pages are relevant until you scan every list item in them, since it might contain `[scheduled::2023-01-01]`.

**Comment by lukemt** [comment]
Ah i see! I didn't know about that feature. Does not fit my workflow atm, but I can see why it might be useful.

If Dataview has a metadata index one could query only for pages with "scheduled".

**Comment by ivan-lednev** [comment]
@lukemt, to my knowledge we can't say: "Dataview, give me only pages with this property (scheduled)" this works only for paths/links/tags. So we have to take all of them and filter each time.

**Comment by lukemt** [comment]
Hi @ivan-lednev 
This makes sense! I believe too it's not even possible unfortunately.

But I think the way you did this is quite performant nonetheless.

**Comment by lukemt** [comment]
Hi @ivan-lednev 
This makes sense! I believe too it's not even possible unfortunately.

But I think the way you did this is quite performant nonetheless.

**Comment by lukemt** [comment]
Hi @ivan-lednev 
This makes sense! I believe too it's not even possible unfortunately.

But I think the way you did this is quite performant nonetheless.

**Comment by lukemt** [comment]
Hi @ivan-lednev 
This makes sense! I believe too it's not even possible unfortunately.

But I think the way you did this is quite performant nonetheless.

**Comment by Smitty010** [comment]
I will just say that I finally removed obsidian day planner from my vault.  I liked it, but the performance hit was simply too high.  You seem to log every time that you do a query.  I never saw anything less than 500 milliseconds for the time and sometimes it was over a second.  When typing it was not unusual for me to get 40-80 characters ahead of what was being displayed in my note.  I do have a lot of notes in my vault (12k+) which I'm sure affects the search time.

It also appears that you do this in the UI thread.  You should be spawning a thread and doing searches outside the UI thread.  I'm sure that complicates the code, but the alternative is performance that is unacceptable.

**Comment by ivan-lednev** [comment]
@Smitty010, have you tried narrowing down Dataview source?
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/edbd0db6-369d-4f65-932e-372a3f12e41c)

> It also appears that you do this in the UI thread. You should be spawning a thread and doing searches outside the UI thread. I'm sure that complicates the code, but the alternative is performance that is unacceptable.

How can I use the Dataview engine outside the UI thread?

**Comment by Smitty010** [comment]
I will try your first suggestion as the day planner is currently only used in my daily notes which are in a single directory.

Regarding your second comment, it is possible that Dataview cannot be executed outside of the UI thread. I am unsure about this and would recommend seeking assistance from someone on the forum. My programming skills are not specific to Obsidian. Alternatively, the upcoming new Dataview replacement may offer a solution to this issue.

I also wonder if you can't find ways to minimize the times you call Dataview.  If the current file being edited doesn't meet the criteria in the dataview source, can you simply not call dataview at all?  Again, I don't code plugins so I don't know what is and is not possible.

**Comment by lukemt** [comment]
@Smitty010 I believe narrowing the query down to your directory will solve the problem for your use case. It is unfortunate that there seems not much that can be improved here with the current dv version

**Comment by Smitty010** [comment]
I added a directory to the source.  It's the directory where I keep my daily notes which is where the day planner stuff is (I assume that's what the filter is for).  It made a big difference. The times for day planner are now in the 10-20 milliseconds.  It still is a little sluggish, but I would say that it's pretty close to acceptable.  

One of my thoughts was to preprocess the source and use it to determine whether to call dataview or not.  If the current file doesn't meet the criteria, then don't call dataview.  Essentially, write some code to duplicate what is being done by dataveiw analyzing the sources.  Maybe you already do that.  Also, if the current file hasn't changed from the last time you looked and the dataview didn't return anything the last time, there's no reason to look again.  I wonder if there's an event you can register for for a new file being edited.  Just some ideas.  But, as I told my programmers, everything's easy to the person who doesn't need to do it themselves.  Do what you wish.  Cheers

**Comment by ivan-lednev** [comment]
Since 0.17.0, querying is restricted to visible daily notes by default. Feel free to re-open the issue with a comment if it's still relevant.

**Comment by Smitty010** [comment]
Sounds like a good solution. nice job.
