### ISSUE TITLE
Add option to extend task until next one if it doesn't have end time

### ISSUE THREAD

**Issue by Monophonic1983** [ivan-lednev/obsidian-day-planner#283]
Hi there! Is there a way that time would automatically track the current time like it used to be? For instance, if I put the current timecode it will automatically track to the next timecode without me having to manually drag to track the time. It used to be like this, as shown in the picture. 

Now I have to drag the bar in order to track my time, which I think is somewhat complex. Would really appreciate it if there's a button for us to switch from tracking the time automatically or using the drag! Many thanks!

![gzbaoi0z8xba1](https://github.com/ivan-lednev/obsidian-day-planner/assets/75333208/9e1a0776-cbc6-4dc3-afe4-6212fdf0fb08)

**Comment by JosephBrooksbank** [comment]
By tracking the current time, do you mean that you would like the timeline to center on the current time automatically, so that the 'current' task is always in the center of the timeline? If that is the case, it is available as a setting:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/6687530/15f0be04-d882-4196-8bf2-d78ed80900fc)

**Comment by Monophonic1983** [comment]
> By tracking the current time, do you mean that you would like the timeline to center on the current time automatically, so that the 'current' task is always in the center of the timeline? If that is the case, it is available as a setting: ![image](https://user-images.githubusercontent.com/6687530/275619260-15f0be04-d882-4196-8bf2-d78ed80900fc.png)

Sorry for the confusion. To clarify, I would like the timeline to automatically start at 10:00 and end at 12:00 without requiring me to input the time or drag. Here's an example:

-  10:00: Wake up and take a shower
-  12:00: Lunch

The timeline should indicate that it took me two hours from waking up and taking a shower until the next event, which is lunch. 

Now I need to manually input the time or drag the time block to track how my time passes.

**Comment by ivan-lednev** [comment]
Hello, @Monophonic1983,

I'm a bit confused by this:
> I would like the timeline to automatically start at 10:00 and end at 12:00 without requiring me to input the time or drag

How would the plugin "know" when you finished your task?

Aren't you able to do this with a daily note template that already contains the duration of repeated tasks? Like this:
```md
- [ ] 10:00 - 12:00 Lunch
```

With this template, you're going to have a nice 2-hour long block for lunch every day.

**Comment by JosephBrooksbank** [comment]
I think they just want the old behavior, which did not allow end times and 'knew' a task was complete when the next task started, without having to specify end times. 

@Monophonic1983 If @ivan-lednev's solution is not sufficient, let me know and I can work on a setting to optionally add the 'old' behavior back, assuming that it is still possible with how the new plugin is built

**Comment by hy4l** [comment]
IMHO, the best approach is to have both options available at the same time. If I could specify both the start and end times (as a range), or just the start time, then the plugin could assume that the next start time marks the end of the previous event.

![Screenshot 2023-10-17 192308](https://github.com/ivan-lednev/obsidian-day-planner/assets/140013867/4187fdba-f2c0-42af-89d3-81854772178e)
Typing becomes tedious when scheduling back-to-back events. Using the mouse to click and move blocks doesn't offer the precision I need.

**Comment by ivan-lednev** [comment]
This is available as an option in 0.12.0. Check out the 'Duration' section in settings.

**Comment by hy4l** [comment]
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/140013867/2af712ab-c9ef-4564-8541-095111a81444)
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/140013867/6e2877db-1d5a-4b26-aebe-6a0398e37e8b)
It just sets default length, it doesn't check next event start. That creates tasks overlaps and it ruins clear representation of my time that I spent on tasks

It would be great if it could render something like this without writing end time of 🟢Hangouts task:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/140013867/db49ea2d-ddbb-4e8e-9955-96cf8ec854f4)

BTW this control + move block that moves other tasks below is awesome!

**Comment by ivan-lednev** [comment]
@hy4l, did you enable the feature in settings?
Here is what mine looks like:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/1abdbbac-e1ad-4170-8e6a-5a69f6bef0d5)

My settings:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/5b90e741-c583-4e4e-841c-e537c126184a)

**Comment by Monophonic1983** [comment]
> I think they just want the old behavior, which did not allow end times and 'knew' a task was complete when the next task started, without having to specify end times.
> 
> @Monophonic1983 If @ivan-lednev's solution is not sufficient, let me know and I can work on a setting to optionally add the 'old' behavior back, assuming that it is still possible with how the new plugin is built

Yes! Thank you so much for understanding. That's exactly what I wanted to express. By not specifying the end time and let the plugin to track until the next event or task starts would allow me to know how I actually allocate my time in a given day, which is very helpful for me to review and plan my day better. 

If possible, could there be an option to allow users to switch between the current behavior and the old behavior. And plus, I think not everything is a task, sometimes it could be just an event. So if possible, I would really appreciate it if there's an option to choose list instead of forcing us to use tasks. Much appreciate it!

**Comment by hy4l** [comment]
> @hy4l, did you enable the feature in settings? Here is what mine looks like: ![image](https://user-images.githubusercontent.com/41428836/276171419-1abdbbac-e1ad-4170-8e6a-5a69f6bef0d5.png)
> 
> My settings: ![image](https://user-images.githubusercontent.com/41428836/276171795-5b90e741-c583-4e4e-841c-e537c126184a.png)

Thank you very much for your red arrows :) Ether I was too tired yesterday and I didn't noticed that option after update or today's system reboot and 🟣Obsidian restart made plugin update to work.

This is great! 
![bicycleRepairMan_05](https://github.com/ivan-lednev/obsidian-day-planner/assets/140013867/caccebc9-5359-456d-9e95-75b25ce37d48)
