### ISSUE TITLE
Tasks scheduled for a day but not created in the current daily notes file are ignored 

### ISSUE THREAD

**Issue by jaxley** [ivan-lednev/obsidian-day-planner#284]
Expected:
When I use the tasks plugin to manage tasks, and I schedule a task for a given day, e.g. 2023-10-16, and I put a timeframe in the task like 15:00-16:00, then I expect it to show up on the daily planner for the day 2023-10-16. This should happen no matter the file that task that is scheduled exists. e.g. could be in a Weekly tasks file or otherwise.

Actual:
The scheduled task does not show up on the daily planner for 2023-10-16. Only way I can get it to do that is if I define a new task in the daily note file.

I looked at the code and it seems that the code makes an explicit check if the task path is inside the current daily note BEFORE it checks to see if it is scheduled for the current day:
https://github.com/ivan-lednev/obsidian-day-planner/blob/98886688e3d7a48b978cb2706947f9616f9a6f9c/src/util/get-tasks-for-day.ts#L23C1-L28C8

If that check was removed or the order swapped, then it would probably work as I'd expect.

**Comment by ivan-lednev** [comment]
Hello, @jaxley,

I think I'm not totally getting it. Is it the case that tasks scheduled for the day in other files don't show up unless there is a daily note for the day?

I released a fix to a similar issue, so you might try to update and re-check.

**Comment by kmaustral** [comment]
It's great to see the pace of development in Day Planner.

I'm finding that tasks with "[scheduled:: 2023-10-25]" in notes other than Daily Note appear in the planner sidebar, but only when a time is specified. Is that right?

But tasks with "⏳ 2023-10-25" do not appear, which I thought the new version was able to see. 

This is with version 0.13.1.

**Comment by ivan-lednev** [comment]
This should've been fixed some time ago.
