### ISSUE TITLE
The time information is overwritten in the CheckBox

### ISSUE THREAD

**Issue by harrislop** [ivan-lednev/obsidian-day-planner#286]
Once I import the note information, it is recognized at first, but when I add a schedule, it is added to the preview.
Does this plug-in not support Embedded?

**Comment by ivan-lednev** [comment]
Hello, @harrislop, I didn't get what you were saying here:
> Once I import the note information, it is recognized at first, but when I add a schedule, it is added to the preview.

But no, this plugin doesn't support embeds.

**Comment by harrislop** [comment]
> Hello, @harrislop, I didn't get what you were saying here:
> 
> > Once I import the note information, it is recognized at first, but when I add a schedule, it is added to the preview.
> 
> But no, this plugin doesn't support embeds.

Oh, really. All right. I should make a different list at the bottom and manage it. Thank you :)
