### ISSUE TITLE
Status bar doesn't show up properly

### ISSUE THREAD

**Issue by twirlined** [ivan-lednev/obsidian-day-planner#288]
I think `Status Bar - Circular Progress` is not working even when it is toggled and `Status Bar - Now and Next` is always on even when it is toggled off.
I use Minimal theme and keep my Day Planner Timeline on the right sidebar.

- When `Status Bar - Circular Progress` and `Status Bar - Now and Next` are both toggled off.
<img width="569" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/52314543/96b0b94a-9576-4e74-a3e2-3ea2caa96be2">

- When only `Status Bar - Circular Progress` is on.
<img width="438" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/52314543/d5f4b85b-b1a8-48cd-b937-89bf071463a1">

- When only `Status Bar - Now and Next` is on.
<img width="538" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/52314543/02c90175-e0f4-46fd-a59f-9e7becdc01eb">

- When both are toggled on.
<img width="455" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/52314543/257f0663-69a4-421a-9af7-bdd0c8c7b27d">

**Comment by ivan-lednev** [comment]
Please update and re-check. Note that the settings for the status bar have been changed.
