### ISSUE TITLE
Timeline always reopens at the top right sidebar when clicking status

### ISSUE THREAD

**Issue by twirlined** [ivan-lednev/obsidian-day-planner#289]
When I click the Now and next part on the status bar, it always reopens on the top right sidebar.

I usually keep my Timeline at the bottom right sidebar.
I checked other locations like the top left, bottom left, middle right but they all get closed and reopened at the top right.

**Comment by iranimij** [comment]
May I work and fix this bug?

**Comment by ivan-lednev** [comment]
Sure

**Comment by ivan-lednev** [comment]
Hey, @twirlined, please update and re-check.
