### ISSUE TITLE
The plugin stopped responding

### ISSUE THREAD

**Issue by adrianjav** [ivan-lednev/obsidian-day-planner#290]
Hi,

I love the plugin, and I have been enjoying it for a few weeks. However, since yesterday it stopped working without apparent reason: everything I did was switching to the weekly planner with the command palette (but I doubt that caused the problem).

The weekly planner is completely gone. I have a white screen, the title, and the navigation buttons on top, and that's about it. The navigation buttons to change weeks are there but don't do anything at all (the week numbers on the top bar do not change either).

About the day planner timeline, it renders the timeline (the cells with the timeslots and the current time) but tasks are not displayed and the interface does not respond (that is, clicking/dragging on the timeline does not trigger anything). In the timeline, all the buttons on the top bar work, except for clicking on the current date, that does not open the note for the current day.

As for fixing it, I've tried changing back my theme from Minimal to the default one, as well as completely re-installing the plugin, but that did not help.

I am not sure how can I provide any other useful information (I have no experience debugging obsidian plugins), so please just let me know. Thanks for the plugin!

**Comment by ivan-lednev** [comment]
Hi, I suppose it gets fixed when you reload Obsidian? If it crashes, please open the developer console (`Ctrl + Shift + I` on Windows) and send me a screenshot of the error there.

**Comment by adrianjav** [comment]
Sorry, forgot to say that, it does not get fixed when I reload Obsidian. I actually haven't managed to get it back to normal.

After opening the developer console in the weekly planner (thanks for the tip!), I can see ~20 errors. Most of them are the same ones, so I assume that the rest are related with the main error and the exception-catching system just escalated. 

The root of all exceptions seems to be `Uncaught (in promise) TypeError: task.scheduled.toMillis is not a function` in this line
 https://github.com/ivan-lednev/obsidian-day-planner/blob/b4f531fab0614e4139b3ab771a80ce05af23eabb/src/util/get-tasks-for-day.ts#L16 

I attach a screenshot of the developer console (all exceptions don't fit, but again, I am guessing they are all related with the ones on top). If I understand it correctly, it could be that I have a typo somewhere in my `scheduled` field. I am going to double-check that right now, but if that were the case, I don't think a typo should basically disable the entire plugin.

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/25713831/cf3b439a-658c-4cc7-b65a-0854633ebe4a)

**Comment by adrianjav** [comment]
Solved! I typed one of my tasks too quick and I had `[scheduled:: tomorrow]` rather than `[scheduled:: 2023-10-19]`. Now everything is back to normal.

But maybe the plugin should have some safety checks to handle these errors, because literally nothing was working/rendering/reacting in the timelines.

**Comment by ivan-lednev** [comment]
Yep, you've identified the problem correctly. Please update the plugin and re-check. Now tasks with an invalid date in `scheduled` should not crash the whole plugin.

**Comment by adrianjav** [comment]
Indeed, now it works even with wrongly scheduled tasks. 

Thanks for the super quick fix!
