### ISSUE TITLE
Any way to add the Day Planner to a daily note template?

### ISSUE THREAD

**Issue by echoleaf** [ivan-lednev/obsidian-day-planner#292]
I tried
```
## Day Planner
- [ ]
```
But when I made my daily note the Day Planner was not recognized. It seems that adding it by command is the only thing that works.

**Comment by ivan-lednev** [comment]
What do you mean by "not recognized"?

**Comment by captureMebutProbablyNot** [comment]
That's because it should look like this: # Day Planner

You have too many ##

**Comment by echoleaf** [comment]
Thank you.

**Comment by FeralFlora** [comment]
This can be closed.
