### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by Felogomez** [ivan-lednev/obsidian-day-planner#297]
**Describe the bug**

**To Reproduce**
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/149029673/98c068c8-8f2b-4494-9649-2fde65ae6830)

**Expected behavior**

**Screenshots**

**Additional context**
![Captura de pantalla 2023-10-25 210407](https://github.com/ivan-lednev/obsidian-day-planner/assets/149029673/16e51597-213b-4948-9bde-3c12a24f25e9)

**Comment by xlndql** [comment]
me too

**Comment by RapidaCJ** [comment]
And me

**Comment by RapidaCJ** [comment]
The versions don't match.
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/53539387/b7d6100c-25a2-4e6a-a5fc-55d993a1a12c)
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/53539387/f55bff8f-e8d6-4424-b21b-418f7432bcf3)

**Comment by MD82** [comment]
me, too
failed update
i want to reinstall and fail install

**Comment by tataue** [comment]
just install locally, seems there is a bug
<img width="394" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/1721417/98c8b54a-af47-4381-8f0f-3b4580d93538">

**Comment by tataue** [comment]
> just install locally, seems there is a bug <img alt="image" width="394" src="https://user-images.githubusercontent.com/1721417/278243218-98c8b54a-af47-4381-8f0f-3b4580d93538.png">

<img width="838" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/1721417/f5f5d072-854a-4449-8161-7f94c10cb7fd">
seems it did not respect `Planner Heading` config limit any more.

**Comment by ivan-lednev** [comment]
The previous version should be available now

**Comment by xlndql** [comment]
Now it can be installed successfully
