### ISSUE TITLE
No information in status bar

### ISSUE THREAD

**Issue by kmaustral** [ivan-lednev/obsidian-day-planner#302]
There is no timeline information in the status bar with the latest update.

I tested this on a sandbox vault. Dataview was the only other extension enabled.

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/73867063/373fdf47-1522-4b97-afc5-359efc134b1c)

Previously there was the current calendar entry with the amount of time left. 

There are also no task notifications either.

**Comment by savslug** [comment]
I am experiencing the same issue. The Day Planner information is not being displayed in the status bar.
By the way, this beautiful plugin is vial for my workflow, and I deeply appreciate your maintenance efforts.

**Comment by xshuai1006** [comment]
Same to me. Version 0.15.3.

**Comment by theBenForce** [comment]
Same issue for me, version `0.15.3`

**Comment by aarRJaay** [comment]
Same issue - this was really helpful - Please add it back

**Comment by ivan-lednev** [comment]
Please update and re-check.

**Comment by theBenForce** [comment]
@ivan-lednev just verified it's working with the latest update, thank you!! 🎉

**Comment by alt-milo** [comment]
Is this solved for everyone, it is now showing for me, please check, it is really helpful

**Comment by aarRJaay** [comment]
It's perfect!! Thank you for checking!! Really love this. It's invaluable for my work (soooo many meetings)!!

----------------------------"No trees were killed to send this message, but a large number of electrons were terribly inconvenienced." - Neil deGrasse Tyson

-------- Original Message --------
