### ISSUE TITLE
Feature request: Allow checking off items in the timeline

### ISSUE THREAD

**Issue by cristi-neagu** [ivan-lednev/obsidian-day-planner#304]
Since we have to have all daily tasks as check items for technical reasons, it seems weird that I can't tick them off in the timeline. I should be able to click the checkboxes in the timeline and check or uncheck the items in the daily note.

**Comment by claremacrae** [comment]
If using the Tasks plugin's recurring tasks facility, be aware that it is non-trivial to calculate the dates of new recurrences....

However, someone kindly recently contributed to the Tasks API a function which exposes that logic now.

[executeToggleTaskDoneCommand()](https://publish.obsidian.md/tasks/Advanced/Tasks+Api#%60executeToggleTaskDoneCommand+(line+string%2C+path+string)+%3D%3E+string%3B%60)

**Comment by ivan-lednev** [comment]
Available in 0.23.2
