### ISSUE TITLE
Tasks listed in Timeline view do not change when changing selected date

### ISSUE THREAD

**Issue by thecristen** [ivan-lednev/obsidian-day-planner#306]
**Describe the bug**
Hi, I'm just starting to use this plugin and think I'm running into unexpected behavior.

**To Reproduce**
1. Open Day Planner Timeline
2. Can see the selected day's planner, great
3. Click left or right arrow to go to previous or next day's plan
4. It's still showing the originally selected day's events

**Expected behavior**
I expect the calendar to exclusively display events/tasks for the chosen day.

**Screenshots**
<img width="330" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/2136286/f7ec7654-109c-41d0-8654-5d812aa98018">

<img width="312" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/2136286/8097eaf8-c2c7-4f82-b71a-60aa23502e60">

<img width="307" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/2136286/7fcba8b8-8c8f-4375-bcd6-a8d913b4a41c">

**Additional context**
The rest of the UI seems to change fine. The newly chosen date displays at top in the Day Planner Timeline, and the new date's Daily Note is opened (or created). And the Weekly Planner view displays the expected things.

**Comment by captureMebutProbablyNot** [comment]
I have flagged this bug yesterday. It's reassuring that it's happening to other users as it'll probably be solved quickly!

**Comment by threeq** [comment]
Yes, I've encountered it too. Does this issue exist in the latest version?

**Comment by Git-Sum** [comment]
I too have this issue and am on 0.15.2

**Comment by kjarnot** [comment]
Same.  Just started happening recently.  I'm on 0.15.2

**Comment by ivan-lednev** [comment]
Fixed in 0.15.3

**Comment by thecristen** [comment]
confirmed fix. thank you @ivan-lednev!!
