### ISSUE TITLE
Slow and unresponsive when moving tasks

### ISSUE THREAD

**Issue by miharekar** [ivan-lednev/obsidian-day-planner#307]
I believe this is since the dataview change, but day planner went from my favorite plugin to very frustrating to use 😬

There are multiple issues:
- the biggest one for me is that it's now super slow and always blocks entire UI whenever I move a task
- ctrl + drag sometimes moves the task that is in the other direction from dragging as well
- shift + drag no longer duplicates with move but as copy and resize? Not super sure what the actual behavior is

The latter 2 I can get around, but the UI freezing is really annoying. Oh, I have a MacBook Pro with M1 Max and an iMac Pro and I experience this on both. 😅

![CleanShot 2023-11-03 at 09 07 57](https://github.com/ivan-lednev/obsidian-day-planner/assets/986645/a4ca05a6-63aa-4b23-85d9-1c47a2823179)

**Comment by Rickyfs** [comment]
I get the same ui freeze issue, sometimes it gets stuck on forever spinning cursor. Same behaviour on both linux and windows

**Comment by captureMebutProbablyNot** [comment]
Please tell me how you get different colors for work and lunch!

**Comment by ivan-lednev** [comment]
Hello, @miharekar, this should've been fixed a while ago. Please re-check.

**Comment by miharekar** [comment]
@ivan-lednev yup, works great!

I stopped using the plugin in the mean time since it was so frustrating and I couldn't see when it was fixed :)

Thanks so much!
