### ISSUE TITLE
Day Planner Panel and Weekly Planner Blank or Unresponsive

### ISSUE THREAD

**Issue by elizdlt202** [ivan-lednev/obsidian-day-planner#308]
Seems to have occurred just some time since the last update.

This happens just after opening obsidian.

**Expected behavior**
The day planner panel is empty..... or sometimes after reload an empty timeline shows but none of my tasks from daily notes are visible. And I cannot click on the timeline to add anything either. The right top corner settings are also unresponsive. And the week planner has the same issue. Sometimes its blank and other times after reload I see the 'grid' boxes but I still cannot add/edit anything.
![Screen Shot 2023-11-03 at 6 40 39 AM](https://github.com/ivan-lednev/obsidian-day-planner/assets/49735067/3a24b5f3-226a-48e0-8e20-9e6f1978e455)

 **### This plugin can be soooooo useful - I really wanted to use it.... please help.** 

**Can anyone comment if they've had the same issues????!!****
![Screen Shot 2023-11-03 at 6 36 08 AM](https://github.com/ivan-lednev/obsidian-day-planner/assets/49735067/fd9b52dd-aaf4-4e1c-9096-535602f5c98d)

**Comment by ivan-lednev** [comment]
When you see this, please open the developer console and show me the error you see there: `ctrl + shift + i` on Windows.

**Comment by ivan-lednev** [comment]
Closing this as stale.
