### ISSUE TITLE
Unscheduled nested bullet tasks won't show up in the timeline

### ISSUE THREAD

**Issue by Monophonic1983** [ivan-lednev/obsidian-day-planner#310]
**Describe the bug**
Unscheduled inline tasks won't show up in the timeline

**Expected behavior**
The task should be able to be identified and show up at the top of the timeline like other unscheduled tasks. 

**Screenshots**

This is nested bullet task scheduled for 11.06.
> <img width="293" alt="CleanShot 2023-11-06 at 12 17 09@2x" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/75333208/a1b12d3a-589e-4439-8e65-a05e7005be4b">

But it does not show up in the timeline. 
> <img width="324" alt="CleanShot 2023-11-06 at 12 18 03@2x" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/75333208/e8e37dcc-f9f5-444e-b83f-42f5f7b208fa">

This is un-nested task scheduled for 11.06
> <img width="252" alt="CleanShot 2023-11-06 at 12 18 41@2x" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/75333208/ff20ec04-5996-4eee-9deb-5d388c7b098d">

And it did show up in the timeline.
> <img width="317" alt="CleanShot 2023-11-06 at 12 19 10@2x" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/75333208/94c871f8-4165-4281-bcac-510615d8bf24">

**Comment by ivan-lednev** [comment]
Have you tried clicking this button?
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/60496302-4150-4506-bc5e-442e32149a3a)

**Comment by Monophonic1983** [comment]
Oh thanks! It works! Thanks again!
