### ISSUE TITLE
"Open week planner" button closes/replaces last used tab

### ISSUE THREAD

**Issue by gerardbosch** [ivan-lednev/obsidian-day-planner#313]
**Describe the bug**

- When you click the button on the image, the last focused note/tab is closed and replaced by the "Week Planner" tab.

Also, the back button is disabled so you cannot navigate back from the note it was previously open before the week planer.

This is quite inconvenient as you probably don't want to close the note you have on screen, but just open the planner in a new tab, check the week and continue where you left before. But you can't as the note was closed and you have no track to it.

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/30733556/990449bc-37c9-4efc-94b3-cc387e8985f2)

**To Reproduce**

1. Click the button
2. The last focused note is replaced
3. The document/note is now closed and you cannot navigate back to it either.

**Expected behavior**

I would expect that the planner is opened in a new tab so I preserve all open tabs unmodified.

**Comment by ivan-lednev** [comment]
Hey, @gerardbosch, please update and re-check.

**Comment by gerardbosch** [comment]
Forgot to answer on the day, but thanks! Works fine :)
