### ISSUE TITLE
[Feature request] Week planner: Show unscheduled tasks on top

### ISSUE THREAD

**Issue by gerardbosch** [ivan-lednev/obsidian-day-planner#314]
**Describe the bug**

💡 _This is a feature request_

### Context

The day planner pane can show unscheduled tasks (tasks that has no specified time). Unscheduled tasks are shown at the top of the schedule like this:

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/30733556/5dc1720e-d20f-4903-af3e-fbcdba30a0f4)

This is not the case for week planner view. So when you look the overview of the week, you don't see those tasks.

Showing them would help to organize or plan the whole week on the same view:

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/30733556/b2c0bfd0-2320-43a9-be77-5b26f5b396fe)

### Request

Implement the unscheduled task view in "Week Planner" likewise day planner pane 😃

**Comment by Jungal10** [comment]
I would appreciate being able to see ALL unscheduled Tasks from the entire Vault.

Currently, only already scheduled tasks (from the entire vault, yes) are visible.  OR, if they are unscheduled but are on the daily note if I got it right

**Comment by ivan-lednev** [comment]
Hello, @gerardbosch,

this is available in 0.20.0. Please update and re-check.

Hey, @Jungal10, that's an interesting suggestion. Could you create a separate issue and add a more detailed description?

**Comment by Jungal10** [comment]
> Hello, @gerardbosch,
> 
> this is available in 0.20.0. Please update and re-check.
> 
> Hey, @Jungal10, that's an interesting suggestion. Could you create a separate issue and add a more detailed description?

thank you for following-up. I added the issue as requested (:
