### ISSUE TITLE
"Go to next day plan" button potentially creates empty files

### ISSUE THREAD

**Issue by gerardbosch** [ivan-lednev/obsidian-day-planner#316]
**Describe the bug**

Hi! I consider the following an unexpected+unwanted behavior. When you click the next or previous day button, a new empty daily note file is created in case the file does not exist.

I wouldn't expect that navigating through a calendar potentially creates new files for each click.

This also pollutes the calendar plugin, as displays a dot on every day, despite the file being empty (no tasks in there).

When I browse the calendar I'm just doing this: browse. The daily note file should be created only in case I add something in the "daily plan" widget/pane.

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/30733556/0c1a1f2b-eff9-44cd-b7a3-04a70d189a49)

**To Reproduce**

1. Click the next day button until you get to a date that has no daily note
2. A new empty file is created for that day

**Expected behavior**

- No file should be created just by the fact of navigating on the planner calendar.
- The file should only be created when adding a task on the planner.

**Comment by flomax** [comment]
Same issue as [247](https://github.com/ivan-lednev/obsidian-day-planner/issues/247)

**Comment by AuthenticCoder** [comment]
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/12873680/7ea4d9af-467c-467d-9472-ed7c1a1e25d5)
This is from [Calendar](https://github.com/liamcain/obsidian-calendar-plugin) Plugin.
Please add an option like this on day-planner.

**Comment by ivan-lednev** [comment]
This has been fixed some time ago.
