### ISSUE TITLE
[Feature Request] Color blocking

### ISSUE THREAD

**Issue by captureMebutProbablyNot** [ivan-lednev/obsidian-day-planner#317]
I would love to see where you could change the color in the day timeline. You'd be able  to configure what each color means for you in the options panel.

This way you could make pink for self care or purple for studying tasks. Even if you cannot label the colors I'd  still prefer to change them in the day timeline. Regardless I'm loving your plugin and appreciate you making it!

**Comment by Admorei** [comment]
Thats exacly the feature that I wanted to ask for. At best even a tag or something that could be added in the task that then doesnt get rendered or replaced by an emoji or icon.

**Comment by neighthan** [comment]
I was also going to request this. I think a nice format would be having a settings table where you can add a new tag and the color you want associated with it (with a color picker probably) and then in the planner you can add a tag somewhere in a line item like

```
* [ ] eat breakfast #food
* [ ] write paper #work
```

to get the color in the planner view.

**Comment by cgeorg** [comment]
+1 to this request, would love to see this especially in the weekly planner view as a visual confirmation of the types of tasks my week is made up of. My first thought was using a #tag and being able to choose set color per tag.

**Comment by ivan-lednev** [comment]
This is available in 0.20.0. Check out plugin settings.

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/3198b104-dd77-498a-a398-dcd48610494b)
