### ISSUE TITLE
The progress bar not showing up

### ISSUE THREAD

**Issue by Amina-FCC** [ivan-lednev/obsidian-day-planner#319]
**Describe the bug**
The display of the progress bar, as well as the notifications are not working anymore.

**To Reproduce**
1- Add a time block in the timeline
2- Edit the duration of the time block in the daily note

**Expected behavior**
A progress bar should be displayed at the status bar, indicating the remaining time of the related time block.

**Screenshots**
<img width="908" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/149249700/40c92b35-dd66-4209-bb4b-9e2b444c6aef">

**Additional context**
Here are the screenshot of the configuration of the plugin:
<img width="533" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/149249700/78a00273-3d76-4054-bcd1-898edec79184">
<img width="546" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/149249700/4f8695a0-5197-4b9f-85d4-2d15cbd2ebd8">
<img width="531" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/149249700/ec6eefd7-cb78-4077-a234-c09c4c55e1b5">

**Comment by alghenab** [comment]
same here. notifications are not working as well...

**Comment by boxibi24** [comment]
I got the same issues here

**Comment by ivan-lednev** [comment]
Please update and re-check.

**Comment by seannik** [comment]
Cheers - fixed for me

**Comment by Amina-FCC** [comment]
The progress bar is working again after the update. Thanks 🙂.
