### ISSUE TITLE
Support for 12-hour AM/PMformat in timeline?

### ISSUE THREAD

**Issue by calculuschild** [ivan-lednev/obsidian-day-planner#322]
**Describe the bug**
It seems the timeline view only supports 24-hour time. If I set my time format to `h:mm a` (12-hour format with am/pm), the timeline is stuck at `HH` format.

**Expected behavior**
If we can change the Default timestamp format, it seems the display format in the timeline should match.

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/5878534/99f14f77-7e52-4f8b-81d5-07f5587415ef)

**Comment by captureMebutProbablyNot** [comment]
I've had to print out a chart to remember them.

**Comment by batrand** [comment]
I would also love to have this option!

**Comment by ivan-lednev** [comment]
Please update and re-check.

**Comment by calculuschild** [comment]
Nice! That was fast!

Thanks much @ivan-lednev !
