### ISSUE TITLE
[Bug] Timeline shows ALL checklist items in daily note, not just under specified heading

### ISSUE THREAD

**Issue by pandasaurusesrex** [ivan-lednev/obsidian-day-planner#324]
**Describe the bug**
Day Planner's plugin settings asks users to specify the heading text + heading level that the plugin will search for within a daily note to detect the day plan (presumably pulling from it to populate the timeline). 

However, the timeline display does **not** respect this setting. Instead ALL checklist items in the daily note, even those belonging to other sections of the note, are displayed in the timeline. This is the case whether the item starts with a time, or has no associated time at all (in which case it populates the "Unscheduled" section at the top of the timeline).

**Expected behavior**
Timeline entries, whether unscheduled or associated with a time slot, should be limited to the checklist items found under the combination of heading text + heading level within a daily note, as specified in Day Planner's settings. 

For example, if I've specified "Day Planner" and "H2" in settings, the timeline should NOT display checklist items under another heading, unless it is contained within the "Day Planner" section.

**Screenshots**
Current timeline behavior (showing examples of both what should and should not be displayed):

<img width="427" alt="Screenshot 2023-11-20 at 1 28 06 PM" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/151563940/6296c0e8-4f6c-47cd-b938-9e667f76e5c2">

**Additional context**
- I'm not sure if the timeline is intended to include tasks/checklist items belonging to subheadings under the "Day Planner" heading... I'm guessing that it probably should. For example, if in settings, "Day Planner" + H2 are specified, and in the daily note, there are two subsections under `## Day Planner` (e.g. `### Scheduled Tasks` and `### Unscheduled Tasks`), the timeline should display all checklist items under those sections. Meanwhile, all checklist items outside of `## Day Planner` should be excluded from the timeline.
- All of the above is also true for the "Week Planner" view

**Comment by ivan-lednev** [comment]
Hello, @pandasaurusesrex,

This behavior is intended. A recent update added the ability to include tasks into the plan from any file in the vault. So the heading text from the settings serves only as a destination for newly created tasks. I'll update the setting description to reflect that.

**Comment by pandasaurusesrex** [comment]
Hi @ivan-lednev,

Thanks so much for your reply--and for all your hard work on this awesome plugin!

In light of the changed intended behavior with the recent update, I'm wondering if you would consider making it an option in Settings to only pull tasks from the heading designated in Settings. Would it break the Dataview integration to offer this option? I don't totally understand the rationale for the change (was trying to glean it from [this thread](https://github.com/ivan-lednev/obsidian-day-planner/issues/282#issuecomment-1775645844) and the documentation you linked there), but the change seems quite sweeping and may not align with some people's mental models of Day Planner and how they intend to use it. I don't think I'm alone in this, and to be honest, I don't think it's just a matter of it not being clear in the documentation. 

Not all checklist items across all my files are time-anchored tasks. As I was trying to show in my example, checklists could be used for grocery lists, books to read, people to send holiday cards to, etc. I'd love to be able to specify a section of my daily note for time-blocking, and limit it to that section only... if I want to add it to my timeline, I'll deliberately include the checklist item in that section. Otherwise, I don't want my checklist items to be grabbed as tasks.

**Comment by ivan-lednev** [comment]
Duplicate of #382
