### ISSUE TITLE
Add time tracking

### ISSUE THREAD

**Issue by HWiwoiiii** [ivan-lednev/obsidian-day-planner#330]
implement all functionalities in
ticktick https://help.ticktick.com/articles/7054286604315131904
toggl track https://toggl.com/track/

Enhance Obsidian to be an all-encompassing solution for daily management, incorporating a comprehensive set of features akin to both TickTick and Toggl Track. This includes integrating a daily timer, Pomodoro technique, Eisenhower Matrix (4-quadrant time management system), habit tracker, task archiving, and the ability to create events seamlessly under the daily folder (Daily notes folder/folder named with the current date/Events).

![f61ef428c7cece5b3c24dc1f87482cc4](https://github.com/ivan-lednev/obsidian-day-planner/assets/103039908/d54a4b8e-9215-4617-802c-d5bbbdb7e0b8)
![a6743c84a292de81aca3cf254c2829ae](https://github.com/ivan-lednev/obsidian-day-planner/assets/103039908/9a81db53-3a7f-47a9-b8cf-df7b6d50e294)
![OIP](https://github.com/ivan-lednev/obsidian-day-planner/assets/103039908/2e64d4fb-db23-4937-a03b-48f1842ca14a)
![feature-mobile-oneclick](https://github.com/ivan-lednev/obsidian-day-planner/assets/103039908/a4497be0-484a-4dd0-9e9a-04b52ffc2009)
![fed50fc4a07de1bf9d8d630bb0d3bf1b](https://github.com/ivan-lednev/obsidian-day-planner/assets/103039908/0de3bb5e-87e7-42f7-bb25-bef430dd026c)

**Comment by HWiwoiiii** [comment]
https://forum.obsidian.md/t/make-obsidian-omnipotent-for-daily-management/72112

**Comment by ivan-lednev** [comment]
Hey, @LBWNB55KYYDS,

You do realize that this plugin is mostly a one-man operation, done as a hobby that brings no income, and that TickTick or Toggl are built by big teams of full-time developers, right? 😅 

If you want some particular feature to be included, please create a separate **focused** issue, like "add this kind of view with these buttons so I can do this and that".

Closing this one as impossible to implement.

**Comment by HWiwoiiii** [comment]
Really sorry about this post, I didn't mean to be absurd😂.  I understand that incorporating all these features could be a huge work for an individual developer, so I have also posted this on the Obsidian official forum.

Currently, the most crucial feature for me is a timer that allows users to seamlessly track their daily activities, similar to the timer in Toggl Track. I haven't found any other plugins that can perform a similar function. I genuinely hope that you can integrate this functionality into your plugin.

Since toggl track is open source, I suppose maybe it is less difficult to develop a plugin with similar features? Or that there are some restrictions prevents people from using their source code?

Once again, thanks for your amazing plugin!

**Comment by ivan-lednev** [comment]
Sure, the time tracking part looks like an interesting challenge. 

I'm probably going to add another view that looks like the timeline, it's just going to function as a tracker, writing tracked time to tasks in a format that Dataview understands. Something like this:
```md
- [ ] Task
      [clocked::2023-11-30T11:32:00--2023-11-30T11:45:00]
      [clocked::2023-11-30T11:32:00--2023-11-30T11:45:00]
      [clocked::2023-11-30T11:32:00--2023-11-30T11:45:00]
```

**Comment by HWiwoiiii** [comment]
I'm looking forward to seeing the improvements!

**Comment by ivan-lednev** [comment]
Basic time tracking is available in the latest release.
