### ISSUE TITLE
[Feature Request] support 5 minutes increments & default task duration 10minutes

### ISSUE THREAD

**Issue by helheimcloud** [ivan-lednev/obsidian-day-planner#331]
Hey guys, 

first of all - I just discovered dayplanner and I already love it for my use case. I need to track billable hours as an IT-Administrator and use dayplanner to create the items. Dayplanner allows me to freely move and adjust these entries quickly, which really helps with the busy days of an administrator. 

My feature request to remediate my only "issues" with it: 

- Allow 5minutes increments when moving items, instead of default 10minutes
- Allow default task duration to be 10minutes
- When clicking on a new item, the text curser starts in front of the time, instead of replace mode of the text "New Item" which results in an extra click

Big love to you!

**Comment by ivan-lednev** [comment]
Hello, @helheimcloud, the first one is addressed in 0.16.0.

**Comment by helheimcloud** [comment]
Awesome, thank you!

**Comment by ivan-lednev** [comment]
Second part added in 0.23.2
