### ISSUE TITLE
Dataview dynamic data is not rendered in daily and weekly view

### ISSUE THREAD

**Issue by loky-lp** [ivan-lednev/obsidian-day-planner#333]
**Describe the bug**
Maybe i'm pushing this elements to the limit and this behaviour it's as is by design, but tinkering with templates i was trying to automatically schedule a task for the current day by using the `[scheduled:: yyyy-MM-dd]` and dataview function to catch the note title which has the day in it.

Te task is correctly picked up but while the note view render the scheduling correctly the day and week views show the dataview query, as shown in the screenshot below

**To Reproduce**
Create with a name of a day in this format `yyyy-MM-dd`
Paste this content:
```markdown
- [ ] 08:00 - 09:00 Task `="[scheduled:: " + dateformat(date(this.file.name), "yyyy-MM-dd") + "]"`
- [ ] 09:00 - 10:00 Task `="⏳ " + dateformat(date(this.file.name), "yyyy-MM-dd")`
- [ ] 10:00 - 11:00 Task [scheduled:: 2023-12-01]
```

**Expected behavior**
To have in the dataview the same rendering of the note view

**Screenshots**
<img width="880" alt="Screenshot 2023-12-01 alle 16 34 07" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/71527839/11d1d50c-02d9-40b9-81ff-3c263b351533">

**Additional context**
- Obisian v1.4.16
- Day Planner v0.16.0

I would be happy to help but i don't know where to start

**Comment by ivan-lednev** [comment]
The tasks are picked up correctly because they are in a daily note, not because they have the computed property. 

How computed props are displayed in time blocks is controlled by Obsidian's own API. You can create a feature request in their repo: https://github.com/obsidianmd/obsidian-api/issues

**Comment by loky-lp** [comment]
Yeah the problem is not the picking up of the tasks, what seems strange is the task rendering in the timeline view.

If I'm understanding things correctly you try to render the task [here](https://github.com/ivan-lednev/obsidian-day-planner/blob/faf655606bcf709491cfffe78f6a5ca10bfe331f/src/ui/components/rendered-markdown.svelte#L16C64-L16C64) which ultimately tries to render the markdown [here](https://github.com/ivan-lednev/obsidian-day-planner/blob/faf655606bcf709491cfffe78f6a5ca10bfe331f/src/main.ts#L80C12-L80C12), but since the markdown of a task could contain things related to other plugins, in this case dataview, why should obsidian care about integrations of plugins.

Should each plugin take care to render/process data of integrated plugins?

I'm not pointing finger, i appreciate your work and I'm just new to the obsidian ecosystem

**Comment by ivan-lednev** [comment]
This is a very rare use case, and it'll likely take a lot of effort to resolve, so closing this for now.
