### ISSUE TITLE
For some reason `shift` and `control` hotkeys don't work.

### ISSUE THREAD

**Issue by kouliavtsev** [ivan-lednev/obsidian-day-planner#338]
**Describe the bug**
I am new to this plugin. When I try to use `shift` and `control` nothing happens.

**To Reproduce**
1. Go to 'daily view'
2. Hold `shift` key.
3. Hold `control` key.

**Expected behavior**
Move stacked items or copy items.

**Screenshots**

![Screenshot 2023-12-09 at 12 59 33](https://github.com/ivan-lednev/obsidian-day-planner/assets/1392575/e910b795-ce95-4bf9-aee6-debecb51d759)

**Additional context**
Version `0.16.0`

**Comment by ivan-lednev** [comment]
Hello, @kouliavtsev,

did you grab a task while holding those keys or did you just move your mouse?
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/c5cf9fd4-4fee-406c-b7a6-d90110fa5663)

**Comment by ivan-lednev** [comment]
Closing this as stale.
