### ISSUE TITLE
Mobile: drag-and-drop edit support

### ISSUE THREAD

**Issue by ibash** [ivan-lednev/obsidian-day-planner#340]
**Describe the bug**

**To Reproduce**
1. Add a task to timeline view
2. Go to timeline view on mobile
3. Tap a task and try to drag

**Expected behavior**
Task moves to new position / time.

**Actual behavior**
Task does not move

I'm on iOS, iPhone 13 mini.

**Comment by psychsatani** [comment]
I have not seen this drag and drop work on mobile since the plugin was launched. I assumed it’s a missing feature. I also am on iPhone 13 mini.

**Comment by FelixAddison** [comment]
I also am unable to drag and drop tasks on mobile. Android 12

**Comment by ivan-lednev** [comment]
Hello! This is not implemented yet, marking it as an enhancement.

**Comment by ivan-lednev** [comment]
Available in 0.21.1.
