### ISSUE TITLE
Don't create tasks on single click

### ISSUE THREAD

**Issue by ibash** [ivan-lednev/obsidian-day-planner#341]
**Describe the bug**
Currently clicking anywhere in the timeline view creates a task. Instead detecting a click + drag should be done (similar to google calendar or cron) so that tasks aren't accidentally created.

**To Reproduce**
1. Go to timeline view
2. Click on space without a task (and do not drag)

**Expected behavior**
No task is created

**Actual behavior**
A task is created

**Additional context**
I am assuming most people are used to google calendar / cron / apple calendar. Clicking empty space in those apps doesn't make a calendar event, only click and dragging does. Timeline view should behave similarly.

**Comment by thomaszdxsn** [comment]
or give a option to disable click behavior.

I only want use text to create event.

**Comment by ivan-lednev** [comment]
In 0.25.0 you can undo accidental creation. This partially covers this request.

**Comment by technotherion** [comment]
The "Undo" option is a very helpful improvement. However, I more commonly find that I am mis-clicking the timeline more often than I am clicking on purpose, meaning that I'm hitting "Undo" more often than not. This is why I think that a "confirm" approach may be more helpful for myself and other users.

**Comment by ivan-lednev** [comment]
A simple edit modal that may be canceled is added in 0.27.0. Please update and re-check.
