### ISSUE TITLE
Can't Change the starting day of the Week Planner

### ISSUE THREAD

**Issue by Eigengrau16161D** [ivan-lednev/obsidian-day-planner#345]
**Describe the bug**
Apologies if this is already implemented, because I can't seem to figure out how to do it. I would like to set the week planner view to start on Sunday. It currently starts on Monday, which I think I would make sense in most use cases, but a lot of my projects regularly end on Saturday and I would like to view the starting day as Sunday. If there is a way to configure it, I've either missed it in the menus or the readme.

**Comment by captureMebutProbablyNot** [comment]
I've made a similar bug post over a month ago. I don't know if he plans on fixing this.

**Comment by ivan-lednev** [comment]
Closing this as a duplicate of #231.
