### ISSUE TITLE
[Feature request] Ability to change both items when shifting the separator between two items in timeline

### ISSUE THREAD

**Issue by hdsateyate** [ivan-lednev/obsidian-day-planner#347]
Advocating for the ability to change two items simultaneously by dragging between two back to back items in the timeline.

At the moment you can extend an item by dragging from the bottom, I am suggesting to be able to also shorten the item below at the same time. There should be enough room to allow for both functionality using a mouse. See screenshot:
![Screenshot_20240110-164158.png](https://github.com/ivan-lednev/obsidian-day-planner/assets/75562118/d6b5c717-1572-4af2-9665-54739d76f1b5)

Bonus request though I realise this is quite a separate issue. To be able to manipulate the timeline on mobile as well would be awesome.

**Comment by ivan-lednev** [comment]
This is available in 0.21.1:
![image](https://github.com/user-attachments/assets/b474cc97-1410-4913-84c2-5d7854fe40e7)
