### ISSUE TITLE
Launch a template of tasks/ current task / status

### ISSUE THREAD

**Issue by jroachgit** [ivan-lednev/obsidian-day-planner#35]
Hi!
Great plugin.
I wanted to ask if there is a way to populate my daily planner tasks from a template automatically? 
I could just save as a template and then load it by clicking through.

Also, I noticed that my page now doesn't show the inline progress bar with the arrows..
![image](https://user-images.githubusercontent.com/35711815/100375962-c5e54f80-3062-11eb-96d5-cb437358b129.png)

Was this feature removed?

I would've asked about this on the forum, but I couldn't find an existing thread.

**Comment by lynchjames** [comment]
You can create the task entries from a template or add a section to your daily note template with default tasks. These should get picked up when you link the day planner to the note.

I removed the markdown progress bar in v0.5.3 as it was causing issues. I could add it back in a configurable option but it would need some work to resolve the issues.

**Comment by tristanbailey** [comment]
I would like this too, if it would auto create a new day with a single template (or even option for one per day of week). Thank you for the planner.
