### ISSUE TITLE
Using Week Planner-view to move an event/task between days adds wrong "scheduled emoji" (⏳ vs ⌛️)

### ISSUE THREAD

**Issue by esodesod** [ivan-lednev/obsidian-day-planner#350]
Using "Week Planner"-view to move a "task" between days, it adds "wrong emoji", being hourglass (⌛️) and not "hourglass with flowing sand" (⏳), making it incompatible with e.g. plugin Obsidian Tasks (and other plugins using same emoji for "scheduled tasks", using "hourglass with running sand" (⏳).

From the screenshot below, notice the first emoji ("hourglass with flowing sand"), added by Obsidian Tasks vs the last (added by moving the task between days using the "Week Planner"-view).

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/9432339/09831d82-3b68-4286-9575-1800c556d72a)

Tested/verified using Sandbox Vault, with only Dataview, Tasks, and Day Planner installed. MacOS 14.1.2, Obsidian 1.5.3 (Insider)

And thanks for making this awesome plugin!

**Comment by esodesod** [comment]
I'm no developer, but simply tested using a "dirty" replace on the emoji(s) I found in the files below, did a (re)build, and it seems to work as expected (using the very same emoji as e.g. Obsidian Tasks, also when moving tasks between days using "Week Planner").

I can create a PR if this is the correct files/modifications, or you (or any other with better coding skills than me) can review, if possible.

Again, thanks for the work on this plugin!


```diff
diff --git a/src/regexp.ts b/src/regexp.ts
index 2f6f96a..e7c8e42 100644
--- a/src/regexp.ts
+++ b/src/regexp.ts
@@ -35,4 +35,4 @@ export const keylessScheduledPropRegExp = new RegExp(
   `(\\(scheduled\\s*::\\s*)${date}(\\))`,
 );
 
-export const shortScheduledPropRegExp = new RegExp(`(⌛\\s*)${date}`);
+export const shortScheduledPropRegExp = new RegExp(`(⏳\\s*)${date}`);
diff --git a/src/ui/hooks/use-edit/tests/diff.test.ts b/src/ui/hooks/use-edit/tests/diff.test.ts
index 16377bc..91b3055 100644
--- a/src/ui/hooks/use-edit/tests/diff.test.ts
+++ b/src/ui/hooks/use-edit/tests/diff.test.ts
@@ -18,7 +18,7 @@ describe("Finding diff before writing updates to files", () => {
         updated: [
           expect.objectContaining({
             id: baseTask.id,
-            firstLineText: expect.stringContaining(`⌛ ${nextDayKey}`),
+            firstLineText: expect.stringContaining(`⏳ ${nextDayKey}`),
           }),
         ],
       }),
diff --git a/src/util/task-utils.ts b/src/util/task-utils.ts
index dce10ba..ebabe60 100644
--- a/src/util/task-utils.ts
+++ b/src/util/task-utils.ts
@@ -87,7 +87,7 @@ export function updateScheduledPropInText(text: string, dayKey: string) {
     return updated;
   }
 
-  return `${text} ⌛ ${dayKey}`;
+  return `${text} ⏳ ${dayKey}`;
 }
 
 export function updateTaskText(task: Task) {

```

**Comment by ivan-lednev** [comment]
Hello, @esodesod! Thank you for such a detailed description! Easy fix 😌 

Please update and re-check.
