### ISSUE TITLE
Can't launch multiple instances of week planner

### ISSUE THREAD

**Issue by ThatAmuzak** [ivan-lednev/obsidian-day-planner#351]
**Describe the bug**
Launching week planner in a second tab or a separate window when one instance is already active causes the first instance to close.

**To Reproduce**
1. Open a new tab
2. Open week planner (either via command palette or the button on top of the timeline side bar view)
3. Open another tab
4. Launch week planner on this tab (either via command palette or the button on top of the timeline side bar view)

**Expected behavior**
A second instance of Week Planner should launch, and they should (relatively) quickly reflect changes made between these instances

**Actual behavior**
First instance of week planner closes

**Additional context**
It's useful to compare schedules between weeks, and the week planner is a highly useful view. I'm not sure if this is a bug or intentional or if Obsidian's framework doesn't fundamentally allow such a change, but if it's possible then having a toggle to enable it at the very least would be very appreciated

**Comment by ivan-lednev** [comment]
This is now available.
