### ISSUE TITLE
Header is not inserted

### ISSUE THREAD

**Issue by gerroon** [ivan-lednev/obsidian-day-planner#354]
Hi
I am using Periodic Notes and this plugin. I can get a daily created using this plugin which uses Periodic Notes ( which uses my template and the template is something like this

```
- [ ] 15:00 - 17:00 tests
- [ ] 17:00 - 17:30 test2
- [ ] 17:30 - 19:00 test3
```

This note is created properly for today  using this template when I open `show todays day planner`  but it gets no header from this plugin.

**Comment by ivan-lednev** [comment]
@gerroon, the plugin inserts the header only when you create tasks with drag-and-drop. You should add the header to your template like so:
```md
# Day planner

- [ ] 15:00 - 17:00 tests
- [ ] 17:00 - 17:30 test2
- [ ] 17:30 - 19:00 test3
```
