### ISSUE TITLE
[Feature Request] Minimum task height

### ISSUE THREAD

**Issue by Zizipack** [ivan-lednev/obsidian-day-planner#357]
I really need an option for tasks to have a minimum height. 
So that even if the task is for 5 minutes, it would still be visible without the maximum zoom (which is impossible to work with).
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/83618118/e4f9c97f-f776-4439-998c-c11a8bd8314a)
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/83618118/b59f3bdc-c1ae-405b-a86e-ba4350cc2ea4)

Like it is done in outlook, when a meeting is half an hour or less, it is still visible.
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/83618118/38582c3e-5ce4-473f-917a-dc2b1cdf0471)
Or make blocks with time of different lengths, depending on how many tasks are in them

**Comment by Zizipack** [comment]
Sorry. created it wrong somehow, don't know how to remove the label bug

**Comment by masaki39** [comment]
I was able to adjust it with this CSS snippet.

```css
.content.svelte-1g1abnm {
 min-height: 20px
}
```
