### ISSUE TITLE
Feature request Better control of Gantt Segments

### ISSUE THREAD

**Issue by tallguyjenks** [ivan-lednev/obsidian-day-planner#36]
So we have the main segment and the BREAK segment we can put our timeline under
Can we add some syntax to allow creation of custom segments?

like the ability for me to say 

```
- [ ] 07:00 WORK | work task here
- [ ] 09:00 SCHOOL | Studying
```

this way the gantt chart displays the day in various tracks. even cooler would be coupling with #32 to have the different tracks be the different calendars/remidners lists on MacOS

**Comment by ivan-lednev** [comment]
Mermaid is no longer supported.
