### ISSUE TITLE
Tasks do not display when timeline is in "h" instead of "H"

### ISSUE THREAD

**Issue by nolangericke** [ivan-lednev/obsidian-day-planner#360]
**Describe the bug**
If I have a task, and I try and move it on the timeline past 2:00, it does not render in the timeline if the timeline is in "h" format rather than "H".

**To Reproduce**
1. Go to day planner settings
2. Go to hour format
3. Insert "h"
4. Exit and attempt to add task to timeline past 2 o'clock.

**Expected behavior**
Task renders.

**Comment by ivan-lednev** [comment]
Please update and re-check
