### ISSUE TITLE
[Feature request] ctrl+decrease task time should drag up any adjacent tasks

### ISSUE THREAD

**Issue by neighthan** [ivan-lednev/obsidian-day-planner#362]
If you hold ctrl while dragging down to make a task longer, it pushes the tasks below down. It would be nice if we had the same option when shortening a task: ctrl + drag up to make the task shorter and also pull up any tasks below that are adjacent to the current one (no gaps between them). I'd expect this to chain as well so if I have tasks at [1-3, 3-4, 4-5] then ctrl+drag to make (1-3) into (1-2) would pull both of the others up too, giving [1-2, 2-3, 3-4].

**Comment by ivan-lednev** [comment]
Added in 0.21.1. You can now achieve this by 'drag with shrink' from the top of the adjacent task'.
