### ISSUE TITLE
Can someone make a better fork of this?

### ISSUE THREAD

**Issue by Esser50K** [ivan-lednev/obsidian-day-planner#363]
**Describe the bug**
This plugin is getting worse on every update.

1. randomly freezes (cant do anything on the calendar)
2. now it always hangs for 1 second after changing the time of a task (didnt use to)
3. using modifier keys to copy/shift tasks is also very flaky
4. bad Mobile integration

**To Reproduce**
1. Update the plugin whenever there is a new update
2. Find a generally worse experience than before

**Expected behavior**
2. To have a better experience and bugs fixed instead of introduced

**Additional context**
Sorry this is kind of a rant..

**Comment by ivan-lednev** [comment]
Hello,

If you wish so, you can fork it and fix all the pain points yourself.

As for this fork...

> Randomly freezes

Once it does that, open the developer console and add a screenshot of what you see there.

> now it always hangs for 1 second after changing the time of a task (didn't use to)

Share screenshots of the console. My guess is that you pull the tasks from all the files without filtering.

> using modifier keys to copy/shift tasks is also very flaky

> bad Mobile integration

Please be precise. 'Very flaky' and 'bad' are not very helpful in debugging the issue.

**Comment by Esser50K** [comment]
Sorry, was just having a bad day. Issue can be closed as it's not productive.
