### ISSUE TITLE
FR: option to hide "done" task

### ISSUE THREAD

**Issue by firmart** [ivan-lednev/obsidian-day-planner#365]
Hello,

It'd be nice to have an option in the settings to toggle visibility of done tasks (hidden by default).

Explanation : 

Sometime, a scheduled task is done early, and a new task is scheduled in the same time slot. In such a situation, 
we have two time blocks side-by-side, but we actually just want to see one. 

Thanks.  Please keep up the nice work !

**Comment by ivan-lednev** [comment]
Please update and check the settings:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/d5644af8-9b52-449c-bc64-cc999bba06e3)

**Comment by firmart** [comment]
Thanks for your amazing work !
