### ISSUE TITLE
Moving task using list items adds [undefined] (in 0.17.2)

### ISSUE THREAD

**Issue by esodesod** [ivan-lednev/obsidian-day-planner#368]
**Background:** As events using **list items** was re-introduced in 0.17.1, I gave it a quick spin (in 0.17.2, which was released today).

**Issue:** Using timeline (view) to change the time (moving the event using drag & drop) adds `[undefined]` before the timestamp (see below). Using checkboxes, it works as expected.

**To reproduce:** Create a new event using **list** item. Move the task using Day planner timeline view (drag & drop to a new timeslot).

**Note:** Issue re-produced in Obsidian 1.5.6 (Insider), **sandbox** vault, only using latest versions of Dataview, Day Planner and Periodic Notes.

**Screenshots**
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/9432339/538426ae-f163-463d-bd3f-172e7e98d52b)

**Comment by lup3v0** [comment]
Hello - I am experiencing the same issue and can confirm that this bug still exists. The workaround is to use a checkbox, but that isn't ideal as not everything on the timeline is necessarily a task. 

Great plugin, I hope there is a simple fix for this issue!

**Comment by natecox** [comment]
I'm also seeing this behavior. Checkbox works fine, but is undesirable for my note flow.

**Comment by jcromwell** [comment]
Yes, I'm also seeing this behavior in v0.20.3. 
I really enjoy using this plugin and hope a fix is imminent.

**Comment by Gelio** [comment]
This should be fixed by #435 (in review). Let's hope it is merged soon
