### ISSUE TITLE
Any time and a date that Dataview Unrecognized

### ISSUE THREAD

**Issue by kin30528** [ivan-lednev/obsidian-day-planner#369]
**Describe the bug**
thank ur pluggin! Recently, Dataview did not recognize the time and date, I have tried using the new ob vault.
<img width="502" alt="Snipaste_2024-02-21_11-25-37" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/121107652/a4d1cfb2-97a7-4658-9b06-fd69af268fea">

ob: 1.5.7
day planner: 0.18.0
dataview: 0.5.64

**Comment by ivan-lednev** [comment]
Hello, @kin30528,

check out this comment: https://github.com/ivan-lednev/obsidian-day-planner/issues/367#issuecomment-1952767823

**Comment by mtomas7** [comment]
In my case DP will not pull tasks even from daily notes. It happened after last update.

**Comment by mtomas7** [comment]
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/2348962/8b7228f5-2097-453e-8c33-9ef1d6f88bfb)

**Comment by ivan-lednev** [comment]
Hey, @mtomas7, can you reload Obsidian, open dev console and check for errors? If there are any, please add them here.

**Comment by mtomas7** [comment]
Sure. Also, after reload, I see some of the tasks, but some of them are just empty containers without names.

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/2348962/18830e0b-dfdc-4a1a-8441-7a11aa0d48c4)

**Comment by mtomas7** [comment]
Interesting, once I would check the box, then the name of the task would appear in the container.

**Comment by Kang-geophysics** [comment]
I experienced this error in the console.  
When I check the box as you did, the container still does not show anything.

When I reload Obsidian, it seems to be fixed. However, it happens again and again. 
Please let me know the solution.

**Comment by kin30528** [comment]
its working when i tag #task in properties or check box.
thank @ivan-lednev 
<img width="606" alt="Snipaste_2024-02-22_23-22-14" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/121107652/93d73682-2568-4f01-8793-2d9b0d922d40">
<img width="615" alt="Snipaste_2024-02-22_23-23-51" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/121107652/801efb65-cdca-49cc-9a59-19d300e023ef">

**Comment by kin30528** [comment]
@ivan-lednev 
ob: 1.5.8
day planner: 0.18.0
dataview: 0.5.64

its unrecognized again in new an ob vault 😂
<img width="508" alt="Snipaste_2024-02-27_11-04-01" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/121107652/fe949109-7a0c-4021-9eac-7a054b84c0bd">
<img width="509" alt="Snipaste_2024-02-27_11-05-05" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/121107652/f9852552-2894-46ca-85a9-c99153d6b86c">

**Comment by ivan-lednev** [comment]
Please update and re-check.

For now, closing this one as a duplicate of https://github.com/ivan-lednev/obsidian-day-planner/issues/384.
