### ISSUE TITLE
Moving a task on the timeline removes all metadata associated with it

### ISSUE THREAD

**Issue by capsidimit** [ivan-lednev/obsidian-day-planner#370]
**Describe the Issue**
When a task is moved on a timeline, any metadata related to that task is deleted.

**Steps to Reproduce**
To reproduce this issue, follow these steps:
1. Install and activate the Tasks plugin.
2. Create a new note.
3. Give the note a tag, like #task.
4. Add the #task tag to the global filter of "Daily Planner" plugin.
5. Create a new task and choose the current date.
6. Drag the task to any location on the timeline.

**Current Behavior**
After moving a task, any metadata associated with it is lost.

**Expected Behavior**
Metadata related to a task should be preserved when it is moved.

**Comment by hoppla20** [comment]
I really like this plugin, but this also bothers me. This does not only apply to tags, but also to dataview metadata like [scheduled:: <date>]. I have non-daily page with tasks where I set metadata in the dataview format.

While I can see the tasks after configuring the filter, drag-ang-dropping the task or resizing leads to all dataview properties beeing removed.

**Comment by hoppla20** [comment]
This means a tasks on a non-daily page shows up in the timeline, but after drag-and-dropping the task disappears, because the dataview metadata [scheduled:: ] is removed while modifing the time of the task

**Comment by imshenwei** [comment]
#375

**Comment by mateuszkowalczyk** [comment]
I had the same issue and found a temporary workaround.
If you use `(scheduled:: )` instead of `[scheduled:: ]` it seems to be working fine (although it won't show "scheduled" label).

**Comment by svenschuldt** [comment]
> I had the same issue and found a temporary workaround. If you use `(scheduled:: )` instead of `[scheduled:: ]` it seems to be working fine (although it won't show "scheduled" label).

That seems to be working ... and indeed it is missing the label.

Interesting is though: when I have a task with the brackets, and I am moving the task the first time, it keeps the metadata and adds the designated time slot. However, once I have it in the calendar and I move it again, it adapts the timing and now removes the metadata.

**Comment by ivan-lednev** [comment]
Please update & re-check.

**Comment by capsidimit** [comment]
@ivan-lednev Everything appears to be functioning as expected.
