### ISSUE TITLE
Moving tasks using week planner fails if the (future) daily note does not exist, but week planner-view is updated (incorrectly)

### ISSUE THREAD

**Issue by esodesod** [ivan-lednev/obsidian-day-planner#371]
Since changes introduced in 0.17.1 related to "moving tasks from daily notes across days using the weekly planner-view" now tries to actually "move the task" (content), the job fails if the day the task is moved to does not already exist, e.g. moving a task from "today" (2024-02-22) to "tomorrow" (2024-02-23), and the note 2024-02-23 (tomorrow) does not yet exist.

Also, the week planner-view is updated (like the operation was successful), but it actually did not do anything (the task is still in today's note, but the week planner-view shows the task in tomorrow, even though the operation failed).

Personal sidenote (feedback);
- I very much liked the way it was pre-0.17.1 (e.g in 0.16.0), where moving a task in week view (just) updated the scheduled date (changed date after the ⏳-emoji, you know, after adding my fix in #350, as the scheduled emoji added by day planner when moving the task between days was incorrect/still is..), leaving the task and content exactly "where it was", but only updating the scheduled date.
- Additionally (unless changed), I also don't want to create several future daily notes (automatically or using a template) just so I can move the tasks to a future date (as needed, if the task is actually moved to a different file, which needs to exist..), as the template I use for daily notes includes a lot of "other stuff", which is "not suppose to exist" until the day is actually happening. 
- If changed back, I also think this plugin would "play better together" with other task-related plugins (including both plugins "Tasks" and "Dataview"), as they both (can) operate on emoji-level and update the date to reflect the day it's scheduled. We could then update the scheduled date using Tasks or Day Planner, and the effect (and view) would be the same (the scheduled date after the emoji is updated).

I guess it comes down to personal preferences as well, but leaving comments above as feedback. Use it as you like :-). I'm still on "a frozen version of 0.16.0, including my #350 workaround). Guess I can just create a fork, but would love to rather contribute to this one.

**Comment by FeralFlora** [comment]
Came here to see if this had been reported. It also fails when moving tasks back to a date without a daily note, but like you say, incorrectly displays the task as moved. In some cases, it actually duplicated the task as well, in the week planner view.

**Comment by ivan-lednev** [comment]
Please update and re-check.
