### ISSUE TITLE
Navigating in the timeline to next/previous day creates empty notes

### ISSUE THREAD

**Issue by Volkmire** [ivan-lednev/obsidian-day-planner#373]
**Describe the bug**
Navigating in the timeline to next/previous day creates empty notes.

**To Reproduce**
1. Create a daily note for today. Make sure there is no notes for at least one previous/next day
2. Open day planner timeline
3.  Click on next/previous day in the timeline
4. Observe a note being created for every day that had no note previously

**Expected behavior**
Navigation should be separate from modification and should not create any files implicitly.

**Additional context**
I'm trying to use the plugin with daily notes. But, I don't create daily notes each day for the sake of it. I only create a note when there is something to record, so it's normal for my setup to have gaps of several days between them. This allows me to have an assumption that if I see a note - it has meaningful content inside.

Current behavior creates empty notes for each day that you navigate through, which breaks my intuition about how notes are organized.

**Suggestion**
Create a note only when user clicks on "Go to file" (when you click on the date itself) and accepts some popup.
In case where a user wants to create an event for a future date - use scheduled syntax on the last known note, if the note does not exist.

**Comment by ivan-lednev** [comment]
This has been fixed some time ago.
