### ISSUE TITLE
[Feature Request] Make CTRL modifier changeable for moving and resizing time blocks

### ISSUE THREAD

**Issue by jreus** [ivan-lednev/obsidian-day-planner#376]
I use Day Planner together with Page Preview. Page Preview uses the CTRL modifier to enable previewing outgoing links and pages. This also works with Day Planner - where CTRL+hover over a timeblock shows you a preview of the daily note and task it links to. However, this also means that it's impossible to use the CTRL modifier to move and resize time blocks. 

It would be great to have the option to choose the modifier keys, using maybe ALT or SHIFT for group move/resize instead.

**Comment by ivan-lednev** [comment]
Hello, @jreus,

I'll handle this one in one of the next releases. Using modifiers for different task modes was not a good idea, because it's not easy to memorize (at least for me, haha) which modifier does what. I'm planning to add an edit mode picker in the settings panel. What do you think?

**Comment by jreus** [comment]
An edit mode for tasks would be really nice. 

Would that also allow editing the text inside tasks? I find it's a hassle to have to always be switching back and forth between daily notes and the planner view to block out a day. It would be great if all the time blocking work, including defining the tasks, naming them, etc.. could be done in the planner view exclusively.

Having a modal popup editor would also be an option. Similar to what Obsidian Tasks gives you.

**Comment by ivan-lednev** [comment]
By edit mode I meant that there will be a picker for how drag-and-drop affects your tasks, with options like `push all`, `shrink neighbors` etc.

To edit task text, you can use the hover editor plugin:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/1d2b317a-5b0e-498e-b7bd-d5eb4721bbbc)

It's powerful and really well-made, so for now I'm not planning any other edit modals.

**Comment by ivan-lednev** [comment]
Now you can pick edit mode explicitly, without any modifier interference:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/380cd97c-731f-42e5-900e-b9c6aa63f90f)

**Comment by hy4l** [comment]
`Push other blocks` breaks structure of overlapping tasks. It doesn't matter if I have bullet points or task for timestamp. I use W11
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/140013867/c6668310-7270-4d88-bb28-ba9b78c3f7e3)
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/140013867/9bd16fa8-e4b8-4aaf-a49f-53fda9f308ea)
