### ISSUE TITLE
unscheduled item removed when drag-and-drop in the future planner

### ISSUE THREAD

**Issue by khsunny87** [ivan-lednev/obsidian-day-planner#379]
The plug-in is awsome, but still has a comple of issues.

In my future daily note (ex. 2024-05-01)
when I try to drag one of my unscheduled routine (within the note) to the specific time, 
the item just disappeared. It is even removed from the note.

It works normally when I try in the today's note.

**Comment by Lunkle** [comment]
I actually encountered this error too, and i think I know how to fix it

**Comment by Lunkle** [comment]
i made a fix, but im not 100% sure if its a safe fix, although in my experience it works for me

**Comment by ivan-lednev** [comment]
Please update and re-check.
