### ISSUE TITLE
day planner searches outside header section

### ISSUE THREAD

**Issue by Smitty010** [ivan-lednev/obsidian-day-planner#382]
**Describe the bug**
If I have an entry in my daily note that's in a new section below the day planner section. The day planner interprets that as part of the schedule.  In my configuration, "Day Planner" is listed as the "Planner Heading Text".  The problem is that there is another section just below this that may contain time annotated notes.  Time Planner interprets them as part of the day planner entries.  In the example below, the note at 11:46 is interpreted as a schedule item.  It seems like that day planner shouldn't search past the day planner section since the "Today's Notes" section is at the same level
```
## Day planner

## Today's Notes
- 11:46 - Some note 
```

**To Reproduce**
I believe there is sufficient information to reproduce in the description of the problem

**Expected behavior**
Items outside the time planner header section should not be processed

**Screenshots**
These screenshots illustrate the problem:

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/3760075/deca1644-0045-457f-b0db-9f64f9d82c8d)

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/3760075/9e301d2b-0c27-4f5d-a610-1181f793985c)

**Additional context**

**Comment by mariashinoto** [comment]
Same here. 

- It is not limited to other blocks below the time liner block but is in the whole document. 
- Also, list items without task boxes are counted as well (as far as I understood and worked yet, it only counted time blocks listed as tasks)
- It counts tasks with only one time set and gives it an estimated duration.

**Comment by Smitty010** [comment]
The problem is that this is a note with a time showing *when the note was
made* during the day.  It's not a scheduled item.  It seems like day
planner should be limited to the block where the timeblocks are.  It's not
a huge deal for me, mostly an annoyance.

**Comment by mariashinoto** [comment]
Well, it is a big deal, I would say. 

The time blocks showing in the time line should be limited to the time blocks from the section where time blocks are supposed to be written (as set in the preferences).

**That said, I am thankful that people develop and maintain such wonderful plugins!**

**Comment by Smitty010** [comment]
I agree that it should be limited to the section specified.  I'm just
saying that, for me, it's not a show stopper.  I can still use the plugin.

And, I too, am amazed at the amount of time people put into plugins.  My
vault would not work nearly as well without the plugins I have access to.

**Comment by IamPatrickSturgill** [comment]
I have this issue as well, and it is becoming a show-stopper. I'm using thino plugin to create a "neural log" and every time I write something, even if it's bulleted and not tasks, it shows up in my day planner. I tried making a contains section dataview query but that doesn't work either. Are there any work arounds or a way this can be fixed? Thank you for the otherwise wonderful plugin.

**Comment by km-o** [comment]
> I have this issue as well, and it is becoming a show-stopper. I'm using thino plugin to create a "neural log" and every time I write something, even if it's bulleted and not tasks, it shows up in my day planner. I tried making a contains section dataview query but that doesn't work either. Are there any work arounds or a way this can be fixed? Thank you for the otherwise wonderful plugin.

I'm also using Thino and was experiencing the same issue. I worked around it by adding a "Ignore Headers" setting to my forked repository. This setting allows you to specify any header you want to exclude from the timeline. In my case, I've excluded the "Thino" header to prevent tasks below it from appearing.  I'm open to submitting a PR if this approach would be beneficial to others and aligns with the project's direction.

**Comment by IamPatrickSturgill** [comment]
> > I have this issue as well, and it is becoming a show-stopper. I'm using thino plugin to create a "neural log" and every time I write something, even if it's bulleted and not tasks, it shows up in my day planner. I tried making a contains section dataview query but that doesn't work either. Are there any work arounds or a way this can be fixed? Thank you for the otherwise wonderful plugin.
> 
> I'm also using Thino and was experiencing the same issue. I worked around it by adding a "Ignore Headers" setting to my forked repository. This setting allows you to specify any header you want to exclude from the timeline. In my case, I've excluded the "Thino" header to prevent tasks below it from appearing. I'm open to submitting a PR if this approach would be beneficial to others and aligns with the project's direction.

This would be very helpful.

**Comment by urnotjl** [comment]
The problem still exists. 

Any header text or header level won't stop it from tracking lines with a timestamp. 
In this case, wonder what's the purpose of header in general ?

**Comment by nstefan13** [comment]
I can confirm the problem still exists both on mobile and desktop on version 0.21.1

**Comment by michael-afanasiev** [comment]
Thanks for the great plugin, I'm finding it very useful! After recently starting to time-stamp some meeting bullet points, however, I've noticed this issue, and agree with the suggestion of restricting day planner entries to a specific header.

**Comment by harrislop** [comment]
I am using a Pomodoro Timer and keeping logs, but I am encountering the same issue. Due to this problem, I need a separate file or folder for logging. I would appreciate it if you could help solve this. Even if the entire section is searched, I would prefer that only - [ ] task format is considered and not the time format.

**Comment by ivan-lednev** [comment]
Please update and re-check.
