### ISSUE TITLE
Tasks are not added properly on empty day

### ISSUE THREAD

**Issue by kchasiotis** [ivan-lednev/obsidian-day-planner#383]
**Describe the bug**
When creating a new task on an empty day, the task is not added properly. If I restart the app it works. If I had to guess I would say it happened because I installed dataview after the day planner plugin. After uninstalling and reinstalling the day planner plugin, it works properly.

**To Reproduce**
1. Create a new task on an empty day

Logs
```
VM221 plugin:obsidian-day-planner:31095 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'path')
    at $$self.$$.update (VM221 plugin:obsidia…ay-planner:31095:56)
    at update (VM221 plugin:obsidia…day-planner:26096:8)
    at flush (VM221 plugin:obsidia…day-planner:26066:9)
$$self.$$.update	@	VM221 plugin:obsidian-day-planner:31095
update	@	VM221 plugin:obsidian-day-planner:26096
flush	@	VM221 plugin:obsidian-day-planner:26066
Promise.then (async)		
schedule_update	@	VM221 plugin:obsidian-day-planner:26047
make_dirty	@	VM221 plugin:obsidian-day-planner:26323
eval	@	VM221 plugin:obsidian-day-planner:26360
handleMouseEnter	@	VM221 plugin:obsidian-day-planner:31069
﻿```
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'children')
    at t.getSideLeaf (app.js:1:2025424)
    at t.getRightLeaf (app.js:1:2024205)
    at DayPlanner.initTimelineLeafSilently (VM221 plugin:obsidian-day-planner:38612:32)
    at async DayPlanner.onload (VM221 plugin:obsidian-day-planner:38705:5)
```

**Expected behavior**
The task is added to the day

**Comment by ivan-lednev** [comment]
Closing this as stale. I believe this has been fixed some time ago.
