### ISSUE TITLE
DayPlanner timeline empty after new Daily Periodic Note created

### ISSUE THREAD

**Issue by mattmcmanus** [ivan-lednev/obsidian-day-planner#384]
I've run into this every day the last week or two. Obsidian will have been open for a while. I sit down for the day, create my new daily note, and the DayPlanner panel will stay empty until I restart or reload the app. 

1. Create a new daily note (I typically do this with the Action URI plugin, which "Actions for Obsidian uses". I haven't tested this with another way yet)
2. The new note is based on a template with several stock items already in it
3. See that the sidebar is empty

**Screenshots**
![Screenshot--Obsidian--2024-03-05--09 20 31@2x](https://github.com/ivan-lednev/obsidian-day-planner/assets/9383/65a5ae2d-e5b2-474f-8e04-a5bbafae5ef2)

An interesting thing to note, the specific DayPlanner error in the console also appears when reloading or restarting the app...so I'm not sure that's the problem. Maybe it's the interaction between creating a new note with the Actions URI plugin? I'll make tomorrow's note internally to confirm

![Screenshot--Obsidian--2024-03-05--09 27 11@2x](https://github.com/ivan-lednev/obsidian-day-planner/assets/9383/f9976bc7-6fa9-4c18-b62d-022b1a2a9149)

**Comment by mtomas7** [comment]
I second that. Obsidian restart is needed to populate the timeline.

**Comment by rthomae** [comment]
I have the same issue. I never restart my computer, so I have to restart Obsidian every day after I amke the daily note in order to see timeline.

**Comment by Kang-geophysics** [comment]
I really love this plugin. But I think many people have the same problem. So I wish this issue is solved as soon as possible.

Same issue

#369 #372

**Comment by ivan-lednev** [comment]
Hello! 

Please update and re-check.

**Comment by obbardc** [comment]
It works for me, thank you !

**Comment by Kang-geophysics** [comment]
It worked well until 0.19.4. 
I really appreciate your efforts. Thank you!

BTW, after update of 0.19.5., the console error is not solved yet. 
When I open obsidian with opened daily note created before, Day planner works well.
However, when I open obsidian without daily note, Day planner has an additional error such as "_b.call is not a function". 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'children')
    at t.getSideLeaf (app.js:1:2025424)
    at t.getRightLeaf (app.js:1:2024205)
    at DayPlanner.initTimelineLeafSilently (plugin:obsidian-day-planner:48925:32)
    at async DayPlanner.onload (plugin:obsidian-day-planner:48959:5)

Uncaught TypeError: _b.call is not a function plugin:obsidian-day-planner:35398 
    at getScheduledDay (plugin:obsidian-day-planner:35398:111)
    at t (plugin:obsidian-day-planner:8289:22)
    at eval (plugin:obsidian-day-planner:9588:20)
    at l2 (plugin:obsidian-day-planner:9724:193)
    at eval (plugin:obsidian-day-planner:48515:51)
    at sync (plugin:obsidian-day-planner:34525:22)
    at Array.eval (plugin:obsidian-day-planner:34536:9)
    at set2 (plugin:obsidian-day-planner:34484:35)
    at eval (plugin:obsidian-day-planner:47175:13)
    at eval (plugin:obsidian-day-planner:47147:7)
```

**Comment by kin30528** [comment]
@ivan-lednev 
I'm guessing it's not a version problem, 
the Task timeline display error when I automatically update 0.20.2 in ob.

But when I manually download 0.20.1 and replace the original files, the timeline is displayed correctly, and I try to download 0.20.2 again and replace it manually, it is still displayed correctly. 

I'll leave a comment if I find new anything. Hope it can be some help. For the time being, this problem can probably be solved by manual download and replace old files!

**Comment by ivan-lednev** [comment]
Hey, @kin30528, could you update and re-check?

**Comment by kin30528** [comment]
> 嘿， @kin30528，您可以更新並重新檢查嗎？

@ivan-lednev thank you, its working, wonderful~~:D
