### ISSUE TITLE
[Feature request] Sort tasks by time in daily note after moving in timeline

### ISSUE THREAD

**Issue by Gelio** [ivan-lednev/obsidian-day-planner#386]
Hey! Thanks for this great plugin which I use daily!

One feature I would appreciate is adding a way to sort tasks by their time after altering the day timeline.

I see there is some code for it already in https://github.com/ivan-lednev/obsidian-day-planner/blob/6bc7d6f993754c6f5c0dc24f8600190cadb7788f/src/mdast/mdast.test.ts#L56-L70 but looks like that's commented out and not working. This code correctly explains what I want to achieve - after moving a task in the day planner timeline, I would love it if it was also moved in the markdown file, so the task list in the file would be chronological.

I can also help out with this feature if you let me know which pieces of code I should look into. I haven't contributed to Obsidian plugins yet, and I am a frontend engineer and I hope I can help out 🙂

**Comment by ivan-lednev** [comment]
Hello, @Gelio,

To sort tasks you'll need to update `src/service/plan-editor.ts`. After every write to the plan, we need to
1. grab the first block under the planner heading
2. parse it with `mdast-util-from-markdown`. An abstract tree is easier to manipulate than an array of lines, and we can have subtasks, so we need this
3. re-order top-level list items
4. serialize it back to markdown and replace document contents

mdast-util-from-markdown handles Obsidian-flavored markdown well, but to convert it back, you can grab this utility that fixes some format discrepancies: `src/mdast/mdast.ts`.

Let me know if you have any other questions!

**Comment by Gelio** [comment]
Hey @ivan-lednev, thanks for providing a list of steps to do, as well as code to consume. That is really helpful!

So far I have noticed that updating the task in the file after moving it in the timeline is done with the following function

https://github.com/ivan-lednev/obsidian-day-planner/blob/2a5e8fb7b9c1e0a7e5c706dd77b4b07bb228e32f/src/service/plan-editor.ts#L134-L148

which uses plain string manipulation. Moreover, as far as I can tell, `mdast-util-from-markdown` is not used in the project so far.

I believe the place I should modify to the very basic case of updating a single file when moving tasks inside of it, is:

https://github.com/ivan-lednev/obsidian-day-planner/blob/2a5e8fb7b9c1e0a7e5c706dd77b4b07bb228e32f/src/service/plan-editor.ts#L85-L95

I will see what I can do. I believe it will take me some time to experiment with modifying the file on the AST level. I'll share updates when I make more progress. Feel free to take over this feature if you feel like you can get it done soon

**Comment by Gelio** [comment]
I finally had the time to get this done. I came up with a solution that I am happy with and works well, to me.

Take a look at #436
