### ISSUE TITLE
Not working on iOS after upgrading

### ISSUE THREAD

**Issue by zeitchef** [ivan-lednev/obsidian-day-planner#388]
Plugin is enabled, but there are no options in the command palette. Desktop working fine.

**Comment by ivan-lednev** [comment]
Hello, @zeitchef,

Please update and re-check. I don't have an iOS device to test the fix, but I'm almost sure this is because I used `requestIdleCallback`, which is not available in iOS Safari, and I didn't add a shim to account for that.

**Comment by zeitchef** [comment]
Thanks @ivan-lednev, updated but now I just get a notification saying the plugin failed to load

![IMG_0099](https://github.com/ivan-lednev/obsidian-day-planner/assets/6670659/d979b177-4ed0-43b8-8201-f45da62a6891)

**Comment by ivan-lednev** [comment]
🤔 It's hard to figure out what's wrong without a stack trace or an iOS device at hand. I'm going to have to find a person with an iPhone and harass them. In the mean time, marking this as `help wanted`.

**Comment by showaykerker** [comment]
same here. Is there any thing I can help with?

**Comment by ivan-lednev** [comment]
I need to see where the error is coming from. For this you'll need to connect your iPhone to a Mac and attach Safari debugger to the mobile Obsidian app. Once you do so, you'll see console output on your Mac. 

It's described here: https://capacitorjs.com/docs/vscode/debugging#use-safari

**Comment by showaykerker** [comment]
<img width="990" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/19175003/c5926f7e-3856-4531-a262-2f64aa29c8f6">
Here's the log when I tried to enable the plugin.

**Comment by showaykerker** [comment]
Well actually I also get an error on macOS every time when I launch the app.
But it never really causes a trouble so I simply ignored it.
Here's the log if it helps
<img width="465" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/19175003/9f640dfa-6ee3-46ad-81f0-40e3d11e8272">

**Comment by ivan-lednev** [comment]
Hey, @showaykerker, thanks! This is really helpful! Can you update and re-check?

**Comment by AdamasFR** [comment]
Hey, I can confirm this last update fixes this behavior on iOS 17.4.

**Comment by showaykerker** [comment]
It works now :)
