### ISSUE TITLE
Text not visible on dark mode

### ISSUE THREAD

**Issue by Arnau478** [ivan-lednev/obsidian-day-planner#389]
**Describe the bug**
When using a dark theme, the text is almost invisible (only the completed tasks and links are visible), as the text is black.

**To Reproduce**
1. Install a dark theme
2. Open either the timeline or week planner
3. Almost invisible text is shown

**Expected behavior**
The text should be white.

**Screenshots**
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/61841960/37ae54e9-4808-4222-b924-103749ed3ca8)

**Additional context**
I am using version 0.19.3 of the plugin. Plus, the tasks shouldn't even be black, as I have the "colorful timeline" setting enabled and both colors set (and not to black).

**Comment by Arnau478** [comment]
When I disable the "colorful timeline" setting, the text turns white. When I refresh obsidian, though, the setting is enabled again, and the text is black.

**Comment by ivan-lednev** [comment]
Hello, @Arnau478! Try to update and re-check. I've fixed colorful timeline setting behavior, but I can't reproduce this one:
> When I refresh obsidian, though, the setting is enabled again, and the text is black.

Is it still reproducible? Are there any errors in the console? If you open data.json in `.obsidian/plugins/day-planner`, does the setting get saved there once you toggle it back and forth?

**Comment by Arnau478** [comment]
Okay, the colored timeline is working now. As for the setting, it is now working as expected, I cannot reproduce it anymore... I guess I'll be closing this issue. Thanks!
