### ISSUE TITLE
How to work with Office 365 calendar

### ISSUE THREAD

**Issue by purierca** [ivan-lednev/obsidian-day-planner#395]
I'm sharing this for the others because I couldn't find a how-to and trialed everything forever before finding the solution on how to add my work calendar from Office 365.

**Describe the _feature_**
Work Outlook.com calendars (personal accounts) as well as Office 365 (work) calendars.

**To Reproduce**
1. In Outlook, go to Settings > Calendar > Share Calendar to personal email > Grab the ICS url from the "Accept and open calendar" button in the email received
   - The button URL has this format: `https://outlook.live.com/?rru=addsubscription&url=webcal://outlook.office365.com/owa/calendar/**<calendarID, in the shape of a Token>**/reachcalendar.ics&name=**<the name of the person you shared it to>**`
   - You need to cut out this format:  `https://outlook.office365.com/owa/calendar/**<calendarID, in the shape of a Token>**/reachcalendar.ics`
3. Go to Day Planner plugin settings, plug either ICS url as a new calendar
4. ???
5. Profit

**Expected behavior**
You should now have your work calendar from Office 365 alongside anyother calendar or tasks that you have setup in the plugin options. Note that any other option to share the calendar in Office 365 (for example, publish a calendar) WILL NOT WORK.

**Additional context**
For those trying to integrate even more with Obsidian <> Office 365, I also use the MS To-do sync plugin, installed via BRAT. However, to add MS To-do to the calendar view, you still need to do it from Outlook (if you want to block out time that you colleagues can see), otherwise use the Tasks plugin to show them in the Day Planner, but your colleagues won't see that time as blocked for tasks. It's a personal choice :)

**Comment by ivan-lednev** [comment]
Hey, @purierca,

have you tried the link in the readme? This one: https://support.microsoft.com/en-us/office/introduction-to-publishing-internet-calendars-a25e68d6-695a-41c6-a701-103d44ba151d?ui=en-us&rs=en-us&ad=us

I followed it and it worked. Here's the relevant part:
> Under the settings in Outlook on the web, go to Calendar > Shared calendars. Choose the calendar you wish to publish and the level of details that you want others to see.

Here's how it looked on my web-outlook:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/400f3048-4ac4-4c4a-be18-89b46cb08b3b)

**Comment by ivan-lednev** [comment]
Also check out the updated readme part: https://github.com/ivan-lednev/obsidian-day-planner?tab=readme-ov-file#where-to-get-an-outlook-link

Is that more helpful?

**Comment by purierca** [comment]
Hi both, thanks a lot for the comments; I had seen the official Outlook one, not the new readme (which is great btw).
A quick note on this, for my part the ICS link using the publish function didn't work, that's why I had to cut-out another link from the invitation received by email when sharing to my personal email.

It might just be due to some random limitation from my organization; it could be useful to mention it as another way to get Day Planner to work if all else fails?

**Comment by ivan-lednev** [comment]
Added a link to this issue as an alternative way to get a link: https://github.com/ivan-lednev/obsidian-day-planner?tab=readme-ov-file#alternative

**Comment by dubaaron** [comment]
Yeah, on my org's Outlook / Office 365 setup, the "Shared Calendars" sub-tab under settings is not even there; nor is the alternative "Settings > Calendar > Share Calendar to personal email"

... guess my calendar's just too locked down to use that particular integration :(  Still a very cool plugin, though, thank you. : )
