### ISSUE TITLE
Feature Request: Configuration option to silence release notes display

### ISSUE THREAD

**Issue by zeitchef** [ivan-lednev/obsidian-day-planner#399]
I would appreciate a configuraton option to silence the release notes when updating the plugin. Every major plugin provides this, and you could easily link to release notes from the settings.

For example, this is the first option in Excalidraw:
![Screenshot 2024-03-17 at 23 05 23](https://github.com/ivan-lednev/obsidian-day-planner/assets/6670659/30f5231a-8141-48dd-81ed-bbb6fb6500ea)

Thanks for your consideration.

**Comment by ivan-lednev** [comment]
Hey, @zeitchef, please update and re-check.

**Comment by zeitchef** [comment]
Thanks @ivan-lednev - I'm able to toggle the setting just fine. The code looks fine so I expect it will work, but the real test will come when I update again ;-) Thanks!
