### ISSUE TITLE
Cannot move task scheduled with tasks in Week Planner

### ISSUE THREAD

**Issue by lboller** [ivan-lednev/obsidian-day-planner#403]
**Describe the bug**
Cannot move task scheduled with tasks in Week Planner

**To Reproduce**
1. Schedule a task using the Tasks plugin (untimed)
2. Open Weekly Planner
3. Try to drag task to a new day

**Expected behavior**
Task moves to a new day

**Screenshots**

**Additional context**
Here's the error output in the developer console:

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/1630748/e147a48c-7b28-41b9-b362-7568314fe539)

**Comment by ivan-lednev** [comment]
Please update and re-check.
