### ISSUE TITLE
Make unscheduled tasks section height configurable

### ISSUE THREAD

**Issue by Ash-Shy** [ivan-lednev/obsidian-day-planner#405]
**Describe the bug**
I can't find the option of "Unscheduled tasks height limit"

**To Reproduce**
1. open the setting，this is version 1.16
![6b861422e997619bc9425684fbbb270](https://github.com/ivan-lednev/obsidian-day-planner/assets/162557030/bf04cb6f-5319-4f2d-999f-1c795914e33a)

**Expected behavior**
Not being able to modify the height makes my usage space very limited, and opening the perimeter view also takes up a considerable amount of space.

**Screenshots**

**Additional context**
nothing

**Comment by ivan-lednev** [comment]
Available with drag-and-drop since 0.21.0
