### ISSUE TITLE
Summer time bug?

### ISSUE THREAD

**Issue by HHMathewChan** [ivan-lednev/obsidian-day-planner#407]
**Describe the bug**
After UK enter summer time, the timeline does not show the task correctly in time, all events shift back one hour later.

**To Reproduce**
In UK, after enter the summer time.
1. open the daily note on today's date
2. create an unordered list item — 09:20 - 09:40 test

**Expected behavior**
The timeline will show a time block from 09:20 to 09:40 with a description "test"

**Screenshots**
<img width="1920" alt="SCR-20240331-iqwg" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/105818584/7a3c1d56-70a3-4534-a77f-9968559011f8">

**Comment by mateocovacho** [comment]
+1 same thing happened, created task:
- [ ] 08:30 - 08:45 New item
and shows at 
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/93396088/8fea39dd-f7f5-4c43-b490-6e01955e7a2e)

**Comment by hezronh** [comment]
Having the same issue, was looking for a solution. Hopefully soon enough.

**Comment by ivan-lednev** [comment]
Duplicate of #309

**Comment by fleeflonc** [comment]
desperately seeking resolution for this issue
