### ISSUE TITLE
iOS: timeline refresh button doesn't work; settings don't get saved

### ISSUE THREAD

**Issue by duxswhatdux** [ivan-lednev/obsidian-day-planner#408]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ivan-lednev** [comment]
Hello, @duxswhatdux,

I don't have an iOS device to debug this, so marking this as `help wanted`.

**Comment by ivan-lednev** [comment]
Seems like a duplicate of #519
