### ISSUE TITLE
Feature request: Optional end time (or duration) for task

### ISSUE THREAD

**Issue by ralfw** [ivan-lednev/obsidian-day-planner#41]
Currently a list of tasks like

```
- [ ] 10:00 Task A
- [ ] 11:00 Task B
- [ ] 15:00 Task C
```

leads to a plan like this:

![image](https://user-images.githubusercontent.com/132662/101464156-9249d580-393e-11eb-875f-f449a84e4161.png)

![image](https://user-images.githubusercontent.com/132662/101464176-9aa21080-393e-11eb-9eb1-0a4bf7c27b3b.png)

`Task B` seems to take up time from 11:00 until 15:00. And Task C does not have a duration at all.

But in my experience tasks don't just take up all the time until the next task. Maybe `Task A` is just a short phone call, and `Task B` is sending an email. I still would like to plan those tasks across the day. But they don't need to be consecutive and not take up all the time until the next task.

My workaround currently is:

```
- [ ] 10:00 Task A
- [ ] 11:00 Task B
- [ ] 11:45 -
- [ ] 15:00 Task C
```

I insert a dummy/no-name tasks to set an end time. At least in this view it improves the depiction:

![image](https://user-images.githubusercontent.com/132662/101464714-4a777e00-393f-11eb-9910-05640fb1b649.png)

But what I'd like to be able to is set not only an explicit start time, but also an end time, e.g.

```
- [ ] 10:00-10:15 Task A
- [ ] 11:00-11:45 Task B
- [ ] 15:00-16:30 Task C
```

Or define the duration of a task, e.g.

```
- [ ] 10:00-15min Task A
- [ ] 11:00-45min Task B
- [ ] 15:00-1h30min Task C
```

**Comment by ppmw99** [comment]
Excellent suggestion.   I would love this feature to be added to my daily planning.

**Comment by vishae** [comment]
This would be an amazing feature.

**Comment by balint-bg** [comment]
Related, but not exactly the same feature request: https://github.com/lynchjames/obsidian-day-planner/issues/109 . Maybe the two can be looked into at the same time, there does seem to be some overlap.

**Comment by flaper87** [comment]
Would *love* to have this. I don't track everything I do so I would like to be able to add an end time to some of the tasks so that I know when they started/finished without having to add new generic tasks with a start time

**Comment by ivan-lednev** [comment]
Done in 0.7.0
