### ISSUE TITLE
ICS Calendar Links don't work on Mac/iOS

### ISSUE THREAD

**Issue by SardonicSystems** [ivan-lednev/obsidian-day-planner#412]
**Issue**
I am attempting to connect two calendars, one from google, one from MS Office 365.
Both links can be entered into a browser, and the ICS file can be downloaded, so I do not believe it is a permissions or network issue.
The calendar sync works on mobile (iOS iPhone app, on same Wi-Fi as desktop), but not on the desktop app (Windows 11). The events show up in the day planner view on my mobile app, but not on the desktop app.

I've disabled windows firewall, no change. I've attempted to remove and re-add the links, uninstall and re-install obsidian, and try on a new vault. All of these failed on the desktop to resolve the issue.

**Screenshots**
Settings page, showing the .ics url links I've used:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/34879622/51f9f91c-0f5c-4c49-bef3-f77d8fbf5997)

Console output, after links are entered and sync begins
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/34879622/5aa6f665-e9c8-4e33-8d57-fe661082a580)

Desktop view of the day planner:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/34879622/99177f59-7064-412e-a172-49d47f3d896e)

**Comment by Juneddo** [comment]
Perfectly same with me. Works well in the mobile obsidian, but not in the mac obsidian. :(

**Comment by elensix** [comment]
I am also having this issue! The Google Calendar connection worked when I first installed and enabled the plugin, but after I disabled and reenabled it (then uninstalled and reinstalled), it no longer was syncing. Haven't looked at the mobile obsidian tho!

**Comment by Juneddo** [comment]
Here is my case about operation environment for remote calendar sync.

- iOS Obsidian + Google calendar : work
- iOS Obsidian + iCloud calendar : not work
- Mac Obsidian + Google calendar : not work
- Mac Obsidian + iCloud calendar : not work

And I'm using obsidian through iCloud. (I mean my obsidian vault has been saved in iCloud.)

**Comment by ivan-lednev** [comment]
I don't have an iOS device or a Mac, so I'd need some help with that one...

**Comment by Somniosus1345** [comment]
Hey there,

I have had the same problem but was able to solve it by exchanging the "webcal" at the beginning of the ICS Link for iCloud calendar with "https" and now all I can see the sync calendars both on my Mac as well as iOS.

Cheers

**Comment by Juneddo** [comment]
> Hey there,
> 
> I have had the same problem but was able to solve it by exchanging the "webcal" at the beginning of the ICS Link for iCloud calendar with "https" and now all I can see the sync calendars both on my Mac as well as iOS.
> 
> Cheers

Wow. It works! Really appreciate it!!!
Perfectly works but not in the iphone.
(Since the webcal URL works fine on iPhone, I tried adding both the webcal and https URLs, but it seems that neither of them works when both are added.)
Anyway I don't use obsidian in iphone that much, so in my case the problem has been solved perfectly.
Thank you so much.

**Comment by ivan-lednev** [comment]
Since 0.25.0 the plugin automatically replaces `webcal://` with `https://`.
