### ISSUE TITLE
Exceptions to recurring events Microsoft 365 still showing in timeline

### ISSUE THREAD

**Issue by neutron246** [ivan-lednev/obsidian-day-planner#418]
**Describe the bug**
If I delete a single occurrence of a recurring event in Microsoft Business 365 it is still shown in the timeline. I create the events in thunderbird, so I am unsure if that has something to do with it.

**Possible cause**
I had a look through the ICS file and found one line which seems to define the exceptions to recurring tasks. Possibly, this is not being recognized.
EXDATE;TZID=Romance Standard Time:20240405T114500,20240501T114500

Here is the whole block:
BEGIN:VEVENT
RRULE:FREQ=WEEKLY;UNTIL=20250404T094500Z;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR;WK
 ST=SU
EXDATE;TZID=Romance Standard Time:20240405T114500,20240501T114500
UID:040000008200E00074C5B7101A82E008000000003F4F17A3F17EDA01000000000000000
 0100000007A311FFAC1405A4DAC057696E03E1030
SUMMARY:Mittag
DTSTART;TZID=Romance Standard Time:20240402T114500
DTEND;TZID=Romance Standard Time:20240402T131500
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20240405T024604Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MICROSOFT-REQUESTEDATTENDANCEMODE:DEFAULT
X-MICROSOFT-ISRESPONSEREQUESTED:FALSE
END:VEVENT

**Comment by gr2mx** [comment]
I can confirm the bug occurs for me as well.

**Comment by aahventures** [comment]
Copying my comment from #431 

I took a quick look and it seems like a pretty simple fix. I hacked my local main.js by excluding any dates in icalEvent.exdate (exclude or exception dates), in addition to excluding recurrence overrides and it seems to fix it. Apparently there is another iCal property called EXRULE also, which should be taken into account if we want to be 100% correct, see: https://www.kanzaki.com/docs/ical/exrule.html.

If I have time, I'll try to open a PR. Otherwise I'd be happy if someone else took my findings and opened a PR too.

**Comment by jenpritchard** [comment]
> Copying my comment from #431
> 
> I took a quick look and it seems like a pretty simple fix. I hacked my local main.js by excluding any dates in icalEvent.exdate (exclude or exception dates), in addition to excluding recurrence overrides and it seems to fix it. Apparently there is another iCal property called EXRULE also, which should be taken into account if we want to be 100% correct, see: https://www.kanzaki.com/docs/ical/exrule.html.
> 
> If I have time, I'll try to open a PR. Otherwise I'd be happy if someone else took my findings and opened a PR too.

@aahventures  Can you share what exactly you changed in main.js?

**Comment by aahventures** [comment]
@jenpritchard something like this:
```js
function hasRecurrenceOverride(icalEvent: ical.VEvent, date: Date) {
  const dateKey = moment(date).format(originalRecurrenceDayKeyFormat);
  const hasRecurrence = icalEvent.recurrences && Object.hasOwn(icalEvent.recurrences, dateKey);
  const hasExdate = icalEvent.exdate && Object.hasOwn(icalEvent.exdate, dateKey);
  return hasRecurrence || hasExdate;
}
```
Function can probably be renamed. And removed early exit:
```js
if (!icalEvent.recurrences) {
  return false;
}
```

**Comment by jenpritchard** [comment]
Thanks @aahventures !  I finally had time to tinker with this, and although I had to make a slight tweak, it now works fantastically.
I had to change the "icalEvent: ical.VEvent, date: Date" bit to just "icalEvent, date" (although I changed it to date2). Additionally, I swapped our your dateKey calculation to match the original one. With those changes, I was off and running; thanks again!

Full updated hasRecurrenceOverride function below:

```
function hasRecurrenceOverride(icalEvent, date2) {
  const dateKey = (0, import_moment19.default)(date2).format(originalRecurrenceDayKeyFormat);
  const hasRecurrence = icalEvent.recurrences && Object.hasOwn(icalEvent.recurrences, dateKey);
  const hasExdate = icalEvent.exdate && Object.hasOwn(icalEvent.exdate, dateKey);
  return hasRecurrence || hasExdate;
}
```

**Comment by aahventures** [comment]
Great, my hack looks similar to yours, but I posted what the changes would be in Typescript. Looks like we might be getting a fix soon.
