### ISSUE TITLE
Empty event name in remote calendar makes week view unresponsive

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [ivan-lednev/obsidian-day-planner#430]
## Description

When an event without a name is in a remote calendar, it (and events on or after that day) are not rendered in the week planner view and freezes the plugin.

## Screenshots:

Week Planner view (becomes unresponsive when loading this week)
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/84215197/69258897-c0b2-408d-8bbc-b73b086fad54)

Events in Google calendar
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/84215197/a0e1a168-9bae-4a16-8719-5148d6a1659d)

## How to reproduce
1. Create an event without a name in Google Calendar (not tested on other remote calendar options)
2. Open the week planner view
3. Navigate to the week with the event

## Expected behavior

The event still appears with a placeholder name like "(no title)". Following events are not affected.

## Console Error

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/84215197/3b0ddc58-aae8-4289-b6a0-f350040db533)

**Comment by ivan-lednev** [comment]
Fixed in 0.21.1
