### ISSUE TITLE
Plugin becomes unresponsive, probably due to ical scheduled tasks

### ISSUE THREAD

**Issue by kjarnot** [ivan-lednev/obsidian-day-planner#432]
**Describe the bug**
I've been encountering an issue where the Day Planner plugin becomes unresponsive.  The timeline doesn't change, task notifications are not displayed, settings toggles don't change when clicked, etc.

I checked the developer console and saw that an exception was being thrown in getNotificationKey(), where task.location.path was undefined:

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/7809688/09688eba-bbc6-48be-a82e-8e37c19a143c)

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/7809688/15375408-69dd-4956-9c5e-be4b3f5ef845)
 
I managed to catch the exception in the debugger, and when I inspected the task variable, I saw that it did not have a member named location (I think a TaskLocation), hence the exception.  I did notice that it was an icalEvent (from an Office 365 Exchange remote calendar).

**To Reproduce**
(this is a guess)
1. Configure an external remote calendar
2. Start Obsidian
3. At some point (when scheduled task begins, I believe), an exception is thrown and Day Calendar becomes unresponsive 

**Expected behavior**
Plugin continues to operate correctly

**Additional context**
I think the bug may be in the icalEventToTask() function, as location is never set.

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/7809688/c44f6925-1778-46e9-a6a5-667ecf31dc7b)

**Comment by ivan-lednev** [comment]
This should be fixed in the latest version. Please re-open it if the issue shows up again.
