### ISSUE TITLE
Calendar Events without a Location Error Out

### ISSUE THREAD

**Issue by sepatel** [ivan-lednev/obsidian-day-planner#438]
**Describe the bug**
If you have a calendar event which does not have a location populated, it causes an error when initializing the day planner for the day. Unsure if this is the root cause for the day planner dying and causing the sidebar to no longer progress and reminders to never go off anymore but it seems likely as it happens pretty regularly and with 3 calendars integrated into it there are bound to be plenty.

Looks like the code is tracked down to
```
function getNotificationKey(task) {
  return `${task.location.path}::${task.startMinutes}::${task.durationMinutes}::${task.text}`;
}
```
Where the `location` property of task is undefined. Thus obtaining a path from it is not possible.

**To Reproduce**
Setup multiple google calendars. Ensure that an event taking place right now (or about to take place probably) does not have a location property on it.

**Expected behavior**
I should still get a notification about this being a task to work on next.

**Additional context**
Task notification settings are turned on. Pasting screenshots to show the settings as it is likely that it is being triggered because of a non-default setting.
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/190585/871b136d-1c9f-456c-ac8f-34325000d83c)

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/190585/387f3a21-92c9-40b6-9c0f-537e99ad916e)

**Comment by aahventures** [comment]
That's awesome you found the root cause as I think I am also affected by this. Do you plan to open a PR for it?

**Comment by sepatel** [comment]
Oh sure I can do that. Unsure why the PR itself didn't cross my mind but yeah I can easily fix this and create a PR for it.
