### ISSUE TITLE
Unblock PRs / more maintainers

### ISSUE THREAD

**Issue by aahventures** [ivan-lednev/obsidian-day-planner#441]
Hi @ivan-lednev,

Thank you for your hard work. I know you do this on your free time and I really appreciate that.

There are a couple of bugs that hamper our workflows, and is preventing this plugin from becoming a daily driver for us. Recently, and specifically:
1. https://github.com/ivan-lednev/obsidian-day-planner/pull/439
2. https://github.com/ivan-lednev/obsidian-day-planner/pull/435

Is it possible to add any other active contributors as a maintainer for this repo, so they can approve them? Do you have any other suggestions for unblocking PRs?

Thanks.

**Comment by sepatel** [comment]
bump

**Comment by ivan-lednev** [comment]
Hello, @aahventures. Those fixes just got released. Try updating the plugin.

**Comment by aahventures** [comment]
Great thanks @ivan-lednev!
