### ISSUE TITLE
[Feature Request] Options for controlling what happen when various interface elements are clicked on

### ISSUE THREAD

**Issue by intervolver** [ivan-lednev/obsidian-day-planner#450]
Currently, when "go to previous day", "go to next day", and several other elements are clicked on, they open the corresponding note in a new tab.  This behavior is almost always undesirable and depending on setup, shadowing other methods of getting to that day.  The Day Planner timeline automatically moves around to whatever day has been edited, creating a hassle as every click back opens a new tab.  The ability to toggle this functionality per instance that it appears is highly desirable.  

Thank you for your time, 
iv

**Comment by ivan-lednev** [comment]
This has been fixed some time ago.
