### ISSUE TITLE
[Feature Request?] Show generated tasks in calendar views

### ISSUE THREAD

**Issue by taiwithers** [ivan-lednev/obsidian-day-planner#452]
It appears that only tasks which are explicitly written as `- [ ] task goes here` are included in the calendar views. Tasks which are "generated" via including a section of another note (e.g. with `![[Title#Heading]]`) do not appear, and neither do those from [Tasks Plugin queries](https://publish.obsidian.md/tasks/Queries/About+Queries). 

This is probably a pretty difficult fix since I imagine this plugin reads the source files rather than the "compiled" output, but it would be incredibly helpful for global task management since it would allow for tasks to be stored outside of the daily note itself.

**Comment by taiwithers** [comment]
There's [some documentation](https://github.com/ivan-lednev/obsidian-day-planner?tab=readme-ov-file#showing-events-from-other-files-in-your-vault) on a similar situation, but imo this is different

**Comment by ivan-lednev** [comment]
Hello. This is close to impossible to implement, so I'm closing this...

For now, the docs you linked to describe the only way to gather tasks from sources other than daily notes.
