### ISSUE TITLE
Unable to select week in weekly view on mobile

### ISSUE THREAD

**Issue by zhang-962464** [ivan-lednev/obsidian-day-planner#458]
cannot freely select which week to view in the weekly view. It only displays the current week's schedule, but I want to review my previous plans.

**Comment by ivan-lednev** [comment]
You can switch the week with the control buttons in the upper right corner:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/e7403096-6794-4d7f-8fb8-a1bf985f64bb)

**Comment by zhang-962464** [comment]
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/80077506/9f627789-b183-4a43-a245-5462a6e018f7)
但是我并没有这个选项，

**Comment by gunererd** [comment]
![20240601_20h04m06s_grim](https://github.com/ivan-lednev/obsidian-day-planner/assets/5788729/d5bdd572-61a1-4bba-8b55-e43579939fc2)
I don't have those control buttons either.

**Comment by ivan-lednev** [comment]
Okay, @zhang-962464, seems like you're using iOS, right?

@gunererd, is this the default theme? Looks like your theme hides the buttons.

**Comment by gunererd** [comment]
@ivan-lednev here I disabled all plugins and set default theme then restarted obsidian but still no luck with those buttons.

![20240604_23h12m30s_grim](https://github.com/ivan-lednev/obsidian-day-planner/assets/5788729/e8f81e43-a841-480b-92ff-e3127055b433)

**Comment by ivan-lednev** [comment]
@gunererd, make sure this option is enabled:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/d9152eb7-d8be-46fc-b1aa-e5ffe77b5b2a)

**Comment by gunererd** [comment]
@ivan-lednev yep that was the case. I can see buttons now, sorry for inconvenience and thank you for your time.

**Comment by ivan-lednev** [comment]
In 0.25.0 there is a side bar in the multi-day view, that always stays visible.
