### ISSUE TITLE
Uncaught Error task.text.split is not a function and freezing day planner timeline when using remote ics calendars

### ISSUE THREAD

**Issue by ckpinguin** [ivan-lednev/obsidian-day-planner#465]
**Describe the bug**
Day Planner Timeline freezes after trying to get remote ics calendar.

**To Reproduce**
1. Go to Day Planner Timeline
2. Click on 'Manually sync with remote calendars' or wait some time
3. Click the „left“ or „right“ icon in Day Planner Timeline => Daily notes still switching, but Timeline displays stays frozen, even options overlay not working anymore.
4. See error in console:
`[ task.text.split is not a function](plugin:obsidian-day-planner:43772 Uncaught (in promise) TypeError: task.text.split is not a function)`

**Expected behavior**
Day Planner Timeline component should not freeze even when there are problems with remote calendar sync

** Workaround **
Remove all remote calendars and restart Obsidian, which is kind of not an option

**Comment by ckpinguin** [comment]
I did some testing with all my calendar sources separately: The root cause of my specific problem was that one of my 3 Proton Calendar exports had some quirky repeating tasks that were imported there via Outlook ICS file ... I deleted that calendar and the other 2 still work flawlessly. I still think that erroneous ICS sources in the component should be handled so that it is not freezing, but consider the priority low from my point of view.

**Comment by ivan-lednev** [comment]
Please re-check with the latest plugin version.
