### ISSUE TITLE
Note and view durations are inconsistent

### ISSUE THREAD

**Issue by Gavoid123** [ivan-lednev/obsidian-day-planner#466]
**Describe the bug**
View and note durations do not match when you click Create

**To Reproduce**
1. Click Create anywhere in the Timeline view
2. Check the time on your notes

**Expected behavior**
Their time should be the same

**Screenshots**
https://github.com/ivan-lednev/obsidian-day-planner/assets/64102271/7d72a288-b240-4de2-af7c-04e64c4ea268

**Comment by ivan-lednev** [comment]
This has been fixed in 0.23.2. Now if you click on a timeline, the task gets created with the configured default duration.
