### ISSUE TITLE
Cannot make the dataview filter work

### ISSUE THREAD

**Issue by NicolasReboule** [ivan-lednev/obsidian-day-planner#469]
Hello,
So I tried to include tasks from other files to the day planner but I can't manage to make it work.

I followed this comment but it still doesn't work

https://github.com/ivan-lednev/obsidian-day-planner/issues/410#issuecomment-2032550108

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/72016245/7e614830-0f88-4831-b882-41f5e6290372)

If anyone can help me understand, I'd be grateful.

**Comment by ivan-lednev** [comment]
@NicolasReboule, you need to add the date to each task individually. Right now there is no way for the day planner to know that, say, Test2 should happen on 2024-06-06. So, using the tasks plugin, scheduling for this day will look like this:
```md
- [ ] Test2 ⏳2024-06-06
```

**Comment by ivan-lednev** [comment]
Closing this one as stale.
