### ISSUE TITLE
Markdown template for daily plan

### ISSUE THREAD

**Issue by briankosw** [ivan-lednev/obsidian-day-planner#47]
Is there a way to specify a template for each daily plan?

**Comment by H3liumBoy** [comment]
Hey hey. I love the plugin but I have a question that I think relates to this question.

Would it indeed be possible to alter the default template that is inserted in a note in command mode? So you can just paste your own schedule template into a note at the start of the day?

Or would it be possible to just add a custom template schedule to your daily note, and then _automatically_ link it to the daily planner once a daily note is created? I'd like to have both planner + daily note in one note. So I was thinking, 'perhaps block referencing?' But there might just be an easier way. 

Thank you in advance for any help

**Comment by jckytf** [comment]
I'm a new user and just found out. 
You can modify the default template by opening the main.js in the plugin folder.
And on line 45 const DAY_PLANNER_DEFAULT_CONTENT = ``
has the default template in there.

**Comment by barbosarp** [comment]
+1. This would be a nice way to link it to the Calendar plugin.

**Comment by d3v0ps** [comment]
+1 to this. If it doesn't get developed soon I can try to develop by myself. @barbosarp how does this feature relate to the Calendar plugin?

**Comment by barbosarp** [comment]
@d3v0ps , what I wanted is a daily planner that would get info from the daily notes (from Calendar plugin) and display it in a dashboard. For example, a section with tasks due today, other with tasks overdue, tasks due the next days, etc.

**Comment by ivan-lednev** [comment]
This is handled by the daily notes plugin now.
