### ISSUE TITLE
Tasks from Community Tasks Plugin not showing in calendar

### ISSUE THREAD

**Issue by cuniman** [ivan-lednev/obsidian-day-planner#479]
I am using the most current version of the Day Planner community plugin in the most current version of Obsidian. I am using the tasks emoji format from the Tasks community plugin (i.e., I'm not using the format dataview. In line with your documentation, I've tried tagging my tasks with the #tasks hashtag and I still don't see my tasks in the Day Planner calendar.  I don't see any filter option for Day Planner where I can insert the tasks tag (as I saw in your documentation, which it appears is now a bit out of date).  Please tell what to do to have my tasks (whether contain a day-of-day or not) to show up in the Day Planner calendar.  Thanks.  Charlie

**Comment by ivan-lednev** [comment]
Can you share a screenshot of your `obsidian-tasks` settings screen, as well as this timeline filter?
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/5fdb5d73-61a4-48d2-9436-50778b08dec6)

**Comment by ivan-lednev** [comment]
Closing this as stale.
