### ISSUE TITLE
Automatic text contrast colors don't work for color overrides in blocks

### ISSUE THREAD

**Issue by bogdansalyp** [ivan-lednev/obsidian-day-planner#481]
# Inconvenience

Daily Planner view uses `var(--text-normal)` which is usually dark for light mode and dark for light mode.

Therefore there's an issue of using darker colors override for time blocks - dark text looks ugly on them:

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/18697399/d1b64f73-2e0e-4519-9677-8f8eccc3ec01)

The same issue exists in dark mode.

# Solution

For Day Planner users should be able to override not only light/dark timeblock background color but also a text color.

**Comment by ivan-lednev** [comment]
Fixed in 0.25.0.
