### ISSUE TITLE
How can I enter the next day by scrolling the timeline instead of using the arrow next to the date?

### ISSUE THREAD

**Issue by bwnjnOEI** [ivan-lednev/obsidian-day-planner#483]
<img width="326" alt=" " src="https://github.com/ivan-lednev/obsidian-day-planner/assets/16009223/37f03c3f-5c4e-48f9-96a4-733063aea6d3">

**Comment by ivan-lednev** [comment]
Hello, this behavior is not implemented. If you want to submit a feature request, you should go with the corresponding template: https://github.com/ivan-lednev/obsidian-day-planner/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.yaml
