### ISSUE TITLE
Unable to create new events or tasks.

### ISSUE THREAD

**Issue by caperegime0425** [ivan-lednev/obsidian-day-planner#489]
**Describe the bug**
Every time I create a new time block I get a message: "Unable to create document." I'm unable to create new tasks or rename them. 

**To Reproduce**
1. Create a new time block on the timeline by clicking and dragging.
2. Error message pops up immediately.

**Expected behavior**
A new task time block created and the ability for me to change the title and move the block both in the new note created and the time block.

**Comment by ivan-lednev** [comment]
Hey, once you do that, please open the dev tools (`Ctrl + Shift + I`) and share the error message that you see.

**Comment by ivan-lednev** [comment]
Closing this as stale.
