### ISSUE TITLE
Feature Request: option to produce the days 'day planner' 24 hours in advance

### ISSUE THREAD

**Issue by ppmw99** [ivan-lednev/obsidian-day-planner#49]
I love this Day Planner plug in.   One thing that would improve my workflow is if the day planner was created automatically for the next day each day.  This would enable me to plan tomorrow during today (typically I try to do this as my last workday task each day so I can hit the ground running next morning).

**Comment by thePHTest** [comment]
Bump on this feature. I also plan days the night before. Has anyone looked into doing this? I might try to figure it out if I can find the time later.

**Comment by balint-bg** [comment]
Related feature request: https://github.com/lynchjames/obsidian-day-planner/issues/75

**Comment by ivan-lednev** [comment]
Handled in 0.7.0.
