### ISSUE TITLE
Parse timestamps anywhere in the line

### ISSUE THREAD

**Issue by louwelyn-jeremy** [ivan-lednev/obsidian-day-planner#492]
first of all, thank you for your work
i have tried the time ruler plugin, but i think yours is greater for me.
but i have a issue with the tasks plugin.

## Describe the bug
In the tasks plugin i use the string "TODO" to find my tasks.
The problem is that your plugin must find start/end hours in the begenning of the task to find the task
so, i can't use the task plugin modal to set the start/end hours.

What your plugin need:
- [ ] 08:00 - 10:00 TODO This task uses the shorthand format ⏳ 2021-08-29
what i have when i use taskplugin modal to create a task
- [ ]  TODO 08:00 - 10:00 This task uses the shorthand format ⏳ 2021-08-29

## Expected behavior
a way to add strat/end hours AFTER the TODO string.
for exemple:
- [ ] TODO This task uses the shorthand format [DAYPLANNER:: 08:00 - 10:00 ]⏳ 2021-08-29

or a way to add a string to bypass in your regex detection
for exemple if "TODO" is the string to bypass
- [ ]  TODO 08:00 - 10:00 This task uses the shorthand format ⏳ 2021-08-29

will works

**Comment by ivan-lednev** [comment]
Available in 0.23.2
