### ISSUE TITLE
Week planner navigation menu gone if "tab title bar" is hidden

### ISSUE THREAD

**Issue by raphaelquast** [ivan-lednev/obsidian-day-planner#495]
Hey, thanks a lot for your awesome plugin... It really helps a lot to keep me organized!

I just realized the following problem and thought I'll report it...
If the option `Appearance -> Interface -> Show tab title bar` is disabled, there is currently no way to navigate 
weeks in the week-panner since the controls are added only to the title-bar.

Would be nice if the controls are added in such a way that the title-bar can be hidden..
Thanks!

**To Reproduce**
1. Open options
2. Disable `Appearance -> Interface -> Show tab title bar`
3. -> no controls to change weeks

**Comment by ivan-lednev** [comment]
Navigation is always available since 0.25.0.

**Comment by raphaelquast** [comment]
Awesome! Thanks!!
