### ISSUE TITLE
How can I exclude certain #tag content from the filter?

### ISSUE THREAD

**Issue by Jack-BH** [ivan-lednev/obsidian-day-planner#499]
![ex](https://github.com/user-attachments/assets/5ee1ee92-c379-4e1a-9d4e-9002b2e8b454)
"#虎狼之词" is recorded by Thino; I want it not to show in the day-planner, what should I do, "-#Tag" has been used, but it doesn't work.

**Comment by ivan-lednev** [comment]
Hello, try this one:
```
-#tag
```

**Comment by JerryG94** [comment]
> Hello, try this one:
> 
> ```
> -#tag
> ```

It doesn't work

**Comment by ivan-lednev** [comment]
I just checked, and it's working: if a file contains this tag, the tasks from this file are not going to show up in the timeline. What exactly do you mean by 'doesn't work'?

**Comment by Jack-BH** [comment]
figure1:
![image](https://github.com/user-attachments/assets/8b07db76-2bf6-4588-8f3a-47ac1f9a41cf)
figure2:
![image](https://github.com/user-attachments/assets/7da813c0-8764-4899-b05b-d0d4a811c12f)
My purpose is to make the content of Figure 1 not displayed in Figure 2. Can it be done? It seems that as long as there is a timestamp, it will be displayed in Figure 2. I have tried adding the "-#tag" filter, but it does not work.

**Comment by JerryG94** [comment]
> I just checked, and it's working: if a file contains this tag, the tasks from this file are not going to show up in the timeline. What exactly do you mean by 'doesn't work'?

figure1:
![image](https://github.com/user-attachments/assets/8b07db76-2bf6-4588-8f3a-47ac1f9a41cf)
figure2:
![image](https://github.com/user-attachments/assets/7da813c0-8764-4899-b05b-d0d4a811c12f)
Thanks for your reply.My purpose is to make the content of Figure 1 not displayed in Figure 2. Can it be done? It seems that as long as there is a timestamp, it will be displayed in Figure 2. I have tried adding the "-#tag" filter, but it does not work.

**Comment by bayerju** [comment]
I guess you have the task in the daily note for that day? Every task in the daily note is shown right now. The filter is just for the tasks in the dataview. So tasks from different files.

I am thinking about suggesting an option in the settings to have dataview first support, but I did not quite figure it out mysel and I wont have time for it in the next few weeks. But I agree, that the expected behavior is different. For the future it would be helpfull, to have the examples in english. I got your examples this time, but I would have been faster with english tags.

**Comment by ivan-lednev** [comment]
Tags work only at file-level, they're not that granular, but I see what you're trying to do. This is the same as #382

**Comment by JerryG94** [comment]
> Tags work only at file-level, they're not that granular, but I see what you're trying to do. This is the same as #382

Yes, I hope to find a solution to this problem as soon as possible. Thank you very much for your explanation.

**Comment by JerryG94** [comment]
> I guess you have the task in the daily note for that day? Every task in the daily note is shown right now. The filter is just for the tasks in the dataview. So tasks from different files.
> 
> I am thinking about suggesting an option in the settings to have dataview first support, but I did not quite figure it out mysel and I wont have time for it in the next few weeks. But I agree, that the expected behavior is different. For the future it would be helpfull, to have the examples in english. I got your examples this time, but I would have been faster with english tags.

That's great. That would be very helpful.
