### ISSUE TITLE
Failed to load plugin obsidian-day-planner

### ISSUE THREAD

**Issue by jestxfot** [ivan-lednev/obsidian-day-planner#511]
![image](https://github.com/user-attachments/assets/bda75932-987a-4fa8-85f4-e5d55eac6e68)

Literally everything worked during the day

![image](https://github.com/user-attachments/assets/3438037f-a135-4dd7-aeec-96301ae05ac0)

Judging by the error stack, the problem occurs in the obsidian-day-planner plugin for Obsidian. Specifically, the `initTimelineLeafSilently` function raises an error when trying to access the `.children` property.

**Comment by jestxfot** [comment]
### Reason for error: An error occurs in the `DailyNotesFolderMissingError` function when a folder in the daily notes plugin is not found. I fixed this in the settings of the original Obsidian plugin, but I think DayPlanner should more adequately inform the user of this error

As I realized this is what was crashing the plugin, the `initTimelineLeafSilently` error doesn't crash it

**Comment by jestxfot** [comment]
As I realized this is what was crashing the plugin, the initTimelineLeafSilently error doesn't crash it

**Comment by Arc13Tangent** [comment]
> ### Reason for error: An error occurs in the `DailyNotesFolderMissingError` function when a folder in the daily notes plugin is not found. I fixed this in the settings of the original Obsidian plugin, but I think DayPlanner should more adequately inform the user of this error
> As I realized this is what was crashing the plugin, the `initTimelineLeafSilently` error doesn't crash it

Your comment saved my life, thanks a lot!
