### ISSUE TITLE
Feature Request: Task with start and end time

### ISSUE THREAD

**Issue by gala8y** [ivan-lednev/obsidian-day-planner#53]
That would be cool to be able to create tasks in format:
- [ ] 08:00 - 08:30 task name

This would remove need to create extra 'free/break' entries.

**Comment by wwingler** [comment]
This would be super helpful!

**Comment by barbosarp** [comment]
+1

**Comment by ivan-lednev** [comment]
Done in 0.7.0.

**Comment by gala8y** [comment]
Works like charm. Thanks for picking it up.
