### ISSUE TITLE
Outlook calendar display misalignment

### ISSUE THREAD

**Issue by 18745085274** [ivan-lednev/obsidian-day-planner#532]
![Clip_20240902_173835](https://github.com/user-attachments/assets/28ca0b6b-00c4-4a14-a313-f0505194bf53)

The Outlook schedule display is misaligned, but the calendar in Outlook is normal. After sharing the day plan through ICS, each schedule is misaligned

**Comment by ramandv** [comment]
Facing same problem for Google calendar too

**Comment by ivan-lednev** [comment]
@ramandv, @18745085274 please create a dummy calendar with a couple of events that get misaligned like that, and then share the link to the calendar here. This will help me debug the issue.

**Comment by ramandv** [comment]
@ivan-lednev i don't have that problem anymore. Cannot replicate it also.

**Comment by ivan-lednev** [comment]
Closing this as stale then.
