### ISSUE TITLE
Error: Failed to Install Plugin

### ISSUE THREAD

**Issue by aloewright** [ivan-lednev/obsidian-day-planner#533]
**Describe the bug**
When trying to install the plugin from the community plugins section in Obsidian, receiving error "Failed to Install Plugin Day Planner" after multiple attempts/refreshes. 

**To Reproduce**
1. Go to plugin page in Community Plugins in Obsidian. 
2. Click on Install.
3. See error: "Failed to Install Plugin Day Planner"

**Expected behavior**
Should be able to install plugin on latest Obsidian version. 

**Additional context**
Not having issue installing other plugins. Currently using latest version of Obsidian on latest version of MacOS for intel-based Macs. Attempted to fix issue through restart of system and app.

**Comment by ivan-lednev** [comment]
Hello, you can install the plugin now.

**Comment by Fifof-hup** [comment]
Have the same installation issue on a Mac version 12.7.1 Monterey done thanks

**Comment by aloewright** [comment]
Thank you!

**Comment by Fifof-hup** [comment]
Done for me also ! Thanks a lot
