### ISSUE TITLE
Task disappears in the week planner when moved to a daily note that hasn't been created yet

### ISSUE THREAD

**Issue by marco7m** [ivan-lednev/obsidian-day-planner#535]
**Describe the bug**
When moving a task from the week planner to a daily note that hasn't been created yet, the task disappears from the week planner and does not appear in the daily note.

**To Reproduce**
Go to the week planner.
Select a task and move it to a daily note that doesn't exist yet.
Check both the week planner and the newly created daily note.
See that the task has disappeared from the week planner and is not present in the daily note.

**Expected behavior**
The task should remain visible in the week planner and the Daily Note should be created, and then it should appear in the daily note without disappearing.

**Additional context**
This issue occurs only when the daily note has not been previously created. It may be related to how the application handles the creation of a new Daily Note in this context.

**Comment by ivan-lednev** [comment]
Hello @marco7m, when this happens, do you see any errors in the console? Can you send the files that you used? I can't reproduce the issue.

**Comment by PhilippHafe** [comment]
I experienced the same issue and found the reason for it is the "Templater" plugin.
My daily note template contains some Templater Code. 
Moving a task to a future date triggers the creation of a daily note, which then triggers the Templater Code.
In the "Weekly Plan" I first see the moved item on the day, then it disappears and is also not in the created daily note.

**Comment by PhilippHafe** [comment]
I experienced the same issue and found the reason for it is the "Templater" plugin. If I turn it off, it works fine.
If Templater is turned on, I first see the moved item on the day in the Weekly Planner View, and then it disappears and is also not in the created daily note.

**Comment by ivan-lednev** [comment]
Please update and re-check.
