### ISSUE TITLE
Tasks scheduled in another note for today can't be dragged into the timeline

### ISSUE THREAD

**Issue by AethelVeritas** [ivan-lednev/obsidian-day-planner#537]
**Issue:**
When a task that is from another note that isn't today's Daily Note is scheduled for today, it shows up in the Day Planner "tasks for today" preview but can't be dragged or dropped. After attempting the latter Day Planner freezes. This happens with a tag filter in Day Planner as well as with a folder filter.

**Steps to Reproduce the Issue:**
1. Create a new note.
2. Create a task in latter note and schedule it for today. Either put it in a folder or add a tag.
3. Enable either a by tag or by folder filter in Day Planner, then add the filter you applied to your task.
4. Try to drag and drop.

**Expected Behaviour:**
Tasks should be able to be dragged and drop, just like tasks/events created in a Daily Note are.

**Comment by ivan-lednev** [comment]
Please update and re-check.
