### ISSUE TITLE
Cause high CPU usage of 3rd cloud storage, like Dropbox, OneDrive, GooleD rive

### ISSUE THREAD

**Issue by WayneWH** [ivan-lednev/obsidian-day-planner#54]
Thanks for the great plugin.
---
I placed my obsidian vault in my Dropbox folder when I linked the data to my daily note.
 I made no changes to the daily notes, but it always triggers Dropbox to upload the "dailynote_xxx.md" file frequently. This makes the CPU usage very high. I wonder if the plugin will constantly modify the meta of the file when the progress diagram is active.

**Comment by SkepticMystic** [comment]
I have the same problem with Google Drive's Backup and Sync. The refresh rate for the Day Planner plugin is so frequent that the syncing software is constantly syncing changes. Is it possible to change the refresh rate?

**Comment by thim0o** [comment]
I have the same problem with Onedrive. 
It looks like the file is being written every second or so, even if there are no changes being made.
A check for changes before writing to the file would most likely fix this issue. 

Thanks for the plugin btw, it's very useful!

**Comment by shabegom** [comment]
I believe the same issue exists for Obsidian Sync. The Day Planner file syncs repeatedly. 

@WayneWH Would you mind changing the title of this issue to note the problem persists across multiple syncing platforms?
