### ISSUE TITLE
the status bar does not show the whole content of active task and the upcoming task

### ISSUE THREAD

**Issue by vincentssn** [ivan-lednev/obsidian-day-planner#542]
**Describe the bug**
the status bar does not show the whole content of active task and the upcoming task after upgrading to 0.22.1

**To Reproduce**
1. note the task as below: 
![image](https://github.com/user-attachments/assets/5bf4104e-9541-48ad-b53b-03d48827e8de)
2. look the status bar:
![image](https://github.com/user-attachments/assets/d2d96ed0-98b0-49a6-a10d-e82255fa2f2d)
It only shows the time of active task and upcoming task, not showing the **content(things 1 and things 2)**

**Expected behavior**
show things 1 and things 2, Intead of  time only.

**Screenshots**
![image](https://github.com/user-attachments/assets/46738dbb-60e6-49dd-99ce-476d0f044271)

**Additional context**
It shows completely in 0.21.1 as belows:
![image](https://github.com/user-attachments/assets/7dc18b21-7df6-42a1-a0bc-c95e1ed7927a)
Is it the new feature at version 0.22.1?

**Comment by vincentssn** [comment]
It shows completely in 0.21.1 as belows:
![image](https://github.com/user-attachments/assets/7dc18b21-7df6-42a1-a0bc-c95e1ed7927a)
Is it the new feature at version 0.22.1?

**Comment by lilskippyy** [comment]
It not a feature. Or at least it should not be a feature. 
I have the same issue, even if I toggle "show timestamp next to text in timeline"

**Comment by lilskippyy** [comment]
@vincentssn 

Btw, now I just rolled back and it's working fine again. Thanks for reminding me I could just do that till it's fixed.

**Comment by bluebirch** [comment]
Checkboxes and times should perhaps be trimmed from the line? It was before, wasn't it?

![image](https://github.com/user-attachments/assets/25f59dd8-1bdc-4e75-9b50-f076cbcbd476)
