### ISSUE TITLE
Timeline pane disappear every time open Obsidian

### ISSUE THREAD

**Issue by Toser24** [ivan-lednev/obsidian-day-planner#543]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar reports.

### Expected Behavior

Once the obsidian timeline is fixed it should remain in place.

### Current behaviour

I placed the timeline panel below the calendar panel.

![Screenshot 2024-09-12 234402](https://github.com/user-attachments/assets/fb18f152-017a-4150-8afc-c2a5f92185be)

What happens is that every time I start Obsidian the timeline panel isn't there and I'm forced to put it back in its place every time.

![Screenshot 2024-09-12 234738](https://github.com/user-attachments/assets/15bf800a-cccf-42c9-8f9d-40c5786664c3)

The strange thing is that as soon as obsidian starts I can see the timeline in its place (where I would like it to stay) but only for a second, after which it disappears as if it resets automatically.

Video here:
https://drive.google.com/file/d/1uRwYtvHvAVtSePXqhUjc6Xuf7DzT1YDt/view?usp=sharing

### Steps to reproduce

I attach video here:

https://drive.google.com/file/d/1uRwYtvHvAVtSePXqhUjc6Xuf7DzT1YDt/view?usp=sharing

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.6.7

### Possible solution

...

**Comment by batrand** [comment]
Can confirm this issue, happens to me as well

**Comment by ms3056** [comment]
Same here. I have to switch to my "workspace" manually every morning to put it in its place - for me the left side - but obviously manually dragging it works - until you restart again.

**Comment by ivan-lednev** [comment]
Available in 0.23.2
