### ISSUE TITLE
Feature Request: custom folder settings

### ISSUE THREAD

**Issue by JokeNeverSoke** [ivan-lednev/obsidian-day-planner#55]
I name my folders prefixed by emojis, and a "Day Planners" in my root dir would seem odd.

It seems that custom folders is already defined:
https://github.com/lynchjames/obsidian-day-planner/blob/d1eb7ce187e7757b7a3880358a6ee184b3b025da/src/settings.ts#L2

Adding a custom setting in the settings tab would be sufficient I guess?

**Comment by MMMikeM** [comment]
This would be very nice - alongside having a bit of control over the filename!

**Comment by fernandes** [comment]
My personal hack to this was create my custom folder - I use with emojis like you @JokeNeverSoke - with emoji and in a sub folder, then on terminal I created a symlink to it

example:

`ln -ns '🔬 foo/daily'  'Daily Planner'`

after enabling _file mode_ again, it's creating on the right folder

ps: still no success on a hack over filename hahaha

**Comment by MMMikeM** [comment]
> 
> 
> My personal hack to this was create my custom folder - I use with emojis like you @JokeNeverSoke - with emoji and in a sub folder, then on terminal I created a symlink to it
> 
> example:
> 
> `ln -ns '🔬 foo/daily' 'Daily Planner'`
> 
> after enabling _file mode_ again, it's creating on the right folder
> 
> ps: still no success on a hack over filename hahaha

I managed to get this sorted by modifying the compiled js. I couldn't get the ts compiling right for some reason.

**Comment by fernandes** [comment]
yes, changing it was my initial thought, I opted to create the symlink otherwise I'd need to change it every time it got a new update, symlink is something I have better control (and can be versioned 😉 )

**Comment by ivan-lednev** [comment]
Creating folders and files is now handled by `obsidian-periodic-notes`.
