### ISSUE TITLE
Feature Request: Time Tracker mode

### ISSUE THREAD

**Issue by pyjamads** [ivan-lednev/obsidian-day-planner#57]
I really like this plugin, but I tend to Track my time, instead of planning the time slots ahead of time. 

So in Time Tracker mode, the plugin should extend the current task as long as you haven't specified a next task starting after the current time, or added the END bullet.

Currently, these three tasks would show in the timeline as 1h, 1h and 0h even after 12:00, also kinda breaks the circular timers etc:

- [ ] 10:00 Task A
- [ ] 11:00 Task B
- [ ] 12:00 Task C

I'd like to be able to specify the tasks I need to do in a list, like:

- [ ] now Task A
- [ ] now BREAK
- [ ] now Task B
- [ ] now BREAK
- [ ] now Task C

Once I begin the task I use the [Natural Language Dates pluing](https://github.com/argenos/nldates-obsidian) to replace the word "now" with the current time:

- [x] 09:55 Task A
- [ ] 10:24 BREAK
- [ ] now Task B
- [ ] now BREAK
- [ ] now Task C

Once I finish Task A, I would ideally be able to use a shortcut to skip to the next task and replace the "now" automatically, but otherwise I can also do that manually. However, it should mark tasks as done, when you switch to a new task, and the status bar + timeline, should handle the last task item, as starting at the specified time, unless the last item is the "END" item, in which case the day is over.

A good example of this is the Toggl time tracker: ![](https://public-assets.toggl.com/b/assets/@toggl/track/images/timeline-activity-hover.96903dbe.png).

**Comment by mochsner** [comment]
I this feature would be a great thing to bake in together with the ability to "copy over" leftover tasks from the previous day. I tend to have a lot of work piled up, and while I do my best to schedule them through-out the day, naturally don't always get to complete them and just copy them to the next day. Bringing them to the "newest" task automatically (or via command) and replacing the time with something like "NOW" (above) or "##:##" would be top tier.

**Comment by lynchjames** [comment]
Picking things back up after a long break. This is an interesting idea and a way of using the plugin I had not thought of before. 

Something to consider as a difference from Toggl is that under a Time Tracker mode the plugin would not currently be able to be any gaps between tasks. Toggl (I think) defines a start and end time for each task to calculate its duration where as Day Planner calculates the duration as the difference between the start time of one task and the start time of the next task.

The "now" text would not need to be included. There could be a small addition to implement a command to add a checkbox with the current time to the line under the cursor which Day Planner would then recognise automatically and update the timeline etc.

**Comment by ivan-lednev** [comment]
Closing this as stale.
