### ISSUE TITLE
Stretch event to next no longer working

### ISSUE THREAD

**Issue by ms3056** [ivan-lednev/obsidian-day-planner#579]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar reports.

### Expected Behavior

My morning template has something like this:

```markdown
- [ ] 07:00 Morning Routine
- [ ] 09:00 - 10:00 Meeting 1
```
In the past the morning meeting would stretch - the setting to allow this is set. I did restart Obsidian after this last update (thanks for fixing it to stay in the last location btw). 

### Current behaviour

The morning task seems to default to 30 minutes. 

### Steps to reproduce

See above. 

### Which Operating Systems are you using?

- [ ] Android
- [X] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.7.3

**Comment by ms3056** [comment]
![image](https://github.com/user-attachments/assets/a69f076f-146c-43e8-8c67-de29c6b1454b)

**Comment by ms3056** [comment]
![image](https://github.com/user-attachments/assets/c366ed55-6148-455f-8003-ada7857be78b)

**Comment by epi-sam** [comment]
![image](https://github.com/user-attachments/assets/cbcd5854-a596-4a5a-8f78-daab420a460e)
![image](https://github.com/user-attachments/assets/dbff6ffe-3862-4000-81fe-d904725a82a4)

Seconding. I'm seeing this behavior as well.

Desktop, windows, obsidian 1.7.4

**Comment by queezz** [comment]
Same thing. However, it seems that this is due to the default task duration, which activates according to the description if there is no end time. And it's limited up to 120 minutes.

![image](https://github.com/user-attachments/assets/36806cc8-91bd-4aad-a732-233d312767d3)

**Comment by epi-sam** [comment]
Yeah this seems like and order of operations question.  First apply default lengths to all tasks, then stretch all tasks that are followed by a later task to that task's start time (if that option is ticked).  The last task should be the default task length.

edit: in fact the default length overrides the stretch option
![image](https://github.com/user-attachments/assets/72d72c81-00d5-424f-9499-ff96836c4109)

**Comment by ac1dTigR** [comment]
Having the same issue on android, latest version. All tasks are being set to the default length instead.

**Comment by ivan-lednev** [comment]
Please update and re-check.

**Comment by ac1dTigR** [comment]
Hi, I updated and now the plugin doe not seem to be displaying any tasks at all.

![Screenshot_20241103_135323_Obsidian](https://github.com/user-attachments/assets/351e93bc-5241-4dde-a1d2-43f783f36b6c)
![Screenshot_20241103_135317_Obsidian](https://github.com/user-attachments/assets/860d8149-ec7b-4fdc-9af1-e16d151135fb)
![Screenshot_20241103_135307_Obsidian](https://github.com/user-attachments/assets/3c710349-a2b2-4163-834c-9f68e32f6b7b)

**Comment by ivan-lednev** [comment]
Hello, fortunately, I can tell you at a glance that the issue is that you don't have a day planner heading. This was described as a breaking change in the release notes. I will fix that, but in the meantime you can configure the plugin to use some planner heading.

**Comment by ac1dTigR** [comment]
Ah! So sorry - I remember reading that in the release notes but forgot to add it.

Edit: I rechecked and it's stretching correctly - thank you for fixing it :)
