### ISSUE TITLE
ICS Calendar (GOOGLE) not showing up

### ISSUE THREAD

**Issue by punnypunnz** [ivan-lednev/obsidian-day-planner#583]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar reports.

### Expected Behavior

The timeline should show all my events for the day as synced to google ics, it works 10% of the time but reopening the app or doing resync does not work. The tasks manually done in Obsidian do sync though. 

### Current behaviour

Sometimes the events show up but very rarely. Nothing I do seems to work. 

![image](https://github.com/user-attachments/assets/3ae47957-d1c7-4644-ab8a-b970103e47c9)

![image](https://github.com/user-attachments/assets/3977429a-db5f-410a-9532-3160c30a3996)

### Steps to reproduce

Install Day Planner
Add ICS Remote Google calendar (it is a public viewable calendar)
Click go to daily note
Leave open for 20-30 mins, nothing shows up.
Press refresh. Nothing shows up.
Close app, reopen. Nothing shows up.

Does not work and on the rare occassion it works displays properly. It is just rarely syncing or showing.

### Which Operating Systems are you using?

- [ ] Android
- [X] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.6.7

**Comment by EmpathicSage** [comment]
I have the same issue. I cannot get the plugin to sync with Google Calendar. I tried both the public and private `.ics` links. First, I installed Day Planner, added the ICS link, tried refreshing, and restarted the app multiple times. Unfortunately, no events appear.

### Details

- Obsidian v1.6.7
- Windows 11 Enterprise version 23H2 build 22631.4169
- I did not experience intermittent syncing; it does not sync
- I tried reconnecting the Google account but saw no change
- I do not know how to access error logs

### Installed Plugins

- Dataview
- Day Planner
- Emoji Autocomplete
- Enhanced Symbols Prettifier
- Excalidraw
- Execute Code
- Gemini AI Assistant
- Github Copilot
- Kanban
- Linter
- Projects
- ReadItLater
- Spaced Repetition
- Tasks
- Text Generator

**Comment by ivan-lednev** [comment]
To resolve this, I'll need to see what's going on in the developer console (press `Control + Shift + I` and show me any errors you see there).

**Comment by LWaetzig** [comment]
Facing the same issue. Tried to sync with mit iCloud Calendar. Followed the same steps mentioned in the original post. Installed the plugins necessary (Day Planner & Dateview), filled the form with calendar name, email and public url. Waited for about 15 minutes, still no events. Pressed the manual refresh button, still no events. Closed the app, still no events. I also opened the console to watch for something like an error. Unfortunately no error.

## Details
- Obsidian v1.6.7
- MacOS Sequoia 15.0.1 (24A348)

## Other plugins
- Dataview
- Day Planner
- Excalidraw
- Folder notes
- Highlightr
- Natural Language Dates
- Outliner
- Paste image rename
- Style Settings
- Tasks
- Templater

## Settings
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/9eb4e62b-3132-4afd-b7ee-7db48a6fa8ce">

## Console
<img width="639" alt="image" src="https://github.com/user-attachments/assets/57ffc9dd-bf37-4179-9c2a-9eaa23a23c6d">


Would love to use this plugin :D

**Comment by ivan-lednev** [comment]
@LWaetzig can you please create and share the URL of a test calendar with a test event that I can use for debugging this? It should be somewhere here:
![image](https://github.com/user-attachments/assets/d43cc664-14dd-447b-adb3-6dd366d060c9)

**Comment by LWaetzig** [comment]
https://calendar.google.com/calendar/u/2?cid=ZjhiODJlOTE1MmZlZjgxYWVhZDEzNjM0NTY2M2MwY2QzZTEyYTgzZjNkM2ZjYzE3YTNjN2ZlZjc4NjM0MDMyMUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

Created a test event today at 5:30 pm

**Comment by ivan-lednev** [comment]
This doesn't look like an ical link. Check the Google page where you copied it, the link should have `.ics` at the end.
Make sure to follow the instructions:
![image](https://github.com/user-attachments/assets/ec0d01c7-ede0-44de-b4f3-778cbf5533a5)

**Comment by LWaetzig** [comment]
sorry my bad:
https://calendar.google.com/calendar/ical/f8b82e9152fef81aead136345663c0cd3e12a83f3d3fcc17a3c7fef786340321%40group.calendar.google.com/private-799717c3fab27ca1a7c7fd7ec06fd0df/basic.ics

**Comment by ivan-lednev** [comment]
@LWaetzig, the calendar you've shared doesn't have any events in it:
```
"BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Test Calendar
X-WR-TIMEZONE:Europe/Berlin
END:VCALENDAR
"
```

Are you sure you created an event in the right calendar? Did you create a Google task or an event?

**Comment by LWaetzig** [comment]
i checked and there is an event:
![image](https://github.com/user-attachments/assets/f3a1aeb4-483e-46e0-a35f-04d3623e1dd7)

* i recreated it, to make sure

**Comment by ivan-lednev** [comment]
Now I can see your event in my app:
![image](https://github.com/user-attachments/assets/f7625152-a571-4ee0-ade4-f8e6259a491f)

Can you try your link in your own app? My guess is that it's a matter of confusing the links, because otherwise I'm clueless 😅

**Comment by LWaetzig** [comment]
wow yes it works 🎉 
The question is, how can it work with iCloud Calendar? There is no option for an .ics link?

**Comment by ivan-lednev** [comment]
Wait a sec, what exactly was the reason it got fixed? Did you copy the link from the wrong place initially? If so, I need to update the docs, so that nobody runs into this later.

For iCloud, there is a separate issue. People seem to find some ways to make it work.

**Comment by LWaetzig** [comment]
i copied the link you mentioned (ending with .ics). Before i copied the "standard" public url of the calendar i wanted to integrate. Do you have the issue where people found a workaround for iCloud?

**Comment by ivan-lednev** [comment]
Just search for 'iCloud'

**Comment by rpj-07** [comment]
> Now I can see your event in my app: 
I have the same issue, but it does not work with the right private ical-Link. Can you try out this Link in your Vault:
https://calendar.google.com/calendar/ical/jahnke.rouven%40gmail.com/private-daaccb711da40ad5d25b8f0f216925b7/basic.ics
There are today some Events, but they do not show up in my Day Plan.
Thank you!

**Comment by thomaszdxsn** [comment]
> Just search for 'iCloud'

the icloud issue is the default icloud ical url is startswith `webcal://`, we need change it to `https://`

**Comment by ivan-lednev** [comment]
Seems to be an issue of copying the wrong link. Updated the docs to warn about this.
