### ISSUE TITLE
Allow events/tasks to continue past midnight (and show up on calendars)

### ISSUE THREAD

**Issue by winged-voices** [ivan-lednev/obsidian-day-planner#586]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Issues](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar feature requests.
- [X] I am only requesting a single feature. Multiple changes should be split into individual requests, with links between them.
- [X] I believe my requested feature will be generally applicable to other users, not just me: it is not uniquely tied to my personal workflow.

### 🔖 Feature description

It would be super helpful to be able to put things on a day planner that are scheduled for over midnight and have it show up automatically on the next day of the calendar (eg - [ ] 9:00pm - 3am tomorrow , or "9pm - 3:00am 2024-10-06" or something like that) 

Right now the only way to do it is to either make them all-day (which isn't always true) or restart the task again (which can end up with notifications and strange timeblocking issues, statuses, etc). 

This would allow for more freedom and better accuracy, status-tracking and notification for multi-day planning, events, and definitely for people like me who work at night and for whom a good part of their time blocking goes over the am/pm line. 

### ✔️ Solution

I think the solution here is the same as the description. I'd like to be able to write something like: 

- [ ] 9:00pm - 3:00am work 
OR
- [ ] 21:00 - 3:00 work 
and have the block on the timeline/weekly calendar/etc continue onto the next day, with the logic that if 3am is placed after 9:00pm, it's 3am on the next day (other ideas in "Alternatives"). 

### ❓ Alternatives

Currently, I solve this problem by scheduling tasks until 11:59pm and then again from 12:01 the next day; it's not very convenient or accurate, however. 

**Alternatives/Problem-Solving in Advance:** 
- It might be easier in 24hr -- for whatever the code needs to do to parse that, say, 15:00 - 3:00 must mean 3:00 the next day, than it would be for it to understand 3:00pm - 3:00am crosses midnight.  
    -  I'm not sure this is a big problem, since many calendars already make the next-day crossover even if you're using 12hr time, but if 12hr time is a pain, I would personally make the tradeoff to write overnight tasks in 24hr time only. 
- similarly, if it's easier to have the date present than have the function depend on parsing clock math, it seems like people who need this frequently would certainly still use it if they had to write in "tomorrow" or the YYYY-MM-DD of the finishing date, etc. 
    - So something like: 
        - [ ] 9:00pm - tomorrow 3:00am 
        - [ ] 15:00 - 3:00 2024-10-06 
        - [ ] 9:00pm 2024-10-05 - 3:00am 2024-10-06 
        - or various permutations of specifying the date on one or both sides

### 📝 Additional Context

It would be nice to be able to drag the block down past midnight, alternatively, but that's a little more complicated, I presume. While they're linked they're not 100% the same request, and I think being able to write am/pm crossovers on the bullet list and have them show up is MORE basic.

**Comment by ivan-lednev** [comment]
Please update and re-check. From release notes:
> - Tasks crossing midnight now get shown properly in multiple day columns instead of stretching the first day (#586, #364)
>    - E.g.: `- 23:00 - 4:00 Task` will get shown in 2 columns as 2 separate blocks
