### ISSUE TITLE
Apple Calendar Sync not working.

### ISSUE THREAD

**Issue by Fifof-hup** [ivan-lednev/obsidian-day-planner#607]
Hi Ivan and the team! 
thanks a lot for this marvelous Plug in! 

I would like to sync my Apple Cal in this format : webcal://p124-cald (..]  I copy this link in the remote Calendar section of the Day Planner parameters. 
This link is come form the URL copy of my apple calendar (Right Click on the calendar, Copy the URL) it's a public Calendar 

- The sync is not working. 

I Have another one form Outlook : https://outlook.office (...).ics and it's working well.
Can you help me? 
thanks a lot and happy Halloween !
Fifof

**Comment by ivan-lednev** [comment]
Hello, @Fifof-hup,
This is a duplicate, and [this is the solution from the original](https://github.com/ivan-lednev/obsidian-day-planner/issues/412#issuecomment-2156447266).

**Comment by Fifof-hup** [comment]
Tanks a lot for your quick following Ivan!Christophe FourcroyLe 1 nov. 2024 à 14:18, Ivan Lednev ***@***.***> a écrit :﻿
Hello, @Fifof-hup,
This is a duplicate, and this is the solution from the original.
