### ISSUE TITLE
Hide stand and end times

### ISSUE THREAD

**Issue by kevinawoo** [ivan-lednev/obsidian-day-planner#608]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Issues](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar feature requests.
- [X] I am only requesting a single feature. Multiple changes should be split into individual requests, with links between them.
- [X] I believe my requested feature will be generally applicable to other users, not just me: it is not uniquely tied to my personal workflow.

### 🔖 Feature description

Is it possible to hide the `start - end` times?

For example, when tasks get copied, it gets kind of unwieldy
<kbd>
![screenshot 2024-10-31 at 17 08 32](https://github.com/user-attachments/assets/8d46734c-34ca-4fef-8422-b13068b3df33)
</kbd>

I noticed in the Readme screenshots, it's nice and clean.

FYI, I'm on v0.24.0

### ✔️ Solution

none

### ❓ Alternatives

none

**Comment by ivan-lednev** [comment]
Closing this as a duplicate of #536
