### ISSUE TITLE
Connect to calendar

### ISSUE THREAD

**Issue by Gadwood** [ivan-lednev/obsidian-day-planner#61]
It would be nice to connect to microsoft exchange calendar to see appointment

**Comment by broskees** [comment]
+1 - iCal integration would probably do in general.

**Comment by abers** [comment]
This might work better as a separate plugin. I can imagine people want a whole range of different calendar and task integrations which would be hard to maintain.

For those looking for a temporary solution. With [vdirsyncer](https://github.com/pimutils/vdirsyncer), [templater](https://github.com/SilentVoid13/Templater), and some python it should be possible to setup a template for inserts today's calendar events.

**Comment by joshsvnd** [comment]
This would also be great in reverse. E.g. I plan my day with Obsidian Day Planner, and then can export this to iCal to keep me on track and get notifications when I need to switch task.

**Comment by muness** [comment]
FYI, I have a gcalcli + Templater solution am using to get my calendar appointments into a Day Planner friendly format over in the Obsidian [Share & Showcase forum](https://forum.obsidian.md/t/adding-your-google-calendar-agenda-to-your-daily-journal/16417/12?u=muness). A solution based on private ical URLs may be easier (no oauth2 hoops to jump through).

**Comment by ikcalB** [comment]
+1 
I'd really like some way to export tasks to a calender.
(I'm using webcal. but iCal or any other method should work as well)

@lynchjames do you have any plans to add export functionality?

**Comment by ivan-lednev** [comment]
Closing this as stale.

**Comment by muness** [comment]
For those looking for this, I've now published a separate plugin that does this and plays nice with Day Planner: https://github.com/muness/obsidian-ics
