### ISSUE TITLE
0.25.0 upate brok the plugin

### ISSUE THREAD

**Issue by endlessblink** [ivan-lednev/obsidian-day-planner#611]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar reports.

### Expected Behavior

Adding a task by choosing time slots 

### Current behaviour

Task disappears after a couple of seconds after adding it to the day planner. 

### Steps to reproduce

Updating to version  0.25.0

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.7.4

**Comment by ivan-lednev** [comment]
Hello, @endlessblink, this issue is close to useless, because it does not follow the issue template and has close to zero details in it. It does not allow me to reproduce it and work on it. Please respect my time and follow the template by providing as much useful information as you can.
