### ISSUE TITLE
Unable to interact with blank sections of the timeline or shorten blocks

### ISSUE THREAD

**Issue by neongrey** [ivan-lednev/obsidian-day-planner#613]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar reports.

### Expected Behavior

When I change the times on a block, I expect the timeline to update accordingly. I expect to be able to click and drag on timeline blocks and be able to extend their lengths. I expect to be able to add blocks by clicking and dragging on the timeline. Some of the behaviour I'm experiencing is also documented in #612, however that's not the main point of this particular report. 

I am discussing the previously-reported behaviour because it comes up in the process of putting a block on the timeline to show that I can't manipulate it in the hopes that it's helpful, but the issue this report is about is the inability to shorten the block or interact with blank sections of the timeline.

### Current behaviour

- If I click and drag on the timeline, nothing happens, as if I had not clicked or interacted with the panel at all. No reaction whatsoever. I should be able to create a new block by dragging on the timeline. This doesn't happen.
- If I manually add an entry to the timeline, it appears, but the times are wrong as per #612 and are always one hour back. This occurs not only with drag and drop as that report states, but also via editing the text.
![b355f6ddbf 1](https://github.com/user-attachments/assets/835538ac-b8b5-43f0-ac29-beba8da4424f)

    - That is: if I extend the length of the block to be 2 hours, by editing the length in the note, it updates the length, but not the start time.
    - If, after having adjusted the block as above, I then change the start time to be later, it will move the start of the block to be one hour prior to the new start time.
    - If I adjust the block to be *earlier* it will start from an hour earlier than set to. 

- Anyway, now that a block exists on the timeline, hovering over the upper edge does not change the cursor or allow me to drag.
- I can drag and drop the block as-is.
- Coming from below, the cursor does change. If I click as if to manipulate the length of the block, the block will not follow my cursor if I attempt to drag it longer. If I drag the cursor up to make it shorter, the change will not be made after I release the button. (i'm aware of the other text from the note that shows-- i'm not concerned by it, nothing particularly personal is revealed)
![e764c29bde 1](https://github.com/user-attachments/assets/eb3ba000-0033-4adf-b40c-e3073bf21266)

### Steps to reproduce

detailed in explaining the current behaviour.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.7.4

**Comment by ivan-lednev** [comment]
@neongrey, judging from the screenshot, you haven't updated the plugin for some months now. Please update and re-check.

**Comment by neongrey** [comment]
well this is embarrassing. yes, that's fixed it.
