### ISSUE TITLE
automatically link it to the daily planner once a daily note is created? 

### ISSUE THREAD

**Issue by Warden20** [ivan-lednev/obsidian-day-planner#62]
It would be awesome if the day planner uses the daily note

**Comment by 3YH** [comment]
This would be nice, I now do it manually. Takes one command by setting the plugin to Command mode and using a planner template in Daily Notes settings. Then firing the 'Link todays planner to current note' command inside the Daily Note using Ctrl/Cmd + P > Link > Enter.

**Comment by symph0nic** [comment]
You can make it ever so slightly quicker by binding a hotkey to the 'Link today's planner..' command too - I use Ctrl+Shift+P, and that works well.

**Comment by isle99** [comment]
> You can make it ever so slightly quicker by binding a hotkey to the 'Link today's planner..' command too - I use Ctrl+Shift+P, and that works well.

Or you can use a button for the command.

**Comment by barbosarp** [comment]
+1 on the feature proposal

**Comment by ivan-lednev** [comment]
From 0.7.0, the plugin is connected to daily notes.
