### ISSUE TITLE
Breaks frontmatter in daily notes when 'day planner heading' is empty in settings

### ISSUE THREAD

**Issue by willschetelich** [ivan-lednev/obsidian-day-planner#625]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar reports.

### Expected Behavior

Usually, when I 'drag and drop' on the timeline, day planner appends the text to the end of my daily note, not affecting anything else in my daily note. 

Thanks so much for the help!!!!!!

### Current behaviour

Now, whenever I drag and drop, it affects the rest of my daily note, messing with my YAML!

### Steps to reproduce

Picture 1: My daily note when I have just created it, using a template. 
<img width="888" alt="Screenshot 2024-11-11 at 10 13 38 AM" src="https://github.com/user-attachments/assets/1d495447-9382-4449-93af-299a10f005f1">
<img width="871" alt="Screenshot 2024-11-11 at 10 14 02 AM" src="https://github.com/user-attachments/assets/7cf76215-e9d1-4dcd-8f8f-7ee9669fd001">

Picture 2: When I drag and drop in the timeline one time!

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version

1.7.5

### Possible solution

I believe the problem has to do with it adding '***' at the start of my daily note! Messing with front matter!

**Comment by willschetelich** [comment]
PS - I love your plugin, it has helped me so much!!!

**Comment by willschetelich** [comment]
UPDATE! SOLVED IT!
Just had to add
# Day Planner

to my daily notes template!! Thanks!!!

**Comment by willschetelich** [comment]
<img width="1097" alt="Screenshot 2024-11-11 at 10 37 15 AM" src="https://github.com/user-attachments/assets/feafd816-2496-4343-93a1-b9881aec959a">

Just add it to the template!

**Comment by yanqing-song** [comment]
I have the same problem too. 
Besides, it messes up embedded file links when drag and drop. I have underscores `_` in linked file names. A backslash is added before each underscore, it becomes `\_`  and the links are all invalid.

**Comment by wenruoxu** [comment]
Yes, I also encountered the same problem.

**Comment by ivan-lednev** [comment]
@yanqing-song, this is a different issue. Please create another one and add to it the markdown that gets broken on edits.

**Comment by ivan-lednev** [comment]
A temporary fix is disabling automatic sorting of entries on edits.

**Comment by ivan-lednev** [comment]
Fixed in 0.26.2. Please update and re-check.

**Comment by yanqing-song** [comment]
> @yanqing-song, this is a different issue. Please create another one and add to it the markdown that gets broken on edits.

issue #635
