### ISSUE TITLE
Gantt (re)calculations any time after the named day

### ISSUE THREAD

**Issue by lwb52** [ivan-lednev/obsidian-day-planner#63]
I am making this a separate request related to a comment made on the Gantt-past-midnight suggestion: allow Gantt CHART modification to take place on any day, so that revisions to the schedule on a note of one day can be calculated in the chart after that midnight, or many days later. Days go well past 24:00, and being away from the desktop without a mobile version of Obsidian makes it impossible for the Gantt Chart to ”catch up” when back at the desk, even if the source schedule has been modified in a mobile app. (If validation of data-entry date is needed, for teams or other work purposes, then the latest ”calculated-on” time-stamp could be added automatically at the bottom of the G-chart.)

**Comment by ivan-lednev** [comment]
Mermaid is no longer supported.
