### ISSUE TITLE
Show full task name on hover in Timeline view

### ISSUE THREAD

**Issue by kahboom** [ivan-lednev/obsidian-day-planner#634]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Issues](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar feature requests.
- [X] I am only requesting a single feature. Multiple changes should be split into individual requests, with links between them.
- [X] I believe my requested feature will be generally applicable to other users, not just me: it is not uniquely tied to my personal workflow.

### 🔖 Feature description

When I hover over a task in the Timeline view that has been shortened with an ellipse, it should show the entire task name.

### ✔️ Solution

Show a standard or native tooltip with the full name of the task

### 📝 Additional Context
Example of how sometimes it gets cut off and there is no easy way to view the task.

**Comment by ivan-lednev** [comment]
Hello, @kahboom, try pressing `Ctrl` and hovering over a task. This should trigger a hover preview of the file.

**Comment by kahboom** [comment]
Thanks, sorry I didn't catch that :)

**Comment by kazerniel** [comment]
Just adding for anyone who stumbles upon this thread like I did, that you need the Page Preview core plugin activated for this to work.
