### ISSUE TITLE
Time tracker not pulled into timeline / sidebar

### ISSUE THREAD

**Issue by kam-hak** [ivan-lednev/obsidian-day-planner#637]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar reports.

### Expected Behavior

Thanks so much for the work on Day Planner. I'm excited about the new time tracking function!
I believe the timeline view of Day Planner should display ongoing clocks, displaying them under 'active clocks'. 

### Current behaviour

As can be seen, when I start clocks, they are created in the note correctly, but this does not seem to be pulled into my timeline. There should be 3 ongoing clocks, but 0 are found.

My add-on did not detect clocks with or without time-blocks, nor outside of the ## day planner heading.

<img width="1416" alt="Screenshot 2024-11-19 at 11 56 22" src="https://github.com/user-attachments/assets/746388df-5e7e-4ed3-9779-268de9ce4839">

### Steps to reproduce

start a clock for a task. Look to see if it displays in timeline.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version

1.7.7

**Comment by ivan-lednev** [comment]
Hello, @kam-hak, thanks for reporting this! Please update and re-check.

**Comment by kam-hak** [comment]
> Hello, @kam-hak, thanks for reporting this! Please update and re-check.

Hi @ivan-lednev! Thanks for the fast response :). I've updated but am still not seeing active clocks. What additional info may be useful?

**Comment by ivan-lednev** [comment]
Keep in mind that you need to have a dataview filter that includes your daily notes. So if your daily notes are in `daily-notes`, your filter should be at least `"daily-notes"`.

**Comment by kam-hak** [comment]
> Keep in mind that you need to have a dataview filter that includes your daily notes. So if your daily notes are in `daily-notes`, your filter should be at least `"daily-notes"`.

Ah! I mistakenly thought it default included my ## day planner section. It is working now... thank you, again!
