### ISSUE TITLE
Time tracking not working

### ISSUE THREAD

**Issue by pkelly102** [ivan-lednev/obsidian-day-planner#647]
### Discussed in https://github.com/ivan-lednev/obsidian-day-planner/discussions/646

<div type='discussions-op-text'>

<sup>Originally posted by **pkelly102** November 25, 2024</sup>
I'm excited about the new Time Tracking feature, but it isn't working on my Obsidian. Here is a screenshot of the settings - there should be an active clock for "buy milk" like the example in the documentation. The plugin seems to be able to recognize it, as right clicking on the entry gives me the option to "clock out," but in the timeline view there is no "active clock" running. 
<img width="802" alt="Screenshot 2024-11-25 at 10 14 28 AM" src="https://github.com/user-attachments/assets/8001ff33-2e20-4a03-8e44-1459b0d8437b">
<img width="846" alt="Screenshot 2024-11-25 at 10 15 15 AM" src="https://github.com/user-attachments/assets/5a5d6fe2-cd7b-4e7b-bf40-d68af717685f">
<img width="950" alt="Screenshot 2024-11-25 at 10 15 29 AM" src="https://github.com/user-attachments/assets/3fd901a2-4748-42e4-8a30-cd0e63011f15">
</div>

**Comment by ivan-lednev** [comment]
Hello, @pkelly102, for now you should explicitly include your daily notes folder into the source filter. If your daily notes are at the top of the vault, you can mark tasks with clocks with `#task` and include `#task` into the filter.

This will change in a future release.

**Comment by pkelly102** [comment]
Worked perfectly!! Thanks so much for your help.
