### ISSUE TITLE
Link to the same day planner every day?

### ISSUE THREAD

**Issue by ron0studios** [ivan-lednev/obsidian-day-planner#67]
As far as I've seen so far, the day planner allows for you to link certain files, or add the day planner template to a file for the rest of the day, viewing the timeline for that file through that day, until the next day, when it unlinks again. Personally, I usually don't change my daily routine so much every day, so it can be quite a frustratioin to keep having to copy and paste every morning. **Is it possible to keep the day planner linked to the same file forever?** 
I tried messing with the code (I have never used typescript or javascript, so I had no idea what i was doing haha), and thought to make the plugin think that its in the same day by changing the "new Date()" snippet in the code. I realized how many times that snippet was used, so backed down in the end.
Are there any present solutions to this? And how would it be done?

**Comment by rudrrayan** [comment]
I have just noticed how often a similar question to this has been asked: to link a template to every new daily note, which follows the same premisis. I believe a quick and dirty solution would be disabling time for the main.js file itself or something like that, sorry for bringing up the same idea again

**Comment by fakeharxy** [comment]
Just to add I came here looking for this - It's not so much I have to create a new planner every day, but I have to navigate to my planner page (as above, my schedule is the same every day) and then "link current file to planner". It would be great for it to just take my planner file every day (even better if I could have one for weekday, one for weekend, but one step at a time :) )

Thanks for making a great plugin!

**Comment by nathan005** [comment]
Seems like you can do this from this other comment:

> You can modify the default template by opening the main.js in the plugin folder.
> And on line 45 const DAY_PLANNER_DEFAULT_CONTENT = ``
> has the default template in there.

**Comment by ivan-lednev** [comment]
Closing this as stale. If you still have the interest, please reopen with a comment.
