### ISSUE TITLE
Feature Request: Link Tomorrow's Day Planner

### ISSUE THREAD

**Issue by Elizabethcase** [ivan-lednev/obsidian-day-planner#75]
Thanks so much for your work on this.

I often plan the next day the night before. Is there any way we can link the day planner to the date of the note, or does it always have to be done day of?

**Comment by EsbenLorenzen** [comment]
Bump. Being able to plan tomorrows tasks, would indeed be very useful.

**Comment by bduplanty** [comment]
Agreed!

**Comment by barbosarp** [comment]
+1

**Comment by JimGrange** [comment]
+1

**Comment by balint-bg** [comment]
As an added note, one use case is: I know I have to do tasks X, Y and Z on days A, B and C. I'd love to be able to create daily planner notes in advance for days A, B and C, add tasks X, Y and Z to them. So when the plugin is triggered to create a new day's note, it could check if a note already exists for that day, and just not create a new one (thus preventing overwriting the pre-created notes for days A, B and C).
I may have over-complicated the description with all the single-letter codenames for days and tasks but hopefully it makes sense :) If not, happy to provide more (and clearer) info!
And, thank you so much for all the work you've been doing here. I can only hope that you have an idea of how much easier you made lots of people's lives with this plugin.

**Comment by jgarr16** [comment]
👍🏻

**Comment by ivan-lednev** [comment]
Available in 0.7.0.
