### ISSUE TITLE
Not an Issue... Day Planner from Google Calendar

### ISSUE THREAD

**Issue by muness** [ivan-lednev/obsidian-day-planner#80]
An FYI...

I put together a Templater + gcalcli way to create a Day Planner list from Google Calendar. Instructions are at the [Obsidian Forum](https://forum.obsidian.md/t/adding-your-google-calendar-agenda-to-your-daily-journal/16417/12?u=muness). I'd be happy to submit a PR if you want to add a reference to it in the README.

**Comment by ivan-lednev** [comment]
Hello, @muness! Thank you for a great companion plugin! I'm going to add it it README shortly.
