### ISSUE TITLE
[Feature Request] Automove unfinished tasks to the next day.

### ISSUE THREAD

**Issue by cocoonkid** [ivan-lednev/obsidian-day-planner#84]
[Feature Request] Automove unfinished tasks to the next day.

**Comment by manuelalonso** [comment]
Second this.  I have so far unable to rollover finished or unfinished tasks to next day note.  Is that working for you, so next day you have a new Day Planner file with all unfinished tasks?

**Comment by ivan-lednev** [comment]
Closing this as stale. If you're still interested in this feature, please reopen the issue with a comment.
