### ISSUE TITLE
Day planner both status task not working

### ISSUE THREAD

**Issue by amriamiruddin** [ivan-lednev/obsidian-day-planner#87]
Both status displayed in active task and  circular progress not working. It's written ALL DONE at the bottom there. Anyone know how to fix this issue ? I'm using the latest obsidian, plugin and mac big sur. thank you

**Comment by lynchjames** [comment]
That would suggest that there is no task with a time in the future. Are you specifying all task times in 24 hour clock e.g. 15:30?

Could you share some example task markdown including the task times and the time of day when you are seeing this issue?

**Comment by ivan-lednev** [comment]
Should be fixed in 0.7.0.
