### ISSUE TITLE
Passing day tasks to next day

### ISSUE THREAD

**Issue by manuelalonso** [ivan-lednev/obsidian-day-planner#91]
Hi!

I have started today to use Day Planner and I was surprised how quickly it became familiar.  However I am not sure that having to copy-paste uncompleted tasks from the day before is very efficient.

I am sure you have seen another plugin called Rollover Daily Todos that works with the Daily Note and I wonder if there is some way for you to put this feature into Day Planner.  

I am sure people would support this development.  I am willing to make a donation for sure.

Thanks!

Manuel

**Comment by 6-AND-9** [comment]
+1

**Comment by barbosarp** [comment]
+1

**Comment by andrej1919** [comment]
+1

**Comment by ivan-lednev** [comment]
Should be fixed in 0.7.0.
