### ISSUE TITLE
Can't get rid of the Day Planner Plugin. Help!

### ISSUE THREAD

**Issue by raptHrafna** [ivan-lednev/obsidian-day-planner#94]
First off:  I'm really impressed with the plugin, but after trying it out, I realized that I just wasn't ready with my time blocking approach to utilize this excellent piece of programming.  I turned it off, and later I tried to delete it.

It is not currently on my list of plugins when I open obsidian.  Nevertheless, it is still creating a new planner note, every day.  When I delete the note, in two seconds, it creates a new one.

To complicate matters, I switched the location of my original vault to accommodate the mobile obsidian app.

Now the plugin creates a new folder with the name of my vault in the old location of the vault, and within it a folder named Day Planner, and within it a new, empty, dsayplanner note.  Why can't I get rid of this?  I've tried deleting the dot files and re-installing obsidian from scratch.  Cannot kill Day Planner.  Please help!

**Comment by lynchjames** [comment]
Sorry you are having problems killing Day Planner! The day planner folder should not be created when the plugin is disabled or uninstalled. It sounds like the plugin failed to fully uninstall for some reason. I'll keep this issue open to try to reproduce and fix the issue you have had.

You can completely remove the plugin by using a file explorer to access the .obsidian folder in your vault. Once you delete the folder on the path `.obsidian/plugins/obsidian-day-planner`, the plugin is completely removed and you should no longer have rogue folders and files created.

**Comment by raptHrafna** [comment]
I appreciate any help you can give.

R. Anthony Perez-Tamayo, MD, PhD
Associate Professor
Residency Program Director
Department of Thoracic and Cardiovascular Surgery
Loyola University Medical Center
Chief, Cardiothoracic Surgery
Hines Veterans Administration Hospital

**Comment by carbeer** [comment]
Commenting to let you know that I had the same issue (Obsidian v1.03 on Ubuntu 20.04 LTS). The folder was recreated despite the plugin being disabled or even uninstalled. I could resolve it by closing Obsidian, and running `rm -rf "Day Planner"`afterwards. I didn't check whether there were any remainders of the plugin in the .obsidian/ folder before, but now, it doesn't seem like that's the case anymore.

**Comment by ivan-lednev** [comment]
Should be fixed in 0.7.0.
