### ISSUE TITLE
Remove "Track current time" setting from sidebar view

### ISSUE THREAD

**Issue by darkcaldera** [ivan-lednev/obsidian-day-planner#95]
I always have this setting turned on, so it adds visual clutter to the sidebar to show it there constantly. It also takes up space in the sidebar, so there is less room to show the timeline itself. (I have a few plugins using this area!)

Perhaps this could be moved into Settings or toggled from the command panel, so it's easier to focus on the timeline. If there *is* a common reason to show it there constantly, perhaps its visibility could be toggled from Settings to suit the user.

The setting keeps turning itself to "off", as well, even though it seems to still be on and continuing to work. This is a nuisance.

(Also, if anyone can suggest a trick I can use in the meantime I would appreciate it!)

**Comment by vovkkk** [comment]
> if anyone can suggest a trick I can use in the meantime

You can create a CSS snippet in Settings → Appearance:

```css
#scroll-controls {
	display: none !important;
}
```

but then you won’t be able to switch on the auto-scroll quickly after a manual scrolling the timeline.

**Comment by ivan-lednev** [comment]
The setting is no longer present in 0.7.0.
