### ISSUE TITLE
How to include a horizontal Mermaid Gantt chart?

### ISSUE THREAD

**Issue by 6-AND-9** [ivan-lednev/obsidian-day-planner#97]
Hi, 

I really like your plugin, looking forward to see which improvements you will implement.

A question though: how can I include that horizontal Mermaid Gantt chart? The plugin page just says it can be done, but doesn't explain how. 

I'm sorry if I'm asking a stupid question, I am a novice to Obsidian in general.

**Comment by anijatsu** [comment]
Pretty sure you just need to tick the option in Obsidian's Plugin settings, for it to be included in the daily planner-linked files.
<img width="967" alt="daily planner gantt" src="https://user-images.githubusercontent.com/1882015/125786540-57daf2da-8cf4-4aab-bed6-c0dfceb6770b.png">

**Comment by ivan-lednev** [comment]
Mermaid is no longer supported.
