### ISSUE TITLE
No planner data or timeline appear with the example.md

### ISSUE THREAD

**Issue by PannenetsF** [ivan-lednev/obsidian-day-planner#98]
I love this app and use it for daily plans! I tried the **timeline** with the [example](https://github.com/lynchjames/obsidian-day-planner/blob/main/examples/day-planner-example.md) provided and it shows nothing.

app version: obsidian insider 0.12.10(latest)

I would be appreciate if anyone could help!

![image](https://user-images.githubusercontent.com/45866836/125951358-0cb5f84e-18a3-42fe-93b1-525872391cf0.png)

**Comment by rebecca1994759** [comment]
me too！！its strange！！

**Comment by nmottagh** [comment]
Plus 1.

**Comment by eterlan** [comment]
hello everyone, I find this mysterious bug today. But fortunately I find out it does appear in the new vault. So I backup my day planner folder and just delete it, then reinstall the plungin. boom, it works again. Holp that help lol.

**Comment by Simplywip** [comment]
I have the same problem. But I found that for me, if I'm writing in Day Planner's notes it works. But if I transfer the schedule to Daily Notes, and change from File mode to Command mode. It doesn't work.
Even after force reload, reinstall, re-enable, nothing works if I don't keep it under Day Planner's note

**Comment by rgrangeiro** [comment]
After make the change file mode to the command mode and selected the 'Daily note' use the option command: "Day Planner: Link today's Day Planner to the current note" 
![image](https://user-images.githubusercontent.com/5529832/157520497-d5436799-c1ae-4e0a-b422-5efc1af63596.png)

**Comment by PannenetsF** [comment]
Oh thank you, and it works! :)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 凌晨3:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lynchjames/obsidian-day-planner] No planner data or timeline appear with the example.md (#98)





 
After make the change file mode to the command mode and selected the 'Daily note' use the option command: "Day Planner: Link today's Day Planner to the current note"

**Comment by jgauna** [comment]
The plugin creates a folder called "Day Planners" so make sure you create the files inside that folder and then follow the @rgrangeiro [note](https://github.com/lynchjames/obsidian-day-planner/issues/98#issuecomment-1063293143)

**Comment by ivan-lednev** [comment]
Should be fixed in 0.7.0.
