### ISSUE TITLE
Contribution Request - Google Calendar Sync for Meetings

### ISSUE THREAD

**Issue by urishiraval** [ivan-lednev/obsidian-day-planner#99]
Hi There,

Just wanted to ask if adding Google Calendar syncing to the daily planner is something that you guys would be open to.

I cloned this project and plugged in some code (that I took from another project) for adding google calendar events to the planner and I'm a good way in. I just had a few questions about how best to add the events to the planner in the most efficient/maintainable way.

I think I've done a good job of decoupling the syncing from the rest of the system by creating a seperate 'engine'. The engine handles the 2 factor auth, refreshing of sessions, token management, the fetching of data and the creation of 'PlanItem' objects with its own factory but I'm a bit unsure how to proceed from here.

Would love your guys input about whether this is something you guys would want + whether I'm on the right track with how I've implemented things.

**Comment by hieu6** [comment]
a google calendar sync would be very interesting. i'm not a developer so can't offer assistance there, but do want to offer my enthusiastic support.

**Comment by urishiraval** [comment]
> a google calendar sync would be very interesting. i'm not a developer so can't offer assistance there, but do want to offer my enthusiastic support.

So this is now in the works...still a bit wonky about how best to plug in my gcal sync but I'll be making a PR in the near future hopefully

**Comment by edhilgendorf** [comment]
Did this ever work? Would love to use it

**Comment by ivan-lednev** [comment]
There is a plugin that does just that: https://github.com/muness/obsidian-ics

**Comment by c-jw** [comment]
@urishiraval It sounds like the feature you proposed goes beyond the ICS integration currently in the Day Planner plugin.  Does your google 'engine' allow for editing and creation of events from inside Obsidian?  If so, that is more fully featured that the current read-only ICS approach.
